### ISSUE TITLE
Table support?

### ISSUE THREAD

**Issue by WillemMali** [raphlinus/pulldown-cmark#104]
I tried using this table:

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

But it doesn't render as a table, just as text. I haven't found a way to get tables to work yet. The project I'm using `pulldown-cmark` in is [here](https://gitlab.com/willemmali-rust/markbrowse).

**Comment by raphlinus** [comment]
You need to call `Parser::new_ext` instead of `Parser::new` and set `[OPTION_ENABLE_TABLES](https://docs.rs/pulldown-cmark/0.1.0/pulldown_cmark/constant.OPTION_ENABLE_TABLES.html)`. The documentation could be better here.

**Comment by marcusklaas** [comment]
There's now an example that shows how to enable extensions in the example directory.
