### ISSUE TITLE
How to enumerate headings?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [raphlinus/pulldown-cmark#106]
Is there a way to enumerate headings in the rendered HTML? I was thinking about using something similar to the examples in the readme, counting headings in each level and adding something to headings inside the rendered HTML, but maybe there is already some undocumented option like:

    let mut opts = Options::empty();
    opts.insert(pulldown_cmark::OPTION_ENABLE_TABLES);

**Comment by ZelphirKaltstahl** [comment]
I've now written some code for reacting to events to get enumerated headings:

    pub fn render_post(file_content: String) -> String {
        let mut result = String::new();
        let mut parser = create_parser(file_content);
        // enumerate headings
        // let parser = parser.map(|event| match event {
        //     Event::Text(text) => Event::Text(Cow::from(text.replace("afaik", "as far as I know"))),
        //     _ => event
        // });

        let mut heading_counts: Vec<i32> = vec![0, 0, 0, 0, 0, 0];
        let mut in_headings_status: Vec<bool> = vec![false, false, false, false, false, false];

        for index in 0..6 {
            let heading_level = index + 1;
            parser = parser.map(|event| match event {
                Event::Start(Tag::Header(heading_level)) => {
                    heading_counts[index] += 1;
                    in_headings_status[index] = true;
                    Event::Start(Tag::Header(heading_level))
                },
                Event::End(Tag::Header(1)) => {
                    in_headings_status[index] = false;
                    heading_counts[index] -= 1;
                    Event::End(Tag::Header(heading_level as i32))
                },
                _ => event
            });
        };

        let parser = parser.map(|event| match event {
            Event::Text(text) => {
                match in_headings_status.iter().position(|&r| r == true) {
                    Some(in_heading_level) => {
                        let mut number_and_dot_space = String::new();
                        for heading_index in 0..in_heading_level {
                            number_and_dot_space.push_str(&heading_counts[heading_index].to_string());
                            number_and_dot_space.push_str(".");
                        }
                        // space to separate numbering from heading text
                        number_and_dot_space.push_str(" ");
                        number_and_dot_space.push_str(&text);
                        Event::Text(Cow::from(number_and_dot_space))
                    },
                    None => Event::Text(text)
                }
            },
            _ => event
        });

        html::push_html(&mut result, parser);
        result
    }

However, this does not work, because of some issues with updating the parser inside the loop:

    expected type `pulldown_cmark::Parser<'_>`
       found type `std::iter::Map<pulldown_cmark::Parser<'_>, [closure@/home/user/development/Rust/blog/src/includes/blog_post_reader.rs:45:29: 57:10 heading_counts:_, index:_, in_headings_status:_, heading_level:_]>` [E0308]

I could do it without loops and shadow the `parser` variable, but it would be a lot of duplicated code for the different heading levels, so I tried to put it into a loop. However, now I don't know how to fix the mentioned problem at `let parser = parser.map …`.

**Comment by ZelphirKaltstahl** [comment]
Here is my temporary solution to enumerate headings:

    pub fn render_post(file_content: String) -> String {
        let mut result = String::new();
        let parser = create_parser(&file_content);
        let mut heading_counts: Vec<i32> = vec![0, 0, 0, 0, 0, 0];
        let mut in_headings_status: Vec<bool> = vec![false, false, false, false, false, false];

        let parser = parser.map(|event| match event {
            // soooo much duplicated code here!
            Event::Start(Tag::Header(1)) => {
                heading_counts[0] += 1;
                heading_counts[1] = 0;
                heading_counts[2] = 0;
                heading_counts[3] = 0;
                heading_counts[4] = 0;
                heading_counts[5] = 0;
                // println!("heading level 1 started, resetting heading counts for 2,3,4,5,6");
                // println!("heading counts: {:?}", heading_counts);
                in_headings_status[0] = true;
                Event::Start(Tag::Header(1))
            },
            Event::End(Tag::Header(1)) => {
                in_headings_status[0] = false;
                // heading_counts[0] -= 1;
                Event::End(Tag::Header(1))
            },
            Event::Start(Tag::Header(2)) => {
                heading_counts[1] += 1;
                heading_counts[2] = 0;
                heading_counts[3] = 0;
                heading_counts[4] = 0;
                heading_counts[5] = 0;
                // println!("heading level 2 started, resetting heading counts for 3,4,5,6");
                // println!("heading counts: {:?}", heading_counts);
                in_headings_status[1] = true;
                Event::Start(Tag::Header(2))
            },
            Event::End(Tag::Header(2)) => {
                in_headings_status[1] = false;
                // heading_counts[1] -= 1;
                Event::End(Tag::Header(2))
            },
            Event::Start(Tag::Header(3)) => {
                heading_counts[2] += 1;
                heading_counts[3] = 0;
                heading_counts[4] = 0;
                heading_counts[5] = 0;
                // println!("heading level 3 started, resetting heading counts for 4,5,6");
                // println!("heading counts: {:?}", heading_counts);
                in_headings_status[2] = true;
                Event::Start(Tag::Header(3))
            },
            Event::End(Tag::Header(3)) => {
                in_headings_status[2] = false;
                // heading_counts[2] -= 1;
                Event::End(Tag::Header(3))
            },
            Event::Start(Tag::Header(4)) => {
                heading_counts[3] += 1;
                heading_counts[4] = 0;
                heading_counts[5] = 0;
                // println!("heading level 4 started, resetting heading counts for 5,6");
                // println!("heading counts: {:?}", heading_counts);
                in_headings_status[3] = true;
                Event::Start(Tag::Header(4))
            },
            Event::End(Tag::Header(4)) => {
                in_headings_status[3] = false;
                // heading_counts[3] -= 1;
                Event::End(Tag::Header(4))
            },
            Event::Start(Tag::Header(5)) => {
                heading_counts[4] += 1;
                heading_counts[5] = 0;
                // println!("heading level 5 started, resetting heading counts for 6");
                // println!("heading counts: {:?}", heading_counts);
                in_headings_status[4] = true;
                Event::Start(Tag::Header(5))
            },
            Event::End(Tag::Header(5)) => {
                in_headings_status[4] = false;
                // heading_counts[4] -= 1;
                Event::End(Tag::Header(5))
            },
            Event::Start(Tag::Header(6)) => {
                heading_counts[5] += 1;
                // println!("heading level 6 started");
                // println!("heading counts: {:?}", heading_counts);
                in_headings_status[5] = true;
                Event::Start(Tag::Header(6))
            },
            Event::End(Tag::Header(6)) => {
                in_headings_status[5] = false;
                // heading_counts[5] -= 1;
                Event::End(Tag::Header(6))
            },

            Event::Text(text) => {
                let mut text_event_result = String::new();
                match in_headings_status.iter().position(|&r| r == true) {
                    Some(heading_level) => {
                        // println!("in heading level: {} with text: {}", heading_level+1, text);
                        for ind in 0..heading_level+1 {
                            text_event_result.push_str(&heading_counts[ind].to_string());
                            text_event_result.push_str(".");
                        }
                        text_event_result.push_str(" ");
                        text_event_result.push_str(&text);
                        Event::Text(Cow::from(text_event_result))
                    },
                    None => Event::Text(text)
                }
            },
            // any other event
            _ => event
        });

        html::push_html(&mut result, parser);
        result
    }

Hope this will be useful for anyone and maybe if someone can find a way to not duplicate so much code, they can post it and people can learn from the example.

**Comment by marcusklaas** [comment]
I think you have the right idea. Doing this with iterator API seems like a good approach. As a tip, you can probably just match on any header level like below, which removes a lot of duplication.
```rust
parser.map(|event| match event {
        Event::Start(Tag::Header(level @ 1..=6)) => {
            heading_counts[level - 1] += 1;
            in_headings_status[level - 1] = true;
            for i in level..6 {
                heading_counts[i] = 0;
            }
            Event::Start(Tag::Header(level))
        },
        Event::End(Tag::Header(level @ 1..=6)) => {
            in_headings_status[level - 1] = false;
            Event::End(Tag::Header(level))
        },
        ...
```
Closing this as this is outside of the scope of the crate and it can be implemented with the iterator API.
