### ISSUE TITLE
Syntect integration

### ISSUE THREAD

**Issue by est31** [raphlinus/pulldown-cmark#107]
It would be great for code blocks inside the html output to be optionally formatted using syntect. E.g. you could have integration via an option and an optional feature.

Alternatively, one could also do a pass on the html code created by pulldown-cmark, e.g. inside something like [ammonia](https://github.com/notriddle/ammonia), but I'd prefer if it were integrated directly into pulldown-cmark.

cc @trishume

**Comment by trishume** [comment]
Both https://github.com/Keats/gutenberg and https://github.com/cobalt-org/cobalt.rs have code to do this that might be useful. But, syntect is a relatively big dependency and not everyone will want it, so I'd say if this is made into a thing, it should be a cargo feature or a separate crate that does a mapping on the pulldown-cmark events.

**Comment by joshleeb** [comment]
Looks like this issue relates to #167

**Comment by est31** [comment]
Since I filed the bug, I found out a way to integrate syntect, by building a custom iterator for events, [like this](https://github.com/est31/cargo-local-serve/blob/master/cargo-local-serve/markdown_render.rs) ([this](https://github.com/est31/cargo-local-serve/commit/5150f5d33350abccc0a12d72103ee5f5dd168a55) being the commit that introduced it). IDK the API could be a bit nicer, but maybe there's some iterator magic that I've missed.

**Comment by marcusklaas** [comment]
That looks like the way to do it. Just a few notes:
- that strategy may not work with the newest version of pulldown_cmark, if you ever choose to upgrade. There, some synthesized text may be inserted as well. You'd need to match on those as well.
- you allocate a temporary buffer always, but this may not be necessary when all the text elements inside the codeblock are perfectly contiguous. Your solution is much more elegant tho, so unless performance is critically important, I wouldn't worry about it.

**Comment by est31** [comment]
Thanks for the reminder, I've [updated pulldown_cmark to the latest version](https://github.com/est31/cargo-local-serve/commit/3a74e1a7a7c51e068a4e4793f297dd27d6a88d6f)!

As for the synthesized text that can be inserted, I'm handling that in the loop. Synthesized text gets translated to normal text events.

**Comment by marcusklaas** [comment]
Sweet! As there seem to be some good solutions to this out-of-crate and there is no immediate benefit to adding it to pulldown_cmark, I'm closing this for now.
