### ISSUE TITLE
Blank line in multi-line HTML comment confuses pulldown

### ISSUE THREAD

**Issue by ehuss** [raphlinus/pulldown-cmark#124]
If there is a blank line inside a multi-line HTML comment, pulldown seems to think that the comment has ended and starts interpreting the rest as-if it is Markdown.

Example:
```
<!--

**foo**
-->
```

Renders as:
```
<!--
<p><strong>foo</strong>
--&gt;</p>
```

Since the comment end is escaped, the rest of the document will not display.

I would expect it to render as:

```
<!--

**foo**
-->
```

**Comment by crlf0710** [comment]
It seems "Example 146" in commonmark spec is exactly the case?
http://spec.commonmark.org/0.28/#example-146

**Comment by marcusklaas** [comment]
This seems fixed now. I'll add a regression test and close after.

**Comment by marcusklaas** [comment]
Closing as this looks to be covered by the spec as mentioned by @crlf0710.
