### ISSUE TITLE
Guarantee that options will only ever enable features?

### ISSUE THREAD

**Issue by quadrupleslap** [raphlinus/pulldown-cmark#125]
I want to enable all features, but I'm afraid that using `Options::all()` might result in some `DISABLE_*` flags being used or something in the distant future. Could you please add a guarantee that `Options::all()` will only enable features, or add `Options::enable_all()`?

**Comment by marcusklaas** [comment]
This may a bit philosophical, but options just *change* behavior. Setting the tables option *enables* HTML tables for example, but it *disables* ASCII tables. I'm not trying to be pedantic here. It can generally get unclear whether you're enabling stuff. Take [GFM's raw HTML extension](https://github.github.com/gfm/#disallowed-raw-html-extension-) for instance. Would this be an enabling or disabling option? You tell me.

From this perspective, I am afraid we can really make no promises. Candidates for future options that I can currently see are the remaining GFM features: raw HTML and autolinks, and perhaps some math functionality.

I hope that helps!

**Comment by quadrupleslap** [comment]
Thanks, that's fine. This issue doesn't make much sense to me now either.
