### ISSUE TITLE
Single-column tables not supported

### ISSUE THREAD

**Issue by Fierthraix** [raphlinus/pulldown-cmark#129]
Currently tables that only have one column aren't recognized as such.

For example typing
```markdown
| foo |
| --- |
| bar |
```
produces 

<p>| foo | | - | | bar |</p>

Adding a second column instantly makes it a table

```markdown
| a | v |
| - | - |
| b | c |
```

<table><thead><tr><td> a </td><td> v </td></tr></thead><tr><td> b </td><td> c</td></tr></table>

**Comment by marcusklaas** [comment]
This is fixed on current master. I will add a regression test and then close.

**Comment by marcusklaas** [comment]
GFM apparently has a [test](https://github.github.com/gfm/#example-193) for this case, and we pass it now! :-)
