### ISSUE TITLE
Add support for extending/overwriting handlers for tags

### ISSUE THREAD

**Issue by lambdadog** [raphlinus/pulldown-cmark#130]
I'm currently writing something that calls for syntax highlighting within markdown code blocks and I've been looking around and it doesn't seem there's any real inbuilt extensibility in pulldown-cmark like I'd hoped.

Correct me if I'm wrong, since I'm new to rust, but the only real ways to do this are to

1. Fork the project and edit the lines I need to (sort of overkill),
2. Parse the html after the conversion has finished and replace it (cludgy and inefficient),
2. Completely reimplement the portion of the code that handles converting to html (duplicating a large block of code really shouldn't be necessary), or
3. Create a "proxy" parser that contains the actual parser inside of it and takes over when a code block starts, then pushes it all through as InlineHtml when the code block closes (probably what I'll actually do, but definitely jumping through hoops to accomplish a fairly simple change)

I know this isn't necessarily the focus of the project, but it would definitely be helpful to devs using pulldown-cmark to be able to extend/modify the html conversions a little bit without jumping through hoops.

**Comment by raphlinus** [comment]
The current HTML renderer is designed to be simple. I'm worried that extensibility would make a significantly more complicated API surface. That said, I'm not completely averse to such a thing, and will take another look after the new_algo branch lands.

**Comment by Figments** [comment]
I'd love to see this too. Been wanting to add support for Discord-like tags for underlining and spoiler text in my project.

**Comment by Weasy666** [comment]
@transitracer I have the same use case and am facing the same problem. Have you found a solution?

**Comment by Martin1887** [comment]
This seems to be the implementation of HTML rendering in a different crate, like #637, #408 and #525.
