### ISSUE TITLE
Consecutive footnote links confuse pulldown-cmark

### ISSUE THREAD

**Issue by Michael-F-Bryan** [raphlinus/pulldown-cmark#133]
I've got the following example:

```md
see the [many] [articles] [on] [QuickCheck].

[many]: https://medium.com/@jlouis666/quickcheck-advice-c357efb4e7e6
[articles]: http://www.quviq.com/products/erlang-quickcheck/
[on]: https://wiki.haskell.org/Introduction_to_QuickCheck1
[QuickCheck]: https://hackage.haskell.org/package/QuickCheck
```

When rendering with `mdbook` (which uses `pulldown-cmark` internally) you get the following:

```html
<p>
  see the 
  <a href="http://www.quviq.com/products/erlang-quickcheck/">many</a> 
  <a href="https://hackage.haskell.org/package/QuickCheck">on</a>).
</p>
```

Whereas CommonMark's [dingus] renders it as:

```html
<p>see the 
  <a href="https://medium.com/@jlouis666/quickcheck-advice-c357efb4e7e6">many</a> 
  <a href="http://www.quviq.com/products/erlang-quickcheck/">articles</a> 
  <a href="https://wiki.haskell.org/Introduction_to_QuickCheck1">on</a> 
  <a href="https://hackage.haskell.org/package/QuickCheck">QuickCheck</a>.
</p>
```

It seems like placing a space between footnote links (e.g. `[many]`) *should* be interpreted as separate links by the common-mark spec, but they get ignored by `pulldown-cmark`.

[dingus]: http://spec.commonmark.org/dingus/?text=see%20the%20%5Bmany%5D%20%5Barticles%5D%20%5Bon%5D%20%5BQuickCheck%5D.%0A%0A%5Bmany%5D%3A%20https%3A%2F%2Fmedium.com%2F%40jlouis666%2Fquickcheck-advice-c357efb4e7e6%0A%5Barticles%5D%3A%20http%3A%2F%2Fwww.quviq.com%2Fproducts%2Ferlang-quickcheck%2F%0A%5Bon%5D%3A%20https%3A%2F%2Fwiki.haskell.org%2FIntroduction_to_QuickCheck1%0A%5BQuickCheck%5D%3A%20https%3A%2F%2Fhackage.haskell.org%2Fpackage%2FQuickCheck

**Comment by marcusklaas** [comment]
This seems fixed, judging from the output:
```html
<p>see the <a href="https://medium.com/@jlouis666/quickcheck-advice-c357efb4e7e6">many</a> <a href="http://www.quviq.com/products/erlang-quickcheck/">articles</a> <a href="https://wiki.haskell.org/Introduction_to_QuickCheck1">on</a> <a href="https://hackage.haskell.org/package/QuickCheck">QuickCheck</a>.</p>
```
I'll add a regression test.
