### ISSUE TITLE
Ordered lists detection difference

### ISSUE THREAD

**Issue by jethrogb** [raphlinus/pulldown-cmark#134]
Input:
```text
1. this is the first step
2. some instructions are here.
   in some case, you need to go back to step
   1.
3. the last step
```

[commonmark.js output](http://spec.commonmark.org/dingus/?text=1.%20this%20is%20the%20first%20step%0A2.%20some%20instructions%20are%20here.%0A%20%20%20in%20some%20case%2C%20you%20need%20to%20go%20back%20to%20step%0A%20%20%201.%0A3.%20the%20last%20step%0A):
```html
<ol>
<li>this is the first step</li>
<li>some instructions are here.
in some case, you need to go back to step
1.</li>
<li>the last step</li>
</ol>
```

Pulldown output:
```html
<ol>
<li>this is the first step</li>
<li>some instructions are here.
in some case, you need to go back to step
<ol>
<li></li>
</ol>
</li>
<li>the last step</li>
</ol>
```

I'm not sure who is correct. If you think pulldown is correct I'm happy to re-file at commonmark.js instead.

**Comment by jethrogb** [comment]
Another related one. I'm fairly certain this is wrong in pulldown and correct in commonmark.js:

```text
This returns the number of nanoseconds since midnight UTC on January 1,
1970. 
```

[commonmark.js](http://spec.commonmark.org/dingus/?text=This%20returns%20the%20number%20of%20nanoseconds%20since%20midnight%20UTC%20on%20January%201%2C%0A1970.):
```html
<p>This returns the number of nanoseconds since midnight UTC on January 1,
1970.</p>
```

Pulldown:
```html
<p>This returns the number of nanoseconds since midnight UTC on January 1,</p>
<ol start="1970">
<li></li>
</ol>
```

**Comment by raphlinus** [comment]
This was addressed somewhat in version 0.25 of the spec, so at least the second example won't interrupt (it only interrupts if the index is 1). However, I think spec clarification is still needed, as just `1.` on a line won't interrupt, but if it's followed by additional text it will.

I'll fix this in the new_algo branch; I just did bullet lists and will probably get to ordered lists soon.

**Comment by marcusklaas** [comment]
I think the first example may be spec compliant. The spec only prevents starting new lists within paragraphs, so even changing the example to
```md
1. this is the first step
2. some instructions are here.
   in some case, you need to go back to step
   2.
3. the last step
```
may produce a sublist. Clarification would be great here indeed.

We are consistent with commonmark.js on the second example.

**Comment by marcusklaas** [comment]
Closing this as pulldown-cmark seems to be compliant with the spec now.
