### ISSUE TITLE
Question: source maps supported or not?

### ISSUE THREAD

**Issue by akavel** [raphlinus/pulldown-cmark#140]
The readme says:

> - Versatile; in particular source-maps are supported

Is this actually supported as of current version, or not? If yes, how? Is it via the `get_offset` method of Parser? If yes, do I understand correctly that this doesn't let me for example detect what are the offsets of various parts of a link definition, thus in: `[some random link](https://github.com)` I can only get the offset where the whole thing starts and where it ends? Also cannot e.g. easily differentiate it from `[ref link][some-ref]`?

I'm searching for a Rust library which could let me write an editor with syntax highlighting and/or hiding of markdown syntax, so I need to be able to precisely position all such minute details...

**Comment by raphlinus** [comment]
It's through `get_offset`, yes. I agree that's only fine-grained down to the level of individual AST nodes, not finer. I'd consider an extension that would report more detail. Also, I'd be happy for a PR that would clarify the language if it's confusing.

**Comment by marcusklaas** [comment]
A new offset iterator with a range for each event has been implemented!
