### ISSUE TITLE
Deviation from CommonMark w.r.t. backslashes in links

### ISSUE THREAD

**Issue by ibookstein** [raphlinus/pulldown-cmark#143]
```
Z:\Projects\rust-lang\pulldown-cmark-backslash>echo [foo](img\bar.jpg)
[foo](img\bar.jpg)

Z:\Projects\rust-lang\pulldown-cmark-backslash>echo [foo](img\bar.jpg)| pulldown-cmark
<p><a href="imgbar.jpg">foo</a></p>

```
Versus https://spec.commonmark.org/dingus/?text=%5Bfoo%5D(img%5Cbar.jpg):
```
<p><a href="img%5Cbar.jpg">foo</a></p>
```

I later looked a bit deeper into the preexisting issues (used a narrow search before) and noticed this may be a duplicate of https://github.com/google/pulldown-cmark/issues/114

**Comment by marcusklaas** [comment]
This is fixed now!
