### ISSUE TITLE
[docs] minimal example

### ISSUE THREAD

**Issue by yoshuawuyts** [raphlinus/pulldown-cmark#15]
Hi, I was wondering if someone could include a minimal example?

The example in the readme might make sense if you know which classes to import and are comfortable with Rust's import syntax, but for newcomers it can be a little rough. Having a more complete example would be of great help. Thanks!

**Comment by Anonyfox** [comment]
+1 on this.

**Comment by 0X1A** [comment]
@raphlinus Is there any chance of this project getting documented a bit more?

**Comment by matthiasbeyer** [comment]
@raphlinus I :+1: what @0X1A said - there is almost no documentation here (looking at [docs.rs](https://docs.rs/pulldown-cmark/0.0.8/pulldown_cmark/struct.Parser.html) at the moment, for example).

**Comment by droundy** [comment]
Agreed.  I found a nice example under `html::push_html` [see](https://docs.rs/pulldown-cmark/0.2.0/pulldown_cmark/html/fn.push_html.html), but it was not at all obvious that this would be a good place to look for the basic example of "how do I turn markdown into html" which is surely what most users of this library want.

**Comment by marcusklaas** [comment]
Two examples have been added to the examples directory, in addition to some example code in the crate root.
