### ISSUE TITLE
Iterator with offset

### ISSUE THREAD

**Issue by crawford** [raphlinus/pulldown-cmark#160]
I'd prefer if I didn't have to call get_offset() in order to read the location of the parser (I have to dump out the location of errors in my application). If the iterator was a tuple of Event and position, I wouldn't need to "manually" iterate over the parser.

Currently, I'm doing something like this:

```rust
while let Some(event) = parser.next() {
    let offset = parser.get_offset();
    ...
}
```

It would be great if I could do something like this instead:

```rust
for (event, offset) in parser.iter_with_offset() {
    ...
}
```

**Comment by raphlinus** [comment]
This'll probably be in the batch of features that lands with new_algo. Here's a question for you though: I'm tracking both start and end offsets, not just start as before. Would it be useful to have both while I'm making the API? I don't believe the cost would be significant.

**Comment by crawford** [comment]
Definitely. That would be helpful for syntax highlighting. Currently, I use the start position to calculate the line number, which is unhelpful for minified YAML (one line). Having a range would let me handle all cases elegantly.
