### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by David-OConnor** [raphlinus/pulldown-cmark#167]
Would it be possible to add syntax highlighting (perhaps just for Rust code) to the Parser? in code blocks, and/or highlight the background color of code blocks, eg how Github displays readmes?

It might be possible to integrate an existing crate, like https://github.com/trishume/syntect

I'm suspicious it can be done by running the text inside code tags through ```syntect::html::highlighted_html_for_string``` ; maybe 
somewhere near https://github.com/raphlinus/pulldown-cmark/blob/master/src/html.rs#L122

**Comment by raphlinus** [comment]
I think you've raised a good point, but my sense is that the pulldown-cmark crate should remain focused. I believe there are some other integrations that include syntect. It might be worthwhile to survey them and see whether the markdown + syntax highlighting functionality can be factored out into a common wrapper crate.

I don't have a lot of bandwidth right now to investigate this, but somebody else might be motivated to.

**Comment by David-OConnor** [comment]
I could do it if you point out where to insert that syntect func.

**Comment by ScottAbbey** [comment]
This doesn't quite seem like it would belong as a direct part of the pulldown-cmark project, since there could be any number of other syntax highlighting utilities people would like to use.

It seems like just another instance of the type of example shown in `README.md` under "Why a pull parser?", right?

After parsing but before sending it to the HTML renderer, you should be able to iterate over the parser's result, applying your syntax highlighting tool to any Event::Text(...) that comes after an Event::Start(Tag::CodeBlock).

For example, from `render_html()` in `main.rs`, you'd probably do this between `let p = Parser::new_ext(text, opts);` and `html::push_html(&mut s, p);`.

Am I on the right track here?

**Comment by Keats** [comment]
Pretty much all that is required to highlight code with syntect is: https://github.com/getzola/zola/blob/master/components/rendering/src/markdown.rs#L112-L133

**Comment by ScottAbbey** [comment]
@Keats: That will work when you want to handle all aspects of HTML generation yourself, but I think might be overkill compared to what @David-OConnor is looking for.  @David-OConnor is just looking for an example of how to use syntax highlighting alongside `pulldown_cmark`'s existing HTML generation.

In this case, all we need to do is modify the event stream before passing it to `push_html`.  We don't need to do anything special with the actual steps of generating the rest of the HTML outside of code blocks.

I took a peek at the `syntect` crate and here's a rough example of how you would do that.  It is missing numerous things needed for completeness's sake, such as intelligently selecting the language based on the supplied tag or kind of error handling or verification at all.

Most of the setup code is taken directly from either the `pulldown_cmark` main or the example files in the `syntect` project -- I don't really have any idea how to use the syntect highlighter beyond the bare minimum to show an example.  I also don't really have the slightest clue how to write idiomatic Rust, so use this at your own risk.

<details>
<summary>Lots of imports</summary>

```rust
extern crate pulldown_cmark;
extern crate syntect;

use syntect::highlighting::ThemeSet;
use syntect::html::highlighted_html_for_string;
use syntect::parsing::SyntaxSet;

use pulldown_cmark::html;
use pulldown_cmark::Event;
use pulldown_cmark::Options;
use pulldown_cmark::Parser;
use pulldown_cmark::Tag;

use std::borrow::Cow;
use std::io;
use std::io::Read;
```
</details>

<details>
<summary>Boilerplate/setup</summary>

```rust
fn main() {
    // Setup for pulldown_cmark to read (only) from stdin
    let opts = Options::empty();
    let mut input = String::new();
    io::stdin().read_to_string(&mut input).unwrap();
    let mut s = String::with_capacity(&input.len() * 3 / 2);
    let p = Parser::new_ext(&input, opts);

    // Setup for syntect to highlight (specifically) Rust code
    let ss = SyntaxSet::load_defaults_newlines();
    let ts = ThemeSet::load_defaults();
    let syntax = ss.find_syntax_by_extension("rs").unwrap();
    let theme = &ts.themes["base16-ocean.dark"];
```

</details>

<details>
<summary>Interesting part</summary>

```rust
    // We'll build a new vector of events since we can only consume the parser once
    let mut new_p = Vec::new();
    // As we go along, we'll want to highlight code in bundles, not lines
    let mut to_highlight = String::new();
    // And track a little bit of state
    let mut in_code_block = false;

    for event in p {
        match event {
            Event::Start(Tag::CodeBlock(_)) => {
                // In actual use you'd probably want to keep track of what language this code is
                in_code_block = true;
            }
            Event::End(Tag::CodeBlock(_)) => {
                if in_code_block {
                    // Format the whole multi-line code block as HTML all at once
                    let html = highlighted_html_for_string(&to_highlight, &ss, &syntax, &theme);
                    // And put it into the vector
                    new_p.push(Event::Html(Cow::Owned(html)));
                    to_highlight = String::new();
                    in_code_block = false;
                }
            }
            Event::Text(t) => {
                if in_code_block {
                    // If we're in a code block, build up the string of text
                    to_highlight.push_str(&t);
                } else {
                    new_p.push(Event::Text(t))
                }
            }
            e => {
                new_p.push(e);
            }
        }
    }

    // Now we send this new vector of events off to be transformed into HTML
    html::push_html(&mut s, new_p.into_iter());
    print!("{}", s);
}
```

</details>

Hopefully this is enough to get @David-OConnor on the right path for success.

Example input:
````
Test

```rust
fn main() {
    let mut input = String::new();
}
```

Test
````

Example output:
```html
<p>Test</p>
<pre style="background-color:#2b303b;">
<span style="color:#b48ead;">fn </span><span style="color:#8fa1b3;">main</span><span style="color:#c0c5ce;">() {
</span><span style="color:#c0c5ce;">    </span><span style="color:#b48ead;">let mut</span><span style="color:#c0c5ce;"> input = String::new();
</span><span style="color:#c0c5ce;">}
</span></pre>
<p>Test</p>
```

**Comment by est31** [comment]
You can also check out my iterator based version [here](https://github.com/est31/cargo-local-serve/blob/master/cargo-local-serve/markdown_render.rs).

**Comment by marcusklaas** [comment]
As there seem to be some good solutions to this out-of-crate, I'm closing this for now.

**Comment by eguiraud** [comment]
Hello, in case it can be useful to someone else, I built a mini-crate based on the example by @ScottAbbey . It adds language detection and error handling. It's https://crates.io/crates/highlight-pulldown , feedback welcome.

**Comment by mrshmllow** [comment]
If anyones looking at this these days, you can achieve it like this:

```rs
pub(crate) struct CodeblockRenderer<'a> {
    inner: Parser<'a>
}

impl<'a> From<Parser<'a>> for CodeblockRenderer<'a> {
    fn from(inner: Parser<'a>) -> Self {
        Self {
            inner
        }
    }
}

impl<'a> Iterator for CodeblockRenderer<'a> {
    type Item = pulldown_cmark::Event<'a>;

    fn next(&mut self) -> Option<Self::Item> {
        let event = self.inner.next();

        let Some(Event::Start(Tag::CodeBlock(kind))) = event else {
            return event;
        };

        let mut code_content = String::new();

        for inner_event in &mut self.inner {
            match inner_event {
                Event::End(TagEnd::CodeBlock) => break,
                Event::Text(code) => code_content.push_str(&code),
                _ => {}
            }
        }

        let lang = match kind {
            CodeBlockKind::Indented => "text".to_string(),
            CodeBlockKind::Fenced(language) => language.to_string()
        };

        let rendered_codeblock = render_some_html(&code_content, &lang);

        Some(Event::Html(CowStr::Boxed(rendered_codeblock.into())))
    }
}
```
