### ISSUE TITLE
Markdown to markdown transformation

### ISSUE THREAD

**Issue by felipetavares** [raphlinus/pulldown-cmark#182]
It seems it's only possible to render to html at the moment.

It would be useful to save intermediate processing in markdown format in such a way that
this could later be used by different rendering tools.

Is there a clear path to implement this? Any pointers?

**Comment by raphlinus** [comment]
It produces an event stream, which can be saved or otherwise processed. This event stream is similar to the AST produced by cmark, but is an iterator rather than an allocated-in-memory tree. I think anything more than that is beyond the scope of this crate. Maybe I just don't understand what you're asking for.

**Comment by felipetavares** [comment]
> It produces an event stream, which can be saved or otherwise processed. This event stream is similar to the AST produced by cmark, but is an iterator rather than an allocated-in-memory tree.

I understand how it currently works (I think).

What I am looking for is a way to use the library to parse markdown and output markdown, as that would be useful for "markdown tools" that work enriching or transforming markdown files.

> I think anything more than that is beyond the scope of this crate

Maybe so, this is more of a "is there a easier way?" type of question: do I need to implement another renderer for the event stream from ground up or could I reuse something existing?

**Comment by raphlinus** [comment]
Ah, you're talking about markdown-to-markdown transformation. That's possibly interesting.

**Comment by marcusklaas** [comment]
There's [this project](https://github.com/Byron/pulldown-cmark-to-cmark) which seems to do what you are looking for. It does still rely on version 0.2 of pulldown-cmark, so it won't be compliant with the latest version of CommonMark. It shouldn't be too hard to update it to use the most recent version though.

Closing this for now as this seems to be solvable out-of-crate. Happy to reopen on new insights.
