### ISSUE TITLE
What table extension spec to choose?

### ISSUE THREAD

**Issue by marcusklaas** [raphlinus/pulldown-cmark#188]
The [markdown-extra](https://michelf.ca/projects/php-markdown/extra/#table) and [GFM](https://github.github.com/gfm/#tables-extension-) markdown table extensions don't agree on whether to use `<th>` or `<td>` for cells in table headers. It seems we must make a choice.

Any requirements/ preference on your side, @GuillaumeGomez ?

Possibly relevant: https://github.com/raphlinus/pulldown-cmark/pull/8

**Comment by GuillaumeGomez** [comment]
I have a preference for `<th>` for header's cells. The rustdoc CSS uses it as well so that might be better for me. :3

**Comment by marcusklaas** [comment]
GFM it is. We should render most commonmark-extra tables ok as well. The difference between the spec besides the `th`s in the header is that we fill table rows with empty cells, whereas commonmark-extra does not expect this.
