### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by GuillaumeGomez** [raphlinus/pulldown-cmark#205]
Can you make a new release please? :) (needed for rustdoc)

**Comment by marcusklaas** [comment]
We working on it! But @raphlinus astutely noted that rustdoc needs broken_link_callback functionality, which isn't yet part of master yet..

**Comment by GuillaumeGomez** [comment]
Awesome, thanks for the explanations! :)

**Comment by marcusklaas** [comment]
[Done!](https://crates.io/crates/pulldown-cmark/0.3.0)

There'll be an announcement post shortly as well.

**Comment by GuillaumeGomez** [comment]
Thanks!
