### ISSUE TITLE
crdt.md License Question

### ISSUE THREAD

**Issue by ScottAbbey** [raphlinus/pulldown-cmark#209]
Where did you get this file from? I think if you got it from https://github.com/xi-editor/xi-editor/, then we probably need to make some acknowledgement of that fact due to the Apache 2.0 license that repository seems to be released under.

Maybe file it under third_party/xi-editor similar to what is already there at third_party/CommonMark?

_Originally posted by @ScottAbbey in https://github.com/raphlinus/pulldown-cmark/pull/187_

**Comment by raphlinus** [comment]
Ah, good point. It is indeed from xi-editor, so to be extremely careful about license attribution it should be in third_party as you say.

It is only used for benchmarking, and it is a document rather than code, so the risk is low, but even so I'm in favor of cleaning up this kind of thing.
