### ISSUE TITLE
Warn on broken reference links

### ISSUE THREAD

**Issue by ehuss** [raphlinus/pulldown-cmark#217]
Too often, I end up with reference links that are no longer used.
```text
blah blah blah

[somelink]: https://example.com
```
It would be useful to get some kind of event to inform that `somelink` did not match anything.

This is the converse of the old `broken_link_callback`, which triggered when a link was found without a corresponding reference definition.

I'm not sure what the plan is for restoring broken link support.

**Comment by marcusklaas** [comment]
This seems like a useful request. I think it is a special case of issue #434 since that will enable users to track which reference definitions are used now that the definitions are exposed (#512).

We plan to address that issue, so I will close this and include this use case there.
