### ISSUE TITLE
Bad markdown intepretation

### ISSUE THREAD

**Issue by GuillaumeGomez** [raphlinus/pulldown-cmark#239]
The following markdown:

```
[`
i8
`](
../../../std/primitive.i8.html
)
```

is currently badly interpreted. It should ignore backlines and trim content. Currently it generates a result pretty strange:

```html
<a href="https://doc.rust-lang.org/nightly/std/primitive.i8.html" title="` i8 `"><code>i8</code></a>(
../../../std/primitive.i8.html
)
```

**Comment by marcusklaas** [comment]
That does look pretty funky :thinking: 

Thanks for the report. I'll look into it!
