### ISSUE TITLE
Usage for command line tool 

### ISSUE THREAD

**Issue by lazypassion** [raphlinus/pulldown-cmark#241]
Does the command line tool take in a markdown file and output an html file? If it does how do I do that because I've been having this issue: 

On both windows 10 and ubuntu 18.10 I've tried cloning the library and building and running the binary. I provide a markdown file but nothing happens and it never finishes executing. 

When I add the `-h` flag after `pulldown-cmark.exe` the help message is displayed so that works. 

I also tried `cargo install pulldown-cmark` but I run into the same issue where the program never does anything and never finishes executing. 

I'm wondering if there's something I'm misunderstanding about it's usage.

**Comment by marcusklaas** [comment]
I believe it treats the standard input as markdown and it doesn't expect a file path. Not sure how this works on Window's shell, but on UNIX-like systems you can either pipe some input to pulldown-cmark like so
```sh
echo "Hello *world*!" | pulldown-cmark
```
or read from file explicitly
```sh
pulldown-cmark <test.md >out.html
```
I hope this helps!

**Comment by ScottAbbey** [comment]
> I believe it treats the standard input as markdown and it doesn't expect a file path.

The help text states otherwise:

```
$ pulldown-cmark -h
Usage: pulldown-cmark FILE [options]
```

Also reported here 8 days ago: https://github.com/raphlinus/pulldown-cmark/pull/36#commitcomment-32812766

**Comment by lazypassion** [comment]
Reading from the file explicitly worked, however just like @ScottAbbey said that isn't the usage specified by the help message.

**Comment by marcusklaas** [comment]
This was fixed by https://github.com/raphlinus/pulldown-cmark/pull/291!
