### ISSUE TITLE
byte index 19 is not a char boundary; it is inside '»' 

### ISSUE THREAD

**Issue by Geobert** [raphlinus/pulldown-cmark#261]
Using 0.4
When writing:
```
[« Blurry Eyes »][blurry_eyes] est assez représentatif de
ce peut faire le bassiste (cliquez sur [le lien][blurry_eyes], elle n’est pas intégrable).
```

I got this error:
```
thread 'main' panicked at 'byte index 19 is not a char boundary; it is inside '»' (bytes 18..20) of `[« Blurry Eyes »][blurry_eyes] est assez représentatif de
ce peut faire le bassiste (cliquez sur [le lien][blurry_eyes], elle n’est pas intégrable).

« Pieces », Une jolie balade :

<div class="embed-video"><iframe src="https://www.youtube.com`[...]', src\libcore\str\mod.rs:2102:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

After some try, it seems that using ` »` inside a `[]` is causing the error.
Note that the space before `»` is a non-breakable space.
I've tried: 
* `space»][link_ref]` -> working
* `][link_ref]nbsp»` -> working
* `nbsp"][link_ref]` -> working
* `nbsp»][link_ref]` -> broken

**Comment by marcusklaas** [comment]
Thank you for filing this detailed report!

I will look into this bug immediately.

**Comment by marcusklaas** [comment]
The bug appeared to be multi-byte spaces inside link labels. We normalize all spaces to regular spaces, but made some error in calculating the right index (and would end up in the middle of another multi-byte character). If it wasn't for `»`, we wouldn't crash but fail to recognize the link.

There's [a fix](https://github.com/raphlinus/pulldown-cmark/pull/262) for this, but review capacity seems to be very limited at the moment. I hope we can get it merged soon.

Thanks again for your report :-) These things really help make the project more robust.

**Comment by Geobert** [comment]
Thank you for your analysis!

> We normalize all spaces to regular spaces

Only for internal use I presume? The nbsp is still output?

**Comment by marcusklaas** [comment]
Correct!
