### ISSUE TITLE
`pulldown-cmark FILE` sits idle

### ISSUE THREAD

**Issue by polyzen** [raphlinus/pulldown-cmark#264]
https://github.com/raphlinus/pulldown-cmark/commit/d7b536963f6dfe9e571603eb3be44376d00a4e5d#r32812766

> In my experience, I've only been able to render from standard input (eg. pulldown-cmark < README.md > README.html).

**Comment by marcusklaas** [comment]
Yup, this is a documentation bug. We should fix this soon.
