### ISSUE TITLE
Get source range of unescaped language of fenced code blocks

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#271]
With an `OffsetIter` the event `(Event::Start(Tag::CodeBlock(CowStr)), Range<usize>)` contains the unescaped *info_string* (according to GFM, left open in CommonMark) of a fenced code block and the range of the whole code block. Is there a way to get the source range of the escaped, original *info_string* as well, e.g. for error reporting in a renderer?

**Comment by marcusklaas** [comment]
There's no way to do this in the current setup as we can only pass one range per tag. If I understand your intention correctly, you could take this range and parse the source yourself. It's not ideal, but it shouldn't be hard for code blocks.

**Comment by oberien** [comment]
That's what I suspected. For code blocks it should be simple enough to do. If you want you can close this issue, or leave it open if it might be a good candidate for a future improvement.

**Comment by marcusklaas** [comment]
I'll close this for now, as it's not clear how we can provide this information without complicating the public API and there's a reasonable out-of-crate solution.
