### ISSUE TITLE
Produce empty text event if a text starts with an escape sequence

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#273]
In [*heradoc*](https://github.com/oberien/heradoc) I'm performing some text processing. For that I concatenate all consecutive text events to be able to apply heuristics to a whole line. In order to handle escape sequences correctly, I'm transforming the escaped source-range to an intermediate unescaped range, perform manipulation on the string, and then convert the resulting unescaped range(s) back to escaped source-code ones.

When pulldown-cmark encounters an escape sequence, it splits the `Event::Text` into one up to the escape character and one after the escaping backslash: `(r"Foo\*Bar", 0..8) → (r"Foo", 0..3), (r"*Bar", 4..8)`. I use this behaviour for performing the mappings. However, I realized that if a text starts with an escape character, the text event starts directly with the next character: `(r"\*Foo\*Bar", 0..10) → (r"*Foo", 1..5), (r"*Bar", 6..10)`.  
In that case, there is no easy way for me to tell if the text event in the source code actually started at `1` or if there is an escape sequence beforehand.

Would it be possible that if a text string starts with an escape sequence, an empty text event is produced before the first unescaped text event? That event indicates that the text actually starts earlier, but there isn't any content before performing the first unescape: `(r"\*Foo\*Bar", 0..10) → (r"", 0..0), (r"*Foo", 1..5), (r"*Bar", 6..10)`.

If that's not possible or out of scope, I'll need to perform manual backtracking in the original source code starting from the first character of a text sequence to find out if there is an escape sequence beforehand which got eliminated.

**Comment by marcusklaas** [comment]
I think this may be out of scope. Emitting empty text events would likely be confusing for most users and not optimal from a performance perspective. Doing the backtracking may be the best solution for your specialized use case.

**Comment by oberien** [comment]
I'll take another look at the provided offsets at some point in the future and might get back at that point. Until then, I'll close this.
