### ISSUE TITLE
add checkboxes

### ISSUE THREAD

**Issue by bestouff** [raphlinus/pulldown-cmark#28]
Hi,
- [x] Would it be possible to add Tasks Lists please ?

**Comment by DarkoDamjanovic** [comment]
Seems like task list/todo items/checkboxes are not part of the CommonMark spec:
https://spec.commonmark.org

**Comment by notriddle** [comment]
Neither are tables or footers. We can add them as an extension.

**Comment by DarkoDamjanovic** [comment]
Thanks, that would be great.

**Comment by bestouff** [comment]
Nice, thanks a lot !
