### ISSUE TITLE
Non-linear behaviour when parsing `a<?a<?a<?...`

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#282]

**Comment by marcusklaas** [comment]
I believe this is fixed by https://github.com/raphlinus/pulldown-cmark/pull/281.

**Comment by oberien** [comment]
Oh, just realized that you already said this in https://github.com/raphlinus/pulldown-cmark/issues/280#issuecomment-487665793 . I tested against the marcusklaas/remove-inline-scanner branch and it indeed doesn't seem to produce non-linear behaviour anymore. You can add `Fix #282` to the toplevel comment on the #281 PR to have this issue auto-closed once it's merged.

**Comment by marcusklaas** [comment]
Fixed now on 0.5.1 and master!
