### ISSUE TITLE
Non-linear behaviour when parsing `[[]()...`

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#284]

**Comment by marcusklaas** [comment]
Erm, have you tried this on https://github.com/raphlinus/pulldown-cmark/pull/281? I think this was fixed as well :sweat_smile:

**Comment by oberien** [comment]
I am in fact running my fuzzer (actually it is a fuzzer by definition) on that branch.

**Comment by marcusklaas** [comment]
Excellent, good find then! Thanks :-)
