### ISSUE TITLE
"\r\n" not treated the same way as "\n"

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#285]
For example, link reference definition is not recognized if its line ends with "\r\n".

```
$ printf "[a]: /u\r\n" | ./target/debug/pulldown-cmark
<p>[a]: /u</p>
```

**Comment by marcusklaas** [comment]
Thanks for reporting this!

**Comment by mity** [comment]
the test case now writes this to stderr:
```
[src/scanners.rs:777] bytes[i] = 13
```

@marcusklaas Maybe some helper debugging message you forgot to remove?

**Comment by marcusklaas** [comment]
Yes! Good thing you caught this so quickly. We were just about to publish a new release :sweat_drops:
