### ISSUE TITLE
Inconsistent whitespace trimming in table cells

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#292]
Leading whitespace in table cells is removed, trailing one is not.

```
$ printf 'A | B\n---|---\nfoo | bar' | ./pulldown-cmark -T
<table><thead><tr><th>A </th><th>B</th></tr></thead><tbody>
<tr><td>foo </td><td>bar</td></tr>
</tbody></table>
```

**Comment by marcusklaas** [comment]
These are great — thanks for filing them. Are you discovering these through some automated process?

**Comment by mity** [comment]
No. I just remembered some problematic cases from MD4C development, so just tried them.

**Comment by oberien** [comment]
Maybe those problematic cases should become examples of the GFM spec such that the automated tests would already catch those.

**Comment by mity** [comment]
Well. Funny thing is that pullmark-cmark failed in theme completely differently so what was complicated for MD4C is not the same for pullmark-cmark and vice versa. Also some of these cover extensions like tables.
