### ISSUE TITLE
tables eat text preceding to them

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#293]
Given the tables is an extension to commonmark, it is not clear whether they should be allowed to interrupt a paragraph or not. But either way, they should not silently consume the text before them:

```
$ printf 'lorem ipsum\nA | B\n ---|---\nfoo | bar' | ./pulldown-cmark -T
<table><thead><tr><th>A </th><th>B</th></tr></thead><tbody>
<tr><td>foo </td><td>bar</td></tr>
</tbody></table>
```

Depending on whether you allow the paragraph interruption, the above should either output 
```
<p>lorem ipsum</p>
<table><thead><tr><th>A </th><th>B</th></tr></thead><tbody>
<tr><td>foo </td><td>bar</td></tr>
</tbody></table>
```

or 

```
<p>lorem ipsum
A | B
---|---
foo | bar</p>
```

(MD4C and cmark-gfm do not allow the interruption and output the latter.)

**Comment by raphlinus** [comment]
Thanks for the report, that does look like a real issue.
