### ISSUE TITLE
Non-linear behavior when parsing "[](<..."

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#296]
```
$ time python -c 'print("[](<" * 10000)' | ./pulldown-cmark >/dev/null
real    0m1.600s
user    0m1.547s
sys     0m0.031s

$ time python -c 'print("[](<" * 20000)' | ./pulldown-cmark >/dev/null
real    0m6.134s
user    0m6.063s
sys     0m0.078s

$ time python -c 'print("[](<" * 40000)' | ./pulldown-cmark >/dev/null
real    0m24.085s
user    0m24.016s
sys     0m0.047s
```

**Comment by mity** [comment]
Likely caused by the fact that the parser accepts unescaped `<` in the `<>`-type of link destination:

```
$ printf '[](<<>)' | ./pulldown-cmark
<p><a href="%3C"></a></p>
```

That is against the spec:

> A link destination consists of either
> * a sequence of zero or more characters between an opening < and a closing > **that contains no line breaks or unescaped < or > characters**, or
>
> * a nonempty sequence of characters that does not start with <, does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

(Emphasis mine)

**Comment by oberien** [comment]
I can't verify that behaviour on #281. There I get [this graph](https://www.wolframalpha.com/input/?i=plot+%5B(26214.0,+1607501.0),+(52428.0,+2992827.0),+(78642.0,+4133549.0),+(104856.0,+5571305.0),+(131070.0,+7016048.0),+(157284.0,+8316662.0),+(183498.0,+9883032.0),+(209712.0,+11065276.0)%5D) for 200KB and [this graph](https://www.wolframalpha.com/input/?i=plot+%5B(1677721.0,+89575815.0),+(3355442.0,+177112216.0),+(5033163.0,+269324236.0),+(6710884.0,+357378271.0),+(8388605.0,+478089843.0),+(10066326.0,+533949863.0),+(11744047.0,+633455160.0)%5D) for 11MB of input data consisting only of that pattern. Both look pretty linear to me :)

**Comment by oberien** [comment]
This might be related to #282, which opens an autolink instead of the inline link used here.
