### ISSUE TITLE
Link ref. def. in a block quote 

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#298]
For the input
```
> [foo
> bar]: /url
>
> [foo bar]
```

I would expect something like 
```
<blockquote>
<p><a href="/url">foo bar</a></p>
</blockquote>
```

but I get 

```
<blockquote>
</blockquote>
<blockquote>
<p>[foo bar]</p>
</blockquote>
```

which makes no sense at all.

(tricky one from https://github.com/mity/md4c/blob/master/test/coverage.txt#L53)

**Comment by marcusklaas** [comment]
This is a hard one. Good catch!
