### ISSUE TITLE
Multi-line inline link inside a blockquote

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#301]
Input:
```
> [link](/url 'foo
> bar')
```

Actual output:
```
<blockquote>
<p><a href="/url" title="foo
&gt; bar">link</a></p>
</blockquote>
```

Expected output:
```
<blockquote>
<p><a href="/url" title="foo
bar">link</a></p>
</blockquote>
```

I.e. the blockquote mark `>` from second line should not propagate into the link title.

(Tricky one from https://github.com/mity/md4c/blob/master/test/coverage.txt#L239)

**Comment by marcusklaas** [comment]
These are excellent. Maybe we should combine our added coverage tests and submit them to CommonMark for inclusion to the main test suite?

**Comment by mity** [comment]
Maybe.

Or maybe as some kind of a separate test file, because in most cases they do not any new rules. They just combine the current rules described by the specification, sometimes even many of them, and I am not sure whether making the `spec.txt` longer is the right thing, because it is not just a test suite but also a textbook for people who want to just write valid Markdown documents.

**Comment by marcusklaas** [comment]
I hadn't considered these things. Your separate test file idea is probably even better :+1:
