### ISSUE TITLE
Fuzzer Literals

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#302]
As discussed in https://github.com/raphlinus/pulldown-cmark/pull/286#discussion_r280458531 we don't necessarily want all literals used in `pulldown-cmark` to end up in the list of literals we fuzz with. Instead we probably want to automatically extract some literals (especially ones used within branches, patterns and match-guards) and then manually add some that are not included in branching code.

One such literal we should manually add is a single entity of `entities.rs`, e.g. `&amp;`. We might also want to include some unicode characters with different lengths to find crashes due to incorrect handling of unicode.

Here is a list of literals automatically extracted from pulldown-cmark. The branching ones look good, but we might also want to include statics and possibly some other manual ones.

Which do you think would make the most sense @marcusklaas?

---

We can assume that whenever arrays are used, we only need to take into account the first element. For example in `if ["foo", "bar"].contains(baz) {` it's enough to just extract the first element to cover that branch.

Extracting only the first element of arrays (see below for the lists with all literals):

<details>
<summary>Literals inside statics (6)</summary>

```
"&#x27;",
"pre",
"&amp;",
"0123456789ABCDEF",
"!--",
"</pre>"
```
</details>

<details>
<summary>Literals inside consts (1)</summary>

```
"address"
```
</details>

<details>
<summary>Literals inside if-conditions / match arm patterns / guards (48)</summary>

```
"&",
"]",
">",
"~",
"$",
"\"",
"[]",
"0",
"{",
"> ",
")",
";",
"\'",
"A",
"@",
"CDATA[",
"^",
"`",
"|",
"#",
"[^",
"(",
"ssse3",
"x",
"%",
"\r",
"!",
"-",
"a",
"9",
"f",
"_",
"+",
"*",
":",
"}",
"<",
"\u{0}",
"=",
"Z",
" ",
"X",
"/",
"[",
"?",
"\\",
"\t",
"."
```
</details>

<details> 
<summary>All literals in pulldown-cmark (excluding entities.rs and main.rs) not in statics / consts / conditions (72)</summary>

```
"   ",
" align=\"center\">",
" align=\"left\">",
" align=\"right\">",
"&aXaaaa.a\'aa9a<>aab&",
"*bcd&f0123456789",
"*hello* world",
"0123456789abcde",
"0123456789abcdefghijkl",
"0123456789abcdefghijklm",
"0123456789abcde~*bcd&f0",
"0123456789abcde~~~~d&f0",
"4444444444444444444444444444444444444444444444444444444444!",
"</a>",
"</a></sup>",
"</code>",
"</del>",
"</em>",
"</h",
"</pre>"
"</pre>",
"</strong>",
"</sup>",
"</td>",
"</th>",
"<a href=\"",
"<a href=\"mailto:",
"<code>",
"<del>",
"<div class=\"footnote-definition\" id=\"",
"<em>",
"<h{}>",
"<img src=\"",
"<li>",
"<ol start=\"",
"<p>",
"<pre><code class=\"language-",
"<pre><code>",
"<strong>",
"<sup class=\"footnote-reference\"><a href=\"#",
"<table>",
"<td",
"<th",
"<thead><tr>",
"<tr>",
"Called unwrap on a Nil value",
"Expected a Inlined variant!",
"SWAG",
"This is a link w/o def: [hello][world]",
"YOLO",
"[ ]",
"[x]",
"[{}]",
"\" />",
"\" alt=\"",
"\" title=\"",
"\">",
"\"><sup class=\"footnote-definition-label\">",
"\u{1bca0}",
"abcdef0123456789",
"match_count: {}, byte: {:?}",
"unexpected item body {:?}",
"world",
"{}",
"¡",
"« Blurry Eyes »",
"«\u{a0}Blurry Eyes\u{a0}»][blurry_eyes]",
"،",
"藏",
"･",
"𛲟",
"🍔",
```
</details>

Extracting all literals of arrays (instead of just the first one):

<details>
<summary>Literals inside statics (19)</summary>

```
"style",
"?",
"&lt;",
"script",
"0123456789ABCDEF",
"&amp;",
"</pre>",
"pre",
"&quot;",
"&gt;",
"]]>",
">",
"</style>",
"</script>",
"!--",
"?>",
"&#x27;",
"-->",
"![CDATA["
```
</details>

<details>
<summary>Literals inside consts (62)</summary>

```
"section",
"base",
"nav",
"h6",
"caption",
"basefont",
"address",
"source",
"h5",
"td",
"noframes",
"title",
"legend",
"main",
"menuitem",
"dialog",
"dd",
"h3",
"frame",
"track",
"figcaption",
"link",
"ul",
"tfoot",
"colgroup",
"center",
"option",
"body",
"html",
"summary",
"form",
"optgroup",
"article",
"table",
"iframe",
"footer",
"dt",
"li",
"details",
"param",
"th",
"ol",
"frameset",
"thead",
"col",
"dir",
"hr",
"figure",
"dl",
"h4",
"blockquote",
"h2",
"tbody",
"fieldset",
"tr",
"header",
"div",
"head",
"p",
"menu",
"aside",
"h1"
```
</details>

<details>
<summary>Literals inside if-conditions / match arm patterns / guards (48)</summary>

```
"[]",
"{",
"@",
"\'",
"+",
"]",
"$",
"9",
"> ",
"|",
"_",
"<",
"?",
"ssse3",
"f",
"\"",
"\u{0}",
"*",
"0",
"X",
".",
" ",
"&",
"!",
"=",
"~",
":",
"-",
";",
"[^",
">",
"\\",
"%",
"[",
"#",
"(",
"\t",
"CDATA[",
"^",
"`",
"a",
"/",
"Z",
"}",
"A",
"x",
")",
"\r"
```
</details>

<details> 
<summary>All literals in pulldown-cmark (excluding entities.rs and main.rs) not in statics / consts / conditions (69)</summary>

```
"   ",
" align=\"center\">",
" align=\"left\">",
" align=\"right\">",
"&aXaaaa.a\'aa9a<>aab&",
"*bcd&f0123456789",
"*hello* world",
"0123456789abcde",
"0123456789abcdefghijkl",
"0123456789abcdefghijklm",
"0123456789abcde~*bcd&f0",
"0123456789abcde~~~~d&f0",
"4444444444444444444444444444444444444444444444444444444444!",
"</a>",
"</a></sup>",
"</code>",
"</del>",
"</em>",
"</h",
"</sup>",
"</td>",
"</th>",
"<a href=\"",
"<a href=\"mailto:",
"<code>",
"<del>",
"<div class=\"footnote-definition\" id=\"",
"<em>",
"<h{}>",
"<img src=\"",
"<li>",
"<ol start=\"",
"<p>",
"<pre><code class=\"language-",
"<pre><code>",
"<strong>",
"<sup class=\"footnote-reference\"><a href=\"#",
"<table>",
"<td",
"<th",
"<thead><tr>",
"<tr>",
"Called unwrap on a Nil value",
"Expected a Inlined variant!",
"SWAG",
"This is a link w/o def: [hello][world]",
"YOLO",
"[ ]",
"[x]",
"[{}]",
"\" />",
"\" alt=\"",
"\" title=\"",
"\">",
"\"><sup class=\"footnote-definition-label\">",
"\u{1bca0}",
"abcdef0123456789",
"match_count: {}, byte: {:?}",
"unexpected item body {:?}",
"world",
"{}",
"¡",
"« Blurry Eyes »",
"«\u{a0}Blurry Eyes\u{a0}»][blurry_eyes]",
"،",
"藏",
"･",
"𛲟",
"🍔",
```
</details>

**Comment by oberien** [comment]
I should include literals in consts in the list of statics. Also I should only use a single literal per const / static, as they are most likely used in the same branches. (e.g. not include all `HTML_END_TAGS`, but only the first one. Same for `HTML_TAGS`). I'll do that later today and report back.

**Comment by mity** [comment]
[OFF-TOPIC]

@oberien Sorry for the off-topic question, but what are those clickable roll-down triangles in the 1st post, used to roll down more content? Yet another GFM extension? Never saw them yet. Cannot find any docs about them.

**Comment by oberien** [comment]
@mity https://stackoverflow.com/questions/32814161/how-to-make-spoiler-text-in-github-wiki-pages/33033172#33033172

**Comment by mity** [comment]
@oberien Thanks.

What a relief. I was afraid I missed some important feature of GFM in MD4C implementation.

[/OFF-TOPIC]

**Comment by oberien** [comment]
I updated the comment and added a second list only taking into account the first element of arrays.

I'd say we should opt for only including the first element of arrays. We should use literals in statics, consts and conditions. Additionally we should add the following literals manually:

* `&amp;`: This triggers the `entities.rs` branch. It *should* already be included from the statics, but adding it an additional time to make sure it's really there doesn't cost anything.
* `\u{a0}`: Unicode no-break space.
* `\u{0}`: First 1-byte UTF-8 character.
* `\u{80}`: First 2-byte UTF-8 character.
* `\u{800}`: First 3-byte UTF-8 character.
* `\u{10000}`: First 4-byte UTF-8 character.

**Comment by oberien** [comment]
Due to the more relevant literals that are now being used, the parse time increased significantly, more than halving the throughput. Also the false-positive rate increased significantly due to this.
