### ISSUE TITLE
Non-linear behaviour when parsing "*~~\u{a0}"

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#307]
Also produced by `~~_a`.

[plot](https://www.wolframalpha.com/input/?i=plot+%5B(26215.0,+14999087.0),+(52428.0,+59359636.0),+(78642.0,+136215463.0),+(104856.0,+244850386.0),+(131070.0,+394244799.0),+(157285.0,+556634061.0),+(183498.0,+761634573.0),+(209712.0,1007746879.0)%5D)

**Comment by marcusklaas** [comment]
I can't reproduce this behavior with either example. What branch did you produce this on?

**Comment by oberien** [comment]
I fuzzed on #281. Whenever strikethrough (must be enabled) occurs next to inline-formatting (like italic), non-linear behaviour can be observed. Did you test without strikethrough enabled? In that case it doesn't happen.

**Comment by marcusklaas** [comment]
Aaah, indeed I did not have the extension enabled! I'm getting quadratic behavior now as well. My bad!  :man_facepalming:
