### ISSUE TITLE
Panic "index out of bounds"

### ISSUE THREAD

**Issue by Draphar** [raphlinus/pulldown-cmark#308]
I recently published my crate [test-exec](https://github.com/Draphar/test-exec) and all CI builds were successful. So, I was pretty surprised when docs.rs failed to build it, and it turns out when that pulldown_cmark panics when trying to document it, but only on Nightly. Steps to reproduce (only the compiler error):

```sh
git clone https://github.com/Draphar/test-exec
cd test-exec
cargo +nightly doc
```

Error:
```
thread 'rustc' panicked at 'index out of bounds: the len is 2 but the index is 2', /cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.4.1/src/parse.rs:1105:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (e305df184 2019-04-24) running on x86_64-unknown-linux-gnu

error: Could not document `test-exec`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-name test_exec src/lib.rs --color always -o /home/joshua/Rust/test-exec/target/doc -L dependency=/home/joshua/Rust/test-exec/target/debug/deps --extern wait_timeout=/home/joshua/Rust/test-exec/target/debug/deps/libwait_timeout-e992bdb7635958bf.rmeta` (exit code: 1)
```

[docs.rs error](https://docs.rs/crate/test-exec/0.1.0/builds/158337)

**Comment by marcusklaas** [comment]
Woops, that's no good. Thanks for reporting this. We'll have a look.

**Comment by Draphar** [comment]
I just [updated](https://github.com/Draphar/test-exec/commit/a33e5cd41439c01171d839ff87d8f507bfd4b70e) the repository "fixed" the error. Here is the code to reproduce the error now:
```sh
git clone https://github.com/Draphar/test-exec
cd test-exec
git reset --hard e6865dfba602446c6761fde7c72436a204daa27c
cargo +nightly doc
```

**Comment by dimbleby** [comment]
Suspect that the issue is a lone `#` somewhere, or similar.

At v0.5.0, the following testcase fails:

```rust
    #[test]
    fn single_octothorpe() {
        // dont crash
        assert_eq!(3, Parser::new("#").count());
    }
```

with 
```
---- parse::test::single_octothorpe stdout ----
thread 'parse::test::single_octothorpe' panicked at 'index out of bounds: the len is 1 but the index is 1', src/parse.rs:1119:17
```
However, it passes on master so I guess this was fixed somewhere along the line.

(I wonder whether this project would be a good target for fuzzing - you'd have thought that a decent fuzzer ought to be able to find a single-character crash without too much trouble!  Is this something you've considered?)

Anyway: can we have a 0.5.1 release including the fix please?

**Comment by oberien** [comment]
Regarding fuzzing you can check out #286. It's implementing a fuzzer which detects non-linear parsing behaviour. At the same time it catches and reports some panics. This issue for example might be related to #305, which the fuzzer found.

**Comment by dimbleby** [comment]
Interesting - that's an ambitious use of fuzzing that I've not seen before. 

However, I can confirm that if 'all' you want to do is find crashes then simply following the instructions for `cargo fuzz` will do the job.  I'll raise a fresh issue with the first one that I found.

**Comment by raphlinus** [comment]
I think the next release out of master will be 0.6.0 due to StrWrite, but I agree, it seems like a good time. It feels to me the fixes for the issues surfaced by fuzzing can roll into point releases in the 0.6 line.

**Comment by marcusklaas** [comment]
This particular bug seems to be fixed!
