### ISSUE TITLE
Deeply nested inline markup test failures

### ISSUE THREAD

**Issue by raphlinus** [raphlinus/pulldown-cmark#31]
There are cases where current algorithm can get confused with deeply nested inline markup. In addition, time complexity is not as good as it should be. I worked out the outline of an algorithm to fix both issues, but didn't implement it. Below are my notes, in case someone else wants to take it on.

Relevant for #30 which is trying to make 0.26 spec succeed.

== Intro
- Imperative algorithm as counterpart to declarative rules in spec
- Not normative
  - Very interesting exercise to prove equivalence to spec

== Definitions
- input is a sequence of code units
  - Any of UTF-8, 16, 32 would work. Only important requirement is that ASCII is 1 unit
- slice is pair of indices into input sequence, representing subsequence from start inclusive to end exclusive
- "after than" relationship on slices
  - reduces to numerical comparison of (say) start index because no slices overlap in context of this algorithm
- delimiter run is as in spec
- "match" is pair of slices representing open and close of markup

== General structure of algorithm
- input is inline text
- output is set of matches
- two passes over input
  - first pass is links
  - second pass is other inline markup
- algorithm runs as forward scan over input, producing matches in arbitrary order (actually post-order traversal)
- this is something of an abstract model of the algorithm; impls are free to do something else (like represent a match by creating a node in an AST)
  - nonetheless, intended to be quite practical to run as is

=== First pass (links)
- Output is:
  - a set of matches corresponding to links
  - a set of skippable spans (link labels, link definition and title)
- internal state is:
  - a stack of:
    - a slice, which indexes a '![' or '[' in the input
    - an optional match, a pair of opener and closer in the input
  - a "high water mark", which is a stack depth, initially zero

==== Step 1: get rid of backslash, html, and inline code
- [add details...not particularly interesting]

=== Step 2:
- scan forward through input, skipping over items identified in step 1
  - on '![':
    - push slice on stack
  - on '[':
    - push slice on stack
  - on ']':
    - let link_inside = high water mark == current stack depth
    - if link_inside, high water mark -= 1
    - let (opener, cand) = pop from stack
      - if stack empty, just skip
    - if link_inside and opener is '[', then not a link, continue scanning
    - peek next character (skipping whitespace)
      - if next character is '(':
        - parse link destination and title
        - if successful:
          - add link destination and title to skippable spans
          - "form a link" with opener, closing ']'
      - else if inner text is a valid link ref:
        - if cand exists:
          - "form a link" with cand
          - add span to skippable spans
      - else:
        - if cand exists and cand is a valid link ref:
          - "form a link" with cand
        - if next character is '[':
          - push following '[' on stack with opener, closing ']' as candidate
          - skip past next '[' (already processed)
- at end of scanning, for each item on stack:
  - if cand exists and cand is a valid link ref:
    - "form a link" with cand

=== subroutine "form a link"
- add opener, closer slices to match set
- if opener is '[', set high water mark to current stack depth

=== Second pass (strong and emph)
- internal state is one stack of slices for each type of nested markup: `[]`, `*`, `_`
  - stack represents opening markup
  - should easily generalize to more types
    - choices regarding precedence

==== Step 1: get rid of backslash, html, and inline code
- same as first pass

==== Step 2: recognize delimiter runs
- skip over skippable spans found in first pass
- scan remaining characters, recognizing potential inline markup
- for '[' and ']':
  - only include if it was in a match set found in first pass
  - size is 1
- for '*' and '_':
  - group together maximal sequences of the same character
- everything else is ignored
- result of this step is a sequence of slices

==== Core of algorithm
- For each delimiter run, do:
  - Determine can_open and can_close
    - rules as in spec, + `[` can_open and `]` can_close
  - Set "candidate" to delimiter run, will be mutated
  - if can_close:
    - while candidate is nonempty, do:
      - determine if eligible opener
        - eligible opener means corresponding stack for candidate is nonempty, and precedence is satisfied
        - let tos = top of corresponding stack for candidate
        - precedence is satisfied if candidate is of type `]`, or stack for `[` is empty, or tos comes after top of stack for `[`
      - if not eligible opener, break out of loop
      - let k ("size of match") = if `_` or `*` then minimum of size of tos, size of candidate, and the constant 2, else 1
      - match is last k code units of tos, first k code units of candidate
      - add that match to output
      - delete all slices in all stacks that come after tos
      - chop last k code units off tos; if tos becomes empty, pop
      - chop first k code units off candidate; if candidate becomes empty, break out of loop
  - if can_open and candidate is nonempty:
    - push candidate onto corresponding stack

**Comment by marcusklaas** [comment]
This can be closed now I think?

**Comment by raphlinus** [comment]
Yes it can! This would have been a *bear* to fix in the old codebase.
