### ISSUE TITLE
Weird parsing time behaviour with inline-code

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#312]
With the fuzzer I have lots of huge outliers when encountering inline-code patterns where the whole content is within the inline-code: ``"`…`"``. Here are 3 examples out of over 100 patterns:

* ``"`/[^a[]`"``: [plot](https://www.wolframalpha.com/input/?i=plot+(26214.0,+675757.0),+(52428.0,+1353310.0),+(78642.0,+2264795.0),+(104856.0,+535590.0),+(262140.0,+7351585.0)%5D)
* ``"`!--~]<`"``: [plot](https://www.wolframalpha.com/input/?i=plot+(26214.0,+514864.0),+(52428.0,+978035.0),+(78642.0,+1438818.0),+(104856.0,+367181.0),+(262140.0,+5152704.0)%5D)
* ``"`>a[]!--`"``: [plot](https://www.wolframalpha.com/input/?i=plot+(26214.0,+514951.0),+(52428.0,+1018647.0),+(78642.0,+232410.0),+(209712.0,+4781845.0),+(262140.0,+6035850.0)%5D)

**Comment by mity** [comment]
In general, if you have an input which requires more then one scan over the input, then I would expect plots exactly like that: At certain input size your CPU cache gets exhausted, releasing some data from it, so the subsequent scan(s) have to load again the data from the main memory and that has some associated cost.

**Comment by mity** [comment]
Or not. The jump would be in the opposite direction. I should rather go to bed tonight to refresh my brain.

**Comment by marcusklaas** [comment]
It looks like these are not indicative of scaling issues, but rather symptoms of taking substrings of the patterns that are not proper multiples. The fuzzer doesn't work like that any more.
