### ISSUE TITLE
Does not conform to Example 265

### ISSUE THREAD

**Issue by ykomatsu** [raphlinus/pulldown-cmark#32]
CommonMark Spec says:

> In order to solve of unwanted lists in paragraphs with hard-wrapped numerals, we allow only lists starting with 1 to interrupt paragraphs.

http://spec.commonmark.org/0.26/#example-265

```
$ ./target/debug/pulldown-cmark
The number of windows in my house is
14.  The number of doors is 6.
<p>The number of windows in my house is</p>
<ol start="14">
<li>The number of doors is 6.</li>
</ol>
```

**Comment by marcusklaas** [comment]
Fixed!
