### ISSUE TITLE
New lines in link reference definition labels

### ISSUE THREAD

**Issue by marcusklaas** [raphlinus/pulldown-cmark#326]
```
[

a

]: x
```
is accepted as a reference definition, but it's not valid.

**Comment by mity** [comment]
I cannot find anything in the specs which prohibits multiple new lines there (it see link ref. def. as a block and some block types may contain blank lines).

But from the intuitive POV, it does not make much sense, so it is likely also a bug in the specs.

**Comment by jgm** [comment]
The specs for block elements ensure that you won't have blank lines inside the text for a paragraph, heading, or other element that contains inline content.  (You can have blank lines inside code blocks, of course.)  For example,

"A sequence of **non-blank lines** that cannot be interpreted as other kinds of blocks forms a paragraph."

For this reason, the spec for link labels doesn't explicitly need to rule out blank lines within link labels.
In your example above, you have three paragraphs.  Since the pieces are in different paragraphs, the issue about whether a link label can contain blank lines never arises.

**Comment by mity** [comment]
@jgm I think that your argument is silently based on the fact that some implementations (cmark, MD4C and likely others) do not parse link ref. defs as other block kinds but only cut them later from head of what they originally parse as a paragraph. 

But that's just an implementation detail, isn't it? The specification never describes the implementations should do that, or does it? And there definitely are some block types which **can** contain a blank line, like e.g. a code block, raw HTML block, list item.

**Comment by mity** [comment]
@jgm And by the way, using or not using that silent assumption also affects how link ref. def. behave e.g. in respect to paragraph continuation lines in block quotes or list items.

**Comment by jgm** [comment]
@mity that's a good point; I hadn't considered the use of link labels inside link reference definitions.

I'm not sure I understand the other point:

> And by the way, using or not using that silent assumption also affects how link ref. def. behave e.g. in respect to paragraph continuation lines in block quotes or list items.

I reopened the github issue on commonmark-spec to track this.

**Comment by mity** [comment]
> I'm not sure I understand the other point:
>
>>   And by the way, using or not using that silent assumption also affects how link ref. def. behave e.g. in respect to paragraph continuation lines in block quotes or list items.

@jgm Consider this example

```
> [ref]: /url
Lorem ipsum.
```

Cmark and MD4C renders 

```
<blockquote>
<p>Lorem ipsum.</p>
</blockquote>
```

The paragraph is inside the block quote because it reads it all as a single paragraph which is later broken into pieces, as noted in the earlier comments. But if the ref. def. is supposed to be standalone block on its own, it should really be

```
<blockquote>
</blockquote>
<p>Lorem ipsum.</p>
```

**Comment by jgm** [comment]
Ah yes, I'm aware of this issue.  (I was confused because I thought you had in mind a case with whitespace in the link label.)  It's [already in the tracker](https://github.com/commonmark/commonmark-spec/issues/574), correct?

**Comment by mity** [comment]
Sorry I missed it's already known issue.
