### ISSUE TITLE
Since 0.3.0, a line with only a space after a table causes the table to continue

### ISSUE THREAD

**Issue by carols10cents** [raphlinus/pulldown-cmark#330]
The smallest test case I've been able to get so far is this:

```
Markdown | Less | Pretty
--- | --- | ---
 
some text
```

Reduced from [this test file in pulldown-cmark-to-cmark](https://github.com/Byron/pulldown-cmark-to-cmark/blob/108c355c252d4b2dd420812ee63cd6f002a66c95/tests/fixtures/table.md)

**NOTE THERE IS A SPACE ON THE LINE BETWEEN THE TABLE AND THE PARAGRAPH!**

If I check out the v0.2.0 tag of pulldown-cmark, build, and run the following, I get the HTML I expect:

```
$ ./target/debug/pulldown-cmark -T < ~/rust/pulldown-cmark-to-cmark/tests/fixtures/table.md
<table><thead><tr><th>Markdown </th><th> Less </th><th> Pretty</th></tr></thead><tbody>
</tbody></table>
<p>some text</p>
```

However, if I check out the v0.3.0 tag, build, and run the same command on the same reduced file, the table doesn't end and the "some text" gets pulled into the table:

```
$ ./target/debug/pulldown-cmark -T < ~/rust/pulldown-cmark-to-cmark/tests/fixtures/table.md
<table><thead><tr><th>Markdown </th><th>Less </th><th>Pretty</th></tr></thead><tbody>
<tr><td></td><td></td><td></td></tr>
<tr><td>some text</td><td></td><td></td></tr>
</tbody></table>
```

The same undesired behavior happens with the current master, 2db7ccfb18b1f229d0ad8eec2f20a83fed8863c5 (v0.5.1):

```
$ ./target/debug/pulldown-cmark -T < ~/rust/pulldown-cmark-to-cmark/tests/fixtures/table.md
<table><thead><tr><th>Markdown </th><th>Less </th><th>Pretty</th></tr></thead><tbody>
<tr><td></td><td></td><td></td></tr>
<tr><td>some text</td><td></td><td></td></tr>
</tbody></table>
```

**Comment by marcusklaas** [comment]
Thanks for filing this. That behavior indeed is not sensible. Luckily, it shouldn't be too hard to fix.
