### ISSUE TITLE
Fuzzer produces NaN scores 

### ISSUE THREAD

**Issue by marcusklaas** [raphlinus/pulldown-cmark#333]
When setting `DEBUG_LEVEL` to 2, I'm only getting NaN scores like this:
```
[(262141.0, 13471871.0), (262141.0, 14449377.0), (262141.0, 12136441.0), (262141.0, 13265482.0), (262141.0, 13521479.0)]
slopes: [-inf, inf, -inf, inf, inf, -inf, inf, -inf, inf, inf]
NaN
```
I haven't dug very deep yet. Do you know what may be causing this @oberien?

**Comment by oberien** [comment]
Yes, I do, an oversight of me… Will fix it.

https://github.com/raphlinus/pulldown-cmark/blob/a7cd5be91ac71e2abd692331f06079d3ff36cc1c/fuzzer/src/main.rs#L395-L398
