### ISSUE TITLE
Raw HTML block versus HTML inline.

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#336]
Input:
```
<foo bar>
```

Expected output:
```
<foo bar>
```
(Rationale: https://spec.commonmark.org/0.29/#html-blocks, start condition 7)

Actual output:
```
<p><foo bar></p>
```
(So, the tag is good enough for inline HTML, but not for HTML block? Strange.)

**Comment by mity** [comment]
Imho the block start condition 7 and inline HTML (the open and close tag cases) should ideally share code as much code as possible in order to guarantee the consistency.

**Comment by marcusklaas** [comment]
Indeed, this is [long overdue](https://github.com/raphlinus/pulldown-cmark/blob/master/src/scanners.rs#L1233) ;-)

**Comment by marcusklaas** [comment]
Blocks of type 7 don't seem to allow multi-line attribute values though, whereas this is fine for inline html. So I guess they're not completely equivalent.

This is inline, apparently.
```
<foo bar="hello
world">
```

**Comment by mity** [comment]
That's true, and not only in the attributes. The complete tag must be on the single line for the block case.
```
<tag
attr="this cannot be block too"
attr2="but still it can be inline">
```

But I believe the EOLs are the only difference. The parser function for that may be parametrized to handle both cases, but not with just a bool value as the inline may be prefixed with some block decorations, e.g. in a blockquote:

```
> This paragraph inside a blockquote can contain an <inline_html
> attr="spanning over two lines">.
```

MD4C works that way. See [`md_is_html_tag()`](https://github.com/mity/md4c/blob/master/md4c/md4c.c#L951). In [the case of block](https://github.com/mity/md4c/blob/master/md4c/md4c.c#L5170), the caller has also additionally test there is nothing more on the line.

**Comment by marcusklaas** [comment]
Aah yes, that's a great point. We're currently missing some logic to properly deal with multiline leaf elements in containers like blockquotes. Will need to think a bit about how to best solve this.

Thanks once more for your excellent issues!

**Comment by marcusklaas** [comment]
Hmmm wait, your example doesn't render as inline html in the reference implementation :thinking: 

https://spec.commonmark.org/dingus/?text=%3E%20This%20paragraph%20inside%20a%20blockquote%20can%20contain%20an%20%3Cinline_html%0A%3E%20attr%3D%22spanning%20over%20two%20lines%22%3E.

**Comment by mity** [comment]
Because I shouldn't use the underscore.

```
> This paragraph inside a blockquote can contain an <inlinehtml
> attr="spanning over two lines">.
```

**Comment by mity** [comment]
> We're currently missing some logic to properly deal with multiline leaf elements in containers like blockquotes. Will need to think a bit about how to best solve this.

In MD4C, this is done during block analysis which not just determines type of the block but it also (for leaf blocks) constructs vector of `MD_LINE` structs (one per every line the leaf block consists of). The structure holds just offset `beg` for beginning of line after (all parent) block decorations and `end` (offset before `'\n'` and before any trailing whitespace or line decorations if there is anything like that).

Every inline parser function gets a vector of the `MD_LINE` structs on the input and they are then implemented as two loops, main one over the lines in the vector, and inner one over bytes inside that line.

It handles the blockquotes as well as tables (vector of single `MD_LINE` describes the cell contents boundaries) or ATX headers (here it can also hide the final optional `#` sequence). This way there is good separation between the block parsing and inline parsing: The inline parsers actually have no need to know how deeply in the block hierarchy they live or what's type or properties of any of those blocks.
