### ISSUE TITLE
Document minimum version of Rust required

### ISSUE THREAD

**Issue by Keats** [raphlinus/pulldown-cmark#342]
It looks like the latest version has bumped the minimum version to 1.33? I only found that when CI failed for a project with 1.31.

The pattern I follow on my projects is to have a CI task with the known lowest allowed version so I know if a dependency or some new features are requiring a newer Rust: https://github.com/Keats/tera/blob/master/.travis.yml

**Comment by marcusklaas** [comment]
I must admit that I don't know. We haven't tracked this so far. It's a good idea.

**Comment by Keats** [comment]
It's 1.34
