### ISSUE TITLE
Incorrect parsing of headers with trailing tab

### ISSUE THREAD

**Issue by rnitta** [raphlinus/pulldown-cmark#344]
I found [spec 0.29 example 52](https://spec.commonmark.org/0.29/#example-52) is not converted correctly.

code is like

```rust
use pulldown_cmark::{html, Options, Parser};

fn main() {
    let original = r##"  Foo *bar
baz*	
===="##;
// ↑ <tab> after "baz*"

    let expected = r##"<h1>Foo <em>bar
baz</em></h1>"##;

    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_FOOTNOTES);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_TASKLISTS);
    let parser = Parser::new_ext(original, options);
    let mut generated = String::new();
    html::push_html(&mut generated, parser);
    println!("expected:\n{}", expected);
    println!("generated:\n{}", generated);
}
```

the output is 

 ```
expected:
<h1>Foo <em>bar
baz</em></h1>
generated:
<h1>Foo <em>bar
baz</em>	</h1>
```

I've been wandering on the code and finally I couldn't find where to fix.
So just report it.

**Comment by marcusklaas** [comment]
There are two bugs in play here. First, there's simply failing to strip the trailing whitespace. The second is that our html normalization code for tests, which lives [here](https://github.com/raphlinus/pulldown-cmark/blob/master/tests/lib.rs), incorrectly *does* strip whitespace.

**Comment by marcusklaas** [comment]
Should have a fix for this. Thanks for reporting it!
