### ISSUE TITLE
Configure link attributes as options

### ISSUE THREAD

**Issue by Keats** [raphlinus/pulldown-cmark#346]
I have seen 2 requests for absolute links attributes that are present on Blackfriday (a md renderer in Go):

## target=blank

Initial feature request from Zola with more details: https://github.com/getzola/zola/issues/681

## rel="noopener/noreferrer/nofollow"

Initial feature request from Zola with more details: https://github.com/getzola/zola/issues/695

Those are three separate options in Blackfriday (https://gohugo.io/getting-started/configuration/#blackfriday-options)

cc @lukeshiao and @MichaelByrneAU in case they have other things they want to mention.

This is easily implementable in Zola itself but it sounds like something like can/should be built-in.

**Comment by Keats** [comment]
@marcusklaas would that be accepted as a PR? I say that without having looked at the pulldown-cmark code so hopefully it's not too hard to implement.

**Comment by Keats** [comment]
ping @marcusklaas

**Comment by marcusklaas** [comment]
Apologies for the long silence here. It's a tricky issue. It's currently still uncertain whether we want to keep the standard renderer mean and lean or provide something more complete out of the box.

I've opened a discussion on this subject on the xi zulip. I hope to share a decision soon!

**Comment by marcusklaas** [comment]
This was discussed briefly with @raphlinus and it seems best to leave more advanced rendering features to a separate crate. We'll maintain a lean implementation within this repository. It should be fairly straightforward to take this implementation and extend it in another crate. If a good community effort emerges, we might bless that. If not, I may start one myself.

Hope that this answers your question.

**Comment by marcusklaas** [comment]
Since this won't be addressed at least in the near future, I will close this issue for now.
