### ISSUE TITLE
Is it possible to add header-id anchor when rendering to html, or how?

### ISSUE THREAD

**Issue by darkdarkfruit** [raphlinus/pulldown-cmark#355]
Great rust idiomatic lib!
I tried but could not figure out how to add "#anchor" in rendered html header.
eg: 
```markdown
# abc
```
could be rendered as
``` html
<h1 id="level1">abc</h1>
```
Thank you very much!

**Comment by marcusklaas** [comment]
The current way to do this is to map `Event::Start(Tag::Header(1))` to `Event::InlineHtml("<h1 id=\"level1\">")`.

We're currently discussing whether we want the default renderer to be more flexible (https://github.com/raphlinus/pulldown-cmark/pull/350 is one such experiment) or that the above solution is feasible for most cases and leave it to users to implement their own renderer when it is not.

**Comment by darkdarkfruit** [comment]
Nice idea!
Talking about flexibility, it might be more convenient if we can add/remove tag easily.
Thanks your quick responding!
