### ISSUE TITLE
Unicase dependency adds 50KB to release WASM builds

### ISSUE THREAD

**Issue by LaylConway** [raphlinus/pulldown-cmark#357]
I'm using this crate in a web frontend framework for markdown rendering.
This is a very size-sensitive target.

While looking over what's taking up a lot of my build's size using twiggy, I noticed that unicase's lookup table takes up 50KB.

```
 51805 ┊    10.71% ┊ unicase::unicode::map::lookup::h4ead59c88430d332
```

It seems to be only used to do lowercase equality checks on link labels.

https://github.com/raphlinus/pulldown-cmark/blob/master/src/linklabel.rs#L33

I'm not sure if this extra-correct functionality is worth a full 50KB in release mode.
Would it be possible to do just a `.to_lowercase()` check, either as default or behind a crate feature?

**Comment by marcusklaas** [comment]
This can probably be solved using unicase's [Ascii](https://docs.rs/unicase/2.4.0/unicase/struct.Ascii.html) struct instead of the general Unicase type.

However, it seems this wouldn't be strictly CommonMark compliant since [it states explicitly that unicode case folding is required](https://spec.commonmark.org/0.29/#matches). As you suggest, we could still do it as a crate feature.

**Comment by LaylConway** [comment]
An alternative option may be to piggyback on JS engines' built-in string types when compiling for wasm32, using `localCompare` with `sensitivity: 'accent'`. This would keep the implementation CommonMark compliant while also reducing the size. This would make more sense to be implemented in unicase though, and it introduces a risk of different platforms working slightly differently.

**Comment by seanmonstar** [comment]
Thanks to the excellent work in https://github.com/seanmonstar/unicase/pull/35, unicase v2.5 contains a much smaller lookup table.

**Comment by marcusklaas** [comment]
That's great news! Is the new ~4kB overhead small enough to warrant closing this issue after upgrading to v2.5?

**Comment by raphlinus** [comment]
In my opinion, yes. Fantastic news!

**Comment by LaylConway** [comment]
Sounds like small enough to me too
