### ISSUE TITLE
Multi-paragraph list item nested in blockquote

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#358]
Input:
```
>* foo
>
>  bar
```

Expected output:
```
<blockquote>
<ul>
<li>
<p>foo</p>
<p>bar</p>
</li>
</ul>
</blockquote>
```

Actual output:
```
<blockquote>
<ul>
<li>foo</li>
</ul>
<p>bar</p>
</blockquote>
```

**Comment by marcusklaas** [comment]
Are you sure about this one? The list item should end after a blank line, correct?

Dingus produces the same output as pulldown-cmark here.

**Comment by mity** [comment]
Maybe there is a bug in cmark too.

See https://spec.commonmark.org/0.29/#example-226. If I prepend everz line of it with blockquote mark, it should be the same output, just wrapped in the blockquote, as per https://spec.commonmark.org/0.29/#block-quotes, the "basic case".

**Comment by mity** [comment]
(Hmm. And MD4C fails too here.)

**Comment by mity** [comment]
I raised it in cmark so maybe we can wait for @jgm what he thinks about it. But Im afraid both from specs wording and from some intuitive POV, all the noted implementations are wrong here.

**Comment by mity** [comment]
See also https://spec.commonmark.org/0.29/#example-229. That seems to me as a more complex variant of the test case (order list instead of unordered and more complicated indentations), yet it seems to agree with our "expected output".

**Comment by mity** [comment]
As explained in commonmark/cmark#304, it is an expected behavior (as of the specs wording) after all.

Sorry for the noise.
