### ISSUE TITLE
Separate parser, type definitions and renderer into their own crates

### ISSUE THREAD

**Issue by BertalanD** [raphlinus/pulldown-cmark#359]
The Tag enum is already able to represent most elements of various markup languages. It's the perfect candidate for transforming into a Pandoc-like document converter system, only faster and safer thanks to Rust.

By splitting off the type definitions/AST, different crate authors could implement Readers and Writers for their formats of choice, which would output and consume a common type. It would make conversions such as reStructuredText -> HTML, Markdown -> PDF and LaTeX -> DOCX possible; cases where the entire functionality of pulldown-cmark is not needed. 

Our representation of document structure could then be made compatible with the existing Pandoc ecosystem. [elliottslaughter/rust-pandoc-types](https://github.com/elliottslaughter/rust-pandoc-types) has already implemented the document structure defined by [jgm/pandoc-types](https://github.com/jgm/pandoc-types), however the changes between versions 1.17.0.5 and 1.17.5.4 have to be done (they are non-breaking though). The AST to JSON serialization would enable this interoperability. The different approaches to representation of document structure would however make this a non-trivial task.

Pulldown-cmark's types are currently missing
- definition lists,
- superscript,
- subscript,
- small caps,
- quoted/cite,
- math inlines/blocks,
- list style,
- custom key-value attributes, classes and identifiers on all Tags.
- and Pandoc has no support for task lists.

Even though, with the speed of the CommonMark standardization effort, they aren't going to be needed anytime soon for Markdown, they would come in handy for other formats.

I'm just a passionate hobbyist, I'm not sure how I could help, but I'm looking forward to implementations of more formats in Rust.

**Comment by oberien** [comment]
You might be interested in my [heradoc](https://github.com/oberien/heradoc/) project, which aims to be an opinionated "reimplementation" of pandoc. It doesn't revolve around any standards like you suggested (yet?), and it's mainly intended to be an easy to use markdown → pdf / website / other formats converter. I personally use it for my master thesis currently.
