### ISSUE TITLE
blank line with whitespace only is treated as a soft break

### ISSUE THREAD

**Issue by ehuss** [raphlinus/pulldown-cmark#370]
The following string (in Rust syntax) treats the line with whitespace as a soft break.

```
"Paragraph 1\n    \nParagraph 2\n"
```

Outputs the following events:

```
Start(Paragraph)
Text(Borrowed("Paragraph 1"))
SoftBreak
HardBreak
Text(Borrowed("Paragraph 2"))
End(Paragraph)
```

I would expect it to be treated as a "blank line" as defined in the spec.

> A line containing no characters, or a line containing only spaces (U+0020) or tabs (U+0009), is called a blank line.

and should emit the following events:

```
Start(Paragraph)
Text(Borrowed("Paragraph 1"))
End(Paragraph)
Start(Paragraph)
Text(Borrowed("Paragraph 2"))
End(Paragraph)
```

Using pulldown-cmark 0.5.2 (42296ca).

https://spec.commonmark.org/dingus/?text=Paragraph%201%0A%20%20%20%20%0AParagraph%202%0A

**Comment by raphlinus** [comment]
This seems like a bug to me. It's not a recent regression.
