### ISSUE TITLE
Pass link type to broken link callback

### ISSUE THREAD

**Issue by euclio** [raphlinus/pulldown-cmark#373]
It would be helpful to know what kind of link failed in the broken link callback to improve diagnostics in rustdoc for intra-doc links.

**Comment by marcusklaas** [comment]
We could add this, as well as https://github.com/raphlinus/pulldown-cmark/issues/165 fairly easily, but it'd be a breaking change. We're about to do a major release, so there is some room for such changes. However, I don't know what impact it'd have on other projects using broken link callbacks. Rustdoc is the big one and possibly the only one, but it'd be good to do a quick survey.

Thoughts, @raphlinus?

**Comment by raphlinus** [comment]
Seems like a good idea to me. If it were me, I'd ask for a PR, or at least a suggested signature, but maybe Marcus has other preferences.

**Comment by marcusklaas** [comment]
Those work for me for sure :+1:

**Comment by euclio** [comment]
I think the following would suffice as a signature:

```rust
fn callback(broken_reference: &'a str, title: &'a str, link_type: LinkType) -> Option<(String, String)>
```

This is assuming that it's safe to assume that `broken_reference` is borrowed from the original markdown (#165).

**Comment by Michael-F-Bryan** [comment]
This should also include *where* in the text a broken link is found. That way tools like link validators can give the user better error messages (including line numbers, content around the broken link, etc.).

**Comment by marcusklaas** [comment]
Done!
