### ISSUE TITLE
Autolinks not respecting block boundaries

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#381]
Input:
```
foo | bar
--- | ---
<http://|>
```

Actual output (with `-T`):
```
<table><thead><tr><th>foo</th><th>bar</th></tr></thead><tbody>
<tr><td><a href="http://%7C">http://|</a></td><td>&gt;</td></tr>
</tbody></table>
```

I would expect there is no autolink because what looks as one is actually broken into multiple table cells.

(Might be the same cause as the one for #351. Perhaps scanners for other inline elements should be reviewed too to verify the issue is not more widely spread.)

**Comment by marcusklaas** [comment]
Thanks for these!
