### ISSUE TITLE
Take FnMut for broken link callback

### ISSUE THREAD

**Issue by Mark-Simulacrum** [raphlinus/pulldown-cmark#385]
It's quite useful to be able to mutate some outside state in the broken link callback and this shouldn't add any significant complexity to the code (since Parser is consumed via iterator, which takes `&mut self` already).

This might be possible to do backwards compatibly, since all `FnMut` implement`Fn` as well, though not sure if inference and such are powerful enough to deduce that.

**Comment by marcusklaas** [comment]
This sounds like a good idea! Could you create a pull request for this?

**Comment by Mark-Simulacrum** [comment]
Oh, actually, now that I went to implement it... this isn't possible unfortunately as `Parser` is `Clone` which means we need the internals to be such, and where we currently store `&dyn Fn(...)` an `FnMut` is equivalent to `Fn` behind a shared reference so we wouldn't be able to implement this in a backwards compatible fashion at all. I'm going to close this as such.

**Comment by marcusklaas** [comment]
In case you missed it: this was actually added in 0.8.0! The `Clone` implementation was removed to accomodate it.
