### ISSUE TITLE
Backslash escape immediately after HTML tag is not handled properly.

### ISSUE THREAD

**Issue by ehuss** [raphlinus/pulldown-cmark#389]
A backslash escape immediately after any HTML tag is left in the output as-is. I believe the backslash should not be included in the output.

Input | Result | Note
------|--------|---------
`<sup>\*hi</sup>` | `<p><sup>\*hi</sup></p>` | Should not include backslash.
`<sup> \*hi</sup>` | `<p><sup> *hi</sup></p>` | Correct.
`<b>x</b>\_` | `<p><b>x</b>\_</p>` | Should not include backslash.

Tested latest master 0f0f9efdc390af17cd173a84aeee36ed667deedc.

**Comment by marcusklaas** [comment]
Thanks for reporting this bug! A fix for this is in progress.
