### ISSUE TITLE
html tag spanning lines in a blockquote closes unexpectedly

### ISSUE THREAD

**Issue by ehuss** [raphlinus/pulldown-cmark#399]
The following markdown:

```
> Note: Though you should not rely on this, all pointers to <abbr
> title="Dynamically Sized Types">DSTs</abbr> are currently twice the size of
> the size of `usize` and have the same alignment.
```

causes the `<abbr>` tag to close at the newline.  That is, it becomes:

```
<blockquote>
<p>Note: Though you should not rely on this, all pointers to <abbr
>title=&quot;Dynamically Sized Types&quot;&gt;DSTs</abbr> are currently twice the size of
the size of <code>usize</code> and have the same alignment.</p>
</blockquote>
```

I would expect the blockquote to be mostly transparent and allow the tag to continue.  commonmark.js dingus seems to handle it correctly.  GitHub handles it too (though it strips out `<abbr>` tags).

**Comment by marcusklaas** [comment]
Yup, that's a bug. Thanks for the issue!

**Comment by marcusklaas** [comment]
I've finally got around to this. It should be fixable.

**Comment by marcusklaas** [comment]
This has (finally) been fixed!
