### ISSUE TITLE
New algorithm and data structure

### ISSUE THREAD

**Issue by raphlinus** [raphlinus/pulldown-cmark#41]
The algorithm in #31 is too complex. I've thought about it some more, and think the best solution is an architectural rework. I've started prototyping but have opened this issue if anyone else is working on it - I can push my prototype to a branch for the curious.

CommonMark requires two passes. Part of the information passed from the first pass to the second is label definitions; whether a label is defined or not can have a profound effect on the parsing of inline markup.

Right now, pulldown-cmark scans the input twice. The information passed from the first to the second pass (`ParseInfo`) is minimal; it's basically the label definitions and information about which lists are "loose".

The new approach is to actually retain a significant amount of information between passes. The intermediate data structure is a tree. After the first pass, the tree contains all block-level structure, but paragraphs (with potentially inline markup) are a linear sequence of tokens, which can be text or "potential inline" (emphasis characters `_*` and link characters `[]`).

The second pass doesn't deal with the block-level structure at all. But when it sees potential inline, it scans through the tokens, mutating the tree when matches are found.

A major reason I didn't do a tree originally is that I wanted to avoid an allocation per node for the usual AST-style representation. However, it's possible to avoid that, by making the tree a `Vec` of nodes, annotated with "child" and "next" links (which are indices into the vector). Another very desirable property of this representation is that moving a sequence of subnodes into a child position is straightforward; it only requires mutation of the parent and last node in the sequence.

A goal of the new work is to make the parser always O(n), even with malicious input. There are a number of ways in which the current parser doesn't meet this goal. It requires some subtlety in the algorithm design (for example, the search for a matching delimiter must be O(1), not trivial due to [Emphasis and strong emphasis](http://spec.commonmark.org/0.27/#emphasis-and-strong-emphasis) Rule 9. But I think it is possible.

**Comment by notriddle** [comment]
Can I recommend TypedArena for this kind of tree structure? The Rust compiler uses it to great effect.

**Comment by raphlinus** [comment]
I thought about TypedArena, but I think this use case is pretty different from the normal AST - I'll be mutating both the tree structure and the node contents as I traverse. I _think_ I could make that work by making the node a `RefCell`, with `&'arena RefCell<Node>` as the type of the `child` and `next` references, but it's not clear at all to me how that's better than plain `Vec`, especially as I'll be able to come up with a pretty good estimate for the capacity, so reallocation should be rare.

**Comment by notriddle** [comment]
Since it's a tree, not a DAG, the child and next links can be `&mut` refs, so you can mutate the things just fine after you allocate them on the arena. Your mutating traversal code has to be recursive for you to do it in unsafe code, though. Yielding events and mutating the tree at the same time would require a traversal kernel with unsafe code in it (one does not simply store non-disjoint exclusive references in a Vec, even if it acts like a stack; it only works with the call stack because the borrow checker can control access to items on the call stack).

**Comment by raphlinus** [comment]
For the curious, I pushed a very early prototype as 5a02636. Really only emphasis parsing works, but the data structure seems pretty solid, and it should give a pretty good idea where this is going.

I _really_ want to avoid unsafe code. I think the `Vec` approach lets me do that, with no significant drawbacks in either performance or code clarity. I'm willing to reconsider if I'm missing something though.

**Comment by notriddle** [comment]
Makes sense.

**Comment by marcusklaas** [comment]
This has landed!
