### ISSUE TITLE
Weird output for nested lists

### ISSUE THREAD

**Issue by terhechte** [raphlinus/pulldown-cmark#418]
Hey! I'm getting a very weird output when parsing a certain type of (unfinished) nested list. If the list looks like this:

``` md
- first
- second
    - 
```

I.e. if the user is typing a list, and he begins typing the indented list, then the output of pulldown_cmark is:

``` html
<ul>
<li>
<h2>first
second</h2>
</li>
</ul>
```

I know that this is a convoluted case, but I'm using pulldown_cmark for a live editor, and this scenario happens everytime a user starts typing a nested list. It kind of breaks the syntax highlighting. 

I suppose it is somehow interpreting these as ATX headings. I've checked against a number of other markdown tools to see what their behavior is, and interestingly, they all differ. (Also, it seems to me this is undefined behavior in Commonmark). Here's a couple of tools and their output for the payload above:

[Stackedit](https://stackedit.io/app#)
``` html
<ul>
<li>first</li>
<li>
<h2 id="second">second</h2>
</li>
</ul>
```

[Dillinger](https://dillinger.io)
``` html
<ul>
<li class="has-line-data" data-line-start="0" data-line-end="1">first</li>
<li class="has-line-data" data-line-start="1" data-line-end="3">
<h2 class="code-line" data-line-start=1 data-line-end=3 ><a id="second_1"></a>second</h2>
</li>
</ul>
```
[Pandao](https://pandao.github.io/editor.md/en.html)
``` html
<ul>
<li>first</li><li>second<br>  - </li></ul>
```

[Gist](https://gist.github.com/terhechte/04641fc6dc74f3431bfb402bfa2ad9a9)
``` html
<ul>
<li>first</li>
<li>
<h2>second</h2>
</li>
</ul>
```

Based on this, it seems the most-used approach seems to be:

``` html
<li>first</li>
<li><h2>second<h2></li>
```

Whereas pulldown_cmark currently returns 

```
<li>
<h2>first
second</h2>
</li>
```

So, it is mostly detecting the second `li`. I'd also happily help fixing this bug but I'd need some pointers for what would be the best approach.

**Comment by raphlinus** [comment]
I'm not reproducing your reported behavior of current pulldown_cmark. This is what I get:

```
<ul>
<li>first</li>
<li>
<h2>second</h2>
</li>
</ul>
```

This also matches the results of the cmark dingus. Thus, I would say we're following the spec, though I agree that this is less than ideal in an interactive editing environment. I might suggest bringing this up as an issue against the CommonMark spec.

**Comment by terhechte** [comment]
Thanks for the quick reply, I'm on `version = "0.6.1"` (Just created a test project to make sure it wasn't something particular to my project) and this is my code:

``` rust
// main.rs
extern crate pulldown_cmark;

use pulldown_cmark::{Options, Parser, html};

fn main() {
    let markdown = "- first wanted\nsecond most wanted\n    - ";

    let mut options = Options::empty();
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_FOOTNOTES);
    let parser = Parser::new_ext(markdown, options);

    // Write to String buffer.
    let mut html_output = String::new();
    html::push_html(&mut html_output, parser);

    println!("{}", &html_output);
}
```

And this is the result:

``` html
<ul>
<li>
<h2>first wanted
second most wanted</h2>
</li>
</ul>
```

**Comment by raphlinus** [comment]
That also matches the cmark output, but it doesn't match what you first posted (there's no "- " before "second").

**Comment by terhechte** [comment]
Hm, I'll create a CommonMark issue then and add some sort of cleanup to my implementation that detects this case and doesn't break the highlighting. Thanks!
