### ISSUE TITLE
Panic with links and images inside headers

### ISSUE THREAD

**Issue by Hirevo** [raphlinus/pulldown-cmark#421]
While trying to test an alternative crate registry I am building ([here]), I tried to re-render all the READMEs of all the crates from crates.io using `pulldown-cmark`.  

By doing so, I got a few panics coming from within the iterator returned by `Parser::new_ext(...)` only with a few crates.  
And by looking at the contents of their READMEs, I noticed that they all feature links and images inside their headers, with empty image title (eg. `![]`).  

Here is a minimal code example to trigger the panic (using a reduced version from the README from the `assimp` crate as input):
```rust
use pulldown_cmark::{Parser, Options};

static CONTENTS: &str =
r#"# assimp-rs [![][crates-badge]][crates]

[crates]: https://crates.io/crates/assimp
[crates-badge]: http://meritbadge.herokuapp.com/assimp
"#;

fn main() {
    let events = Parser::new_ext(CONTENTS, Options::all()).collect::<Vec<_>>();
    println!("event count: {}", events.len());
}
```

<details>
<summary>And here is the complete panic backtrace from the code above:</summary>
<pre><code>thread 'main' panicked at 'slice index starts at 30 but ends at 15', src/libcore/slice/mod.rs:2670:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2670
  15: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2845
  16: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2928
  17: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/slice/mod.rs:2647
  18: pulldown_cmark::parse::Parser::scan_inline_link
             at /home/hirevo/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.6.1/src/parse.rs:2330
  19: pulldown_cmark::parse::Parser::handle_inline_pass1
             at /home/hirevo/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.6.1/src/parse.rs:2095
  20: pulldown_cmark::parse::Parser::handle_inline
             at /home/hirevo/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.6.1/src/parse.rs:1957
  21: <pulldown_cmark::parse::Parser as core::iter::traits::iterator::Iterator>::next
             at /home/hirevo/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-0.6.1/src/parse.rs:2804
  22: alloc::vec::Vec<T>::extend_desugared
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:2108
  23: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:2005
  24: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:2000
  25: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/vec.rs:1901
  26: core::iter::traits::iterator::Iterator::collect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/iter/traits/iterator.rs:1493
  27: cmark_issue::main
             at src/main.rs:11
  28: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  32: std::panicking::try
             at src/libstd/panicking.rs:265
  33: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  34: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  35: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  36: cmark_issue::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.</code></pre>
</details

For testing purposes, here is the complete list of the crates whose READMEs caused a panic in that way:
- `rmpv`
- `rmp-serde`
- `doc-comment`
- `sysinfo`
- `minitt`
- `assimp`
- `assimp-sys`
- `tlhelp32`
- `voile`
- `run-down`
- `bear`
- `p3p`
- `directx`
- `directx-sys`
- `dotplot`
- `airbrake`

[here]: https://github.com/Hirevo/alexandrie

**The versions I am using:**

`pulldown_cmark`: `0.6.1`
`rustc`: `1.40.0` (stable toolchain)

**Comment by marcusklaas** [comment]
Wow, this is a serious one. Thank you so much for your very detailed report. I will investigate this.
