### ISSUE TITLE
Custom section heading ID extension

### ISSUE THREAD

**Issue by lo48576** [raphlinus/pulldown-cmark#424]
`## heading {#custom-id-here}` syntax is common among many markdown processers, but pulldown-cmark currently does not support it, and for now applications needs to implement it manually (<https://github.com/getzola/zola/pull/685> is one of them).
By this feature, users can avoid breakage of cross references, and can make documents more portable.

I believe this extension syntax is very useful and well known enough, and I'm happy if this is supported by pulldown-cmark.

cc: <https://github.com/rust-lang/mdBook/issues/1141>

**Comment by marcusklaas** [comment]
This seems useful, and already supported by [a number of implementations](https://babelmark.github.io/?text=%23%23+heading+%7B%23custom-id-here%7D).

Unfortunately, as with many extensions, there is [no clear consensus](https://talk.commonmark.org/t/anchors-in-markdown/247) on the precise syntax. [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#spe-attr) is one option, but it is quite a bit more general than the simple header case.

**Comment by oberien** [comment]
IETF mentiones the `{#<id>}` "Fragment Identifiers" in their [Guidance on Markdown (RFC 7764)](https://tools.ietf.org/html/rfc7764) being used by PHP Markdown Extra and pandoc.

Also in heradoc I decided to use `# Header {#label}` for inline-style header labels. See the "unified labels" checkmark in the [Readme](https://github.com/oberien/heradoc/blob/master/README.md).

**Comment by marcusklaas** [comment]
Pulldown now supports custom header IDs and classes thanks to @lo48576! <3
