### ISSUE TITLE
Support for underline

### ISSUE THREAD

**Issue by HelloEdit** [raphlinus/pulldown-cmark#428]
Hello,

As a md4c user, I wonder if it would be possible to implement underline syntax as an option?

> With the flag `MD_FLAG_UNDERLINE`, underscore (_) denotes an underline instead of an ordinary emphasis or strong emphasis.

Thank,

**Comment by Martin1887** [comment]
Sorry, but this is out of the scope of this project, as it is conflict with CommonMark. It could probably be implemented as a external crate if a plugin system is finally created, but that will not happen in the short term.
