### ISSUE TITLE
Newline required after HTML comment for links to work

### ISSUE THREAD

**Issue by alexcrichton** [raphlinus/pulldown-cmark#43]
Found some unusual behavior today, and was curious if it was a bug or not! I wasn't sure if this was intentional by the spec or whether it's a bug:

Given this document

```md
[foo][bar]

<!-- foo -->
[bar]: a
```

pulldown cmark will render it as:

```
$ pulldown-cmark < ./foo.md
<p>[foo][bar]</p>
<!-- foo -->
[bar]: a
```

whereas this document:

```md
[foo][bar]

<!-- foo -->

[bar]: a
```

will render as 

```
$ pulldown-cmark < ./foo.md
<p><a href="a">foo</a></p>
<!-- foo -->
```

**Comment by notriddle** [comment]
I think it's intentional. The commonmark spec specifiers that whole blocks are rendered as HTML, where "blocks" of text are separated by blank lines.

**Comment by kivikakk** [comment]
An easy way to determine the correctness is to run a sample against the "dingus": http://spec.commonmark.org/dingus/?text=%5Bfoo%5D%5Bbar%5D%0A%0A%3C!--%20foo%20--%3E%0A%5Bbar%5D%3A%20a%0A

In this case, CommonMark does expect the reference-style link to be interpreted and applied. Per [HTML block start condition 4](http://spec.commonmark.org/0.27/#start-condition), the block is considered to be ended as soon as a line containing the string `-->` is encountered, meaning the reference on the following line should be interpreted as a new block; a blank line shouldn't be necessary.

So this is a slight divergence.

**Comment by ayosec** [comment]
I have the same issue with a list.

The following code

```markdown
<!-- <dl> -->
- **foo** (u8, u8)

  make something

- **bar** (u16, u16)

  make something
```

Is rendered as:

```html
<!-- <dl> -->
- **foo** (u8, u8)
<p>make something</p>
<ul>
<li>
<p><strong>bar</strong> (u16, u16)</p>
<p>make something</p>
</li>
</ul>
```

But in spec.commonmark.org, it is:

```html
<!-- <dl> -->
<ul>
<li>
<p><strong>foo</strong> (u8, u8)</p>
<p>make something</p>
</li>
<li>
<p><strong>bar</strong> (u16, u16)</p>
<p>make something</p>
</li>
</ul>
```

[Link to dingus](http://spec.commonmark.org/dingus/?text=%3C!--%20%3Cdl%3E%20--%3E%0A-%20**foo**%20%28u8%2C%20u8%29%0A%0A%20%20make%20something%0A%0A-%20**bar**%20%28u16%2C%20u16%29%0A%0A%20%20make%20something%0A)

**Comment by marcusklaas** [comment]
pulldown_cmark now renders all these examples consistent with dingus.
