### ISSUE TITLE
into_offset_iter() does not give correct range for link references

### ISSUE THREAD

**Issue by dsherret** [raphlinus/pulldown-cmark#430]
For example, given the following markdown:

```markdown
# H1
[testing](https://github.com)
[testing][Some reference]

[Some reference]: https://github.com
```

The events and ranges are like so:

```
Event: Start(Heading(1))
Range: 0..5
Event: Text(Borrowed("H1"))
Range: 2..4
Event: End(Heading(1))
Range: 0..5
Event: Start(Paragraph)
Range: 5..61
Event: Start(Link(Inline, Borrowed("https://github.com"), Borrowed("")))
Range: 5..34
Event: Text(Borrowed("testing"))
Range: 6..13
Event: End(Link(Inline, Borrowed("https://github.com"), Borrowed("")))
Range: 5..34
Event: SoftBreak
Range: 34..35
Event: Start(Link(Reference, Borrowed("https://github.com"), Borrowed("")))
Range: 35..36
Event: Text(Borrowed("testing"))
Range: 36..43
Event: End(Link(Reference, Borrowed("https://github.com"), Borrowed("")))
Range: 35..36
```

So for inline links it will give the full range of `5..34`, which is correct. The reference link is incorrect though as it gives `35..36` instead of `35..60`.

~~I can look into this issue.~~ The only reason I need this though is because I am manually parsing out link reference text because it's not provided another way. Edit: Actually, I'm just going to work around this as I don't have time at the moment to fix it.

**Comment by marcusklaas** [comment]
Good catch, and thank you for reporting it. I shall investigate.

**Comment by dsherret** [comment]
Also, `FootnoteReference` does not have the full width:

```markdown
Testing this[^1] out.

[^1]: Footnote.
```

Outputs:

```
Event: Start(Paragraph)
Range: 0..22
Event: Text(Borrowed("Testing this"))
Range: 0..12
Event: FootnoteReference(Borrowed("1"))
Range: 12..13 <-- should be 12..16
Event: Text(Borrowed(" out."))
Range: 16..21
Event: End(Paragraph)
Range: 0..22
Event: Start(FootnoteDefinition(Borrowed("1")))
Range: 23..39
Event: Start(Paragraph)
Range: 29..39
Event: Text(Borrowed("Footnote."))
Range: 29..38
Event: End(Paragraph)
Range: 29..39
Event: End(FootnoteDefinition(Borrowed("1")))
Range: 23..39
Text: "Testing this[^1] out.\n\n[^1]: Footnote.\n"
```

**Comment by alerque** [comment]
This is related to #411, not only is the range misreported here, but some information is missing.

**Comment by dsherret** [comment]
@marcusklaas could there be a release for this? Thanks!

**Comment by marcusklaas** [comment]
Yes, I'll do a release containing this fix shortly. Planning one before the end of the week.

**Comment by marcusklaas** [comment]
It was [released](https://crates.io/crates/pulldown-cmark/0.7.2)!

**Comment by dsherret** [comment]
Thanks @marcusklaas! I just tested it out now and it's working well 🙂
