### ISSUE TITLE
Hangs on unterminated html tag

### ISSUE THREAD

**Issue by jpospychala** [raphlinus/pulldown-cmark#437]
This was initially reported in `rust-clippy` in https://github.com/rust-lang/rust-clippy/issues/4917
that clippy hangs on doc comment `/// <foo`

I can see that same issue occurs directly in pulldown_cmark parser:

```rust
#[test]
fn test_unterminated_foo() {
    use pulldown_cmark::Parser;
    let parser = Parser::new("<foo");
    for _ in parser {}
}
```

**Comment by oberien** [comment]
I wonder when this was introduced. I'd expect this to be caught by the fuzzer. Therefore, I think this was probably introduced after the last fuzzing.
