### ISSUE TITLE
whitespace issue with nested lists

### ISSUE THREAD

**Issue by BartMassey** [raphlinus/pulldown-cmark#443]
Rendering this string (*edited*):

```rust
r#"Some text.
 
* A list.
 
   * A sublist.
 
   * Another sublist.
"#
```

as HTML with `pulldown_cmark` 0.7.1 results in this output:

```html
<p>Some text.</p>
<ul>
<li>
<p>A list.</p>
</li>
<li>
<p>A sublist.</p>
</li>
<li>
<p>Another sublist.</p>
</li>
</ul>
```

which disagrees with the old Perl `markdown` in that `markdown` indents the sublists.

See [`rustdoc` issue #72556](https://github.com/rust-lang/rust/issues/72566). Thanks to @ehuss for help with isolation.

**Comment by marcusklaas** [comment]
Do you mean that literal string or

```
Some text.

* A list

   * A sublist.

   * Another sublist.

```
?

Because the latter does render as a sublist.

**Comment by BartMassey** [comment]
Yes, I screwed up the bug report. The literal string to reproduce the bug is
```rust
r#"Some text.
 
* A list.
 
   * A sublist.
 
   * Another sublist.
"#
```

The bug appears to be caused by the space on the otherwise-blank lines.

Apologies for the confusion.

**Comment by marcusklaas** [comment]
Ah, I gotcha. I can reproduce it now. I'll try to look into this tomorrow.

Thanks for the report!

**Comment by marcusklaas** [comment]
Just an update to let you know that I am in fact working on this. It's been a long time since I last touched this and our list/ blockquote handling is a bit tricky. I feel that I am close though.

**Comment by terhechte** [comment]
I just came here to report a very similar bug. It is a bit different, but might have the same reason. I'll just quickly note it:

``` md
- first
- second
- third
- fourth
```
Generates the following events: 
`Start:List, Start:Item, StartText, End:Text, End:Item, Start:Item, ...`

Just adding one newline suddenly wraps all items into paragraphs:

``` md
- first
- second

- third
- fourth
```
Generates the following events: 
`Start:List, Start:Item, Start:Paragraph, StartText, End:Text, End:Paragraph, End:Item, Start:Item, ...`

Is that expected or a bug?

**Comment by marcusklaas** [comment]
I *think* that's intended behavior. There's this thing called 'tightness' of markdown lists. The specifics cannot be reproduced immediately by me, but it basically means that we wrap the contents of list items in paragraphs whenever the list isn't 'tight', i.e., there are blank lines between the list's items.

**Comment by terhechte** [comment]
> I _think_ that's intended behavior. There's this thing called 'tightness' of markdown lists. The specifics cannot be reproduced immediately by me, but it basically means that we wrap the contents of list items in paragraphs whenever the list isn't 'tight', i.e., there are blank lines between the list's items.

Good to know! I found a workaround to cope with this behavior, so just ignore my comment :) Markdown has quite the hidden complexity, I have to say.

**Comment by BartMassey** [comment]
Thanks much for fixing!
