### ISSUE TITLE
Parser calls `broken_link_callback` twice for broken reference links

### ISSUE THREAD

**Issue by jyn514** [raphlinus/pulldown-cmark#444]
Code:
```rust
use pulldown_cmark::{Options, Parser};

fn main() {
    let markdown_input: &str = "See also [`g()`][crate::g] and [`h()`]";
    println!("Parsing the following markdown string:\n{}", markdown_input);

    // Set up parser.
    let parser = Parser::new_with_broken_link_callback(markdown_input, Options::empty(), Some(&|_, bad_link| {
		println!("got broken link: {}", bad_link);
		None
	}));
    for _ in parser {}
}
```
Output:
```
Parsing the following markdown string:
See also [`g()`][crate::g] and [`h()`]
got broken link: crate::g
got broken link: crate::g
got broken link: `h()`
```
This is causing issues downstream in https://github.com/rust-lang/rust/pull/72771, I can work around them but I think it would be better for pulldown to only call the callback once for each broken link.

**Comment by jyn514** [comment]
As best I understand, this is because `[g()][crate::g]` is
1. evaluated as a potential link
2. found not to be a link because the callback returns `None`,
3. treated as a text node, then
4. `[crate::g]` is _re-evaluated_ as another potential link.

The change I would like to see is for step 4. to be removed: we already know `crate::g` can't be a link because we found that out in step 2.

**Comment by marcusklaas** [comment]
Thanks for filing this. I agree that it's not very intuitive to trigger the callback twice in such situations.

I see you've already started work on this yourself, which is much appreciated! Send me a ping there when you get the test suite to pass, and I'll review. Similarly, if you need any help, I'm also available :-)

Thanks again!

**Comment by marcusklaas** [comment]
This should be fixed now on master!
