### ISSUE TITLE
Paragraphs added to list items if there is a blank line between one of the items

### ISSUE THREAD

**Issue by dsherret** [raphlinus/pulldown-cmark#455]
Given the following:

```md
- a
- b
- c
- d
```

The output is:

```
0..16 Start(List(None))
0..4 Start(Item)
2..3 Text(Borrowed("a"))
0..4 End(Item)
4..8 Start(Item)
6..7 Text(Borrowed("b"))
4..8 End(Item)
8..12 Start(Item)
10..11 Text(Borrowed("c"))
8..12 End(Item)
12..16 Start(Item)
14..15 Text(Borrowed("d"))
12..16 End(Item)
0..16 End(List(None))
```

That's good.

----

Now if I put a blank line between one of the items:

```
- a
- b

- c
- d
```

Every item gets a paragraph:

```
0..17 Start(List(None))
0..4 Start(Item)
2..4 Start(Paragraph)
2..3 Text(Borrowed("a"))
2..4 End(Paragraph)
0..4 End(Item)
4..9 Start(Item)
6..8 Start(Paragraph)
6..7 Text(Borrowed("b"))
6..8 End(Paragraph)
4..9 End(Item)
9..13 Start(Item)
11..13 Start(Paragraph)
11..12 Text(Borrowed("c"))
11..13 End(Paragraph)
9..13 End(Item)
13..17 Start(Item)
15..17 Start(Paragraph)
15..16 Text(Borrowed("d"))
15..17 End(Paragraph)
13..17 End(Item)
0..17 End(List(None))
```

----

If I give one of these items a task list marker such as:

```md
- [ ] d
```

It will not have the task list marker inside the paragraph:

```
13..21 Start(Item)
15..18 TaskListMarker(false)
19..21 Start(Paragraph)
19..20 Text(Borrowed("d"))
19..21 End(Paragraph)
13..21 End(Item)
0..21 End(List(None))
```

Is all this expected behaviour? Thanks!

**Comment by oberien** [comment]
The spacing / wrapping of list items in paragraphs is intended CommonMark behaviour called [loose list](https://spec.commonmark.org/0.29/#loose) (compared to tight lists). I don't know about the TaskListMarker though.

**Comment by dsherret** [comment]
@oberien interesting so this is correct. I'm going to close this as I guess the task list marker being outside the paragraph could make sense.
