### ISSUE TITLE
Is it possible to provide a custom escaped sequence?

### ISSUE THREAD

**Issue by SchrodingerZhu** [raphlinus/pulldown-cmark#456]
Hello, I am using this crate to render my blog posts (for example, https://zhuyi.fan/post/optimization-learning-notes-4.html).

In my case, I would like to use it together with mathjax to render formulas, however, some symbols like `\\`, `_` and `\{` are mistranslated by `cmark`. Is it possible to let the parser escape the content quoted in math blocks (between `$` and `$$`)?

**Comment by marcusklaas** [comment]
It is not possible through pulldown itself. Your use case of inline math is a common request for markdown parsers (see https://github.com/raphlinus/pulldown-cmark/issues/6), but there is not a clear standard that we can implement.

I personally preprocess the markdown for my blog to render the math spans and blocks. It seems to be the only way to do math reliably with pulldown at this point.

**Comment by marcusklaas** [comment]
As this is essentially #6, I'll close this as duplicate. If anyone can produce a spec we could implement, please share it there and we will take under serious consideration.
