### ISSUE TITLE
Code block text is different structure depending on newline kind used

### ISSUE THREAD

**Issue by dsherret** [raphlinus/pulldown-cmark#457]
Given the following escaped text using line feeds:

```rs
let code_to_parse = "```\ntest\n\ntest\n```\n";
```

...the output is...

```
0..18 Start(CodeBlock(Fenced(Borrowed(""))))
4..15 Text(Borrowed("test\n\ntest\n"))
0..18 End(CodeBlock(Fenced(Borrowed(""))))
```

However, if carriage return line feeds are used...

```rs
let code_to_parse = "```\r\ntest\r\n\r\ntest\r\n```\r\n";
```

...the output is...

```rs
0..22 Start(CodeBlock(Fenced(Borrowed(""))))
5..9 Text(Borrowed("test"))
12..17 Text(Borrowed("\ntest"))
0..22 End(CodeBlock(Fenced(Borrowed(""))))
```

Shouldn't they be the same? Or is this some weird markdown thing I don't know about?

**Comment by marcusklaas** [comment]
That does look like a bug. Besides the normalization of line endings which the spec doesn't mandate, it seems to strip one empty line altogether. That's definitely not right.

I'll have a look. Thanks for reporting this.

**Comment by dsherret** [comment]
@marcusklaas yeah, I noticed it because blank lines were being stripped. It will also remove multiple consecutive blank lines.

**Comment by marcusklaas** [comment]
Hmm, weird. I tested your string locally, and my version of pulldown (0.7.2) produces `"<pre><code>test\n\ntest\n</code></pre>\n"` for both inputs, which doesn't strip the newlines.

What version of pulldown and platform are you running?

**Comment by dsherret** [comment]
@marcusklaas I'm using 0.7.2 on Windows 10. I didn't check the output of it, but I've just been looking at the Events when using `into_offset_iter()` with these options:

```rs
let mut options = Options::empty();
options.insert(Options::ENABLE_TABLES);
options.insert(Options::ENABLE_FOOTNOTES);
options.insert(Options::ENABLE_STRIKETHROUGH);
options.insert(Options::ENABLE_TASKLISTS);

let markdown_text = "```\r\ntest\r\n\r\ntest\r\n```\r\n";
for (range, event) in Parser::new_ext(markdown_text, options).into_offset_iter() {
    println!("{:?} {:?}", range, event);
}
```

**Comment by marcusklaas** [comment]
Wow, very strange. I'm running the same platform and version and that code produces this on my machine:
```
Start(CodeBlock(Fenced(Borrowed("")))) 0..22
Text(Borrowed("test")) 5..9
Text(Borrowed("\n")) 10..11
Text(Borrowed("\ntest")) 12..17
Text(Borrowed("\n")) 18..19
End(CodeBlock(Fenced(Borrowed("")))) 0..22
```

A headscratcher, this one.

**Comment by dsherret** [comment]
@marcusklaas wait it's doing that for me too once I created that more simpler example. Sorry, there is a bug deeper down in **my code** that was striping the empty blank lines. Sorry to waste your time on this one!

**Comment by dsherret** [comment]
I'm going to close this as that seems like reasonable output. Sorry again!! I have a custom iterator that does a few extra things and striping "empty" text events was one of them...

**Comment by marcusklaas** [comment]
No worries, it happens. Please don't hesitate to open other issues when you run into problems. These things make pulldown better :-)
