### ISSUE TITLE
Footnotes parsed without Options::ENABLE_FOOTNOTES

### ISSUE THREAD

**Issue by lunaryorn** [raphlinus/pulldown-cmark#459]
A parser created with `Parser::new_ext` *without* including `Options::ENABLE_FOOTNOTES` still emits a `FootnoteReference` event when seeing a footnote.  

I can provide a minimal example but I'd first like to clarify whether this is actually unexpected behaviour.

**Comment by marcusklaas** [comment]
This may be a bug indeed. Investigating...
