### ISSUE TITLE
Reuse parser to improve performance

### ISSUE THREAD

**Issue by IronOxidizer** [raphlinus/pulldown-cmark#463]
`Parser` should be reusable to improve performance. This would reduce the number of allocations since no new parser is required for each Markdown conversion and would also improve performance since parser options and custom event mapping would not have to be set for each new Parser.

This would be particularly useful in a case where many small parses are happening independently but with the same options and event mapping (e.g. a long forum thread with thousands of comments where each comment has to be parsed with non-standard markdown).

I propose a `parser.set_content(text: &'a str)` syntax as it would be rather intuitive and does not seem like it would break any current implementations.

**Comment by IronOxidizer** [comment]
This issue was made in reference to https://github.com/raphlinus/pulldown-cmark/issues/462#issuecomment-674417179

**Comment by marcusklaas** [comment]
I have briefly investigated this. It appears that it can be done, but with the restriction that the new text must have the same lifetime as the original input. This is because the parser's own lifetime (and that of its components) is tied to the original input.

**Comment by IronOxidizer** [comment]
I'm not familiar with pulldown-cmark's internals, but if the parser ingested a `mut String` instead of `&str` we could simply reuse the input string and have the lifetime bound to that instead. However, I'm sure this kind of change would have major consequences throughout the library.

**Comment by raphlinus** [comment]
I've seen this pattern before, and I think one way to address it is to make the parser polymorphic on `T: AsRef<str>`. This is probably a breaking change, but probably not hugely disruptive.

So I'm not arguing in favor or against at the moment, but throwing that out there.

**Comment by marcusklaas** [comment]
Ok, I made an [initial attempt] at implementing this and learned two more things:

1. the performance boost seems modest. Parsing the string `This is a [link](example.com). **Cool!**` 100 times is about 25% faster with parser reuse:

       reuse_naive             time:   [102.76 us 102.89 us 103.02 us]
       reuse_new               time:   [78.224 us 78.360 us 78.494 us]

2. reusing the iterator is awkward with the current design. Since `Parser` itself is the `Iterator` and many (all?) of the standard iterator methods (map, filter, etc.) consume the iterator, it cannot be reused after using any of these. This is probably salvageable by adding an iterator wrapper, so something like this:
   ```rust
   let mut parser = Parser::new(text);
   let event_iter = parser.get_iter().map(|ev| ...);
   parser.reuse(new_text);
   let another_event_iter = parser.get_iter();
   ```

[initial attempt]: https://github.com/marcusklaas/pulldown-cmark/tree/reuse

**Comment by jyn514** [comment]
nit about the API: I think it would be nicer to say `impl IntoIterator for &mut Parser` so you can keep using `for event in parser {`

**Comment by jyn514** [comment]
> reusing the iterator is awkward with the current design. Since Parser itself is the Iterator and many (all?) of the standard iterator methods (map, filter, etc.) consume the iterator, it cannot be reused after using any of these

Couldn't you use `for event in parser.by_ref()`? https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.by_ref

**Comment by marcusklaas** [comment]
Yup, that would be a better solution it looks like :+1:

**Comment by Martin1887** [comment]
It seems to me that the best solution is using `by_ref`, as proposed in the last comments. Feel free to resume the discussion if you find this useful.
