### ISSUE TITLE
What are the `broken_link_callback()` arguments?

### ISSUE THREAD

**Issue by vojtechkral** [raphlinus/pulldown-cmark#471]
The `broken_link_callback` takes two `&str` args, but the doc doesn't say what they are except

> the provided callback will be called with the reference name

In the source code, I can see that the callback is called as:

```rust
callback(link_label.as_ref(), link_label.as_ref())
```

... so it seems both arguments are the same thing ... Why is there the two of them?

Thanks!
Vojech

**Comment by marcusklaas** [comment]
Yeah, it's a bit of a mess at the moment. We're working on a [new design](https://github.com/raphlinus/pulldown-cmark/pull/469) which should make the design clearer, among other things.

**Comment by vojtechkral** [comment]
Ah, very cool, I'll let you get to it then :)

**Comment by marcusklaas** [comment]
This should be better now that https://github.com/raphlinus/pulldown-cmark/pull/469 has been merged. Let me know if you have any more questions!
