### ISSUE TITLE
Missing examples for some LinkType's 

### ISSUE THREAD

**Issue by laysauchoa** [raphlinus/pulldown-cmark#472]
I was not able to write an example for the following types [LinkType's](https://docs.rs/pulldown-cmark/0.6.0/i686-unknown-linux-gnu/pulldown_cmark/enum.LinkType.html)

```
                                //Reference, [foo][bar]
                                //ReferenceUnknown, [foo][] 
                                //Collapsed, ? no examples
                                //CollapsedUnknown, ? no examples
                                //Shortcut, [foo] 
                                //ShortcutUnknown, ? no examples
```

Would it be possible to give me some examples for them? Or are they supported already?

Many thanks,

**Comment by marcusklaas** [comment]
The unknown variants have broken references which were fixed by the callback. For example:
```md
This is a broken link: [foo][bar]

[baz]: http://example.com
```
When the link is fixed using the the broken link callback, it produces a link of type `ReferenceUnknown`.

Hope this answers your question.

**Comment by drahnr** [comment]
Actually, I think there is a difference in how the links are represented:

`prefix [I'm an inline-style link](https://duckduckgo.com) postfix`

is deconstructed as

```
[src/documentation/markdown.rs:67] event = Start(
    Paragraph,
)
[src/documentation/markdown.rs:67] event = Text(
    Borrowed(
        "prefix ",
    ),
)
[src/documentation/markdown.rs:67] event = Start(
    Link(
        Inline,
        Borrowed(
            "https://duckduckgo.com",
        ),
        Borrowed(
            "",
        ),
    ),
)
[src/documentation/markdown.rs:67] event = Text(
    Borrowed(
        "I\'m an inline-style link",
    ),
)
[src/documentation/markdown.rs:67] event = End(
    Link(
        Inline,
        Borrowed(
            "https://duckduckgo.com",
        ),
        Borrowed(
            "",
        ),
    ),
)
[src/documentation/markdown.rs:67] event = Text(
    Borrowed(
        " postfix",
    ),
)
[src/documentation/markdown.rs:67] event = End(
    Paragraph,
)
```

---

`[I'm an reference link][http://foo.bar/baz]`

is deconstructed as

```
[src/documentation/markdown.rs:65] event = Start(
    Paragraph,
)
[src/documentation/markdown.rs:65] event = Text(
    Borrowed(
        "[",
    ),
)
[src/documentation/markdown.rs:65] event = Text(
    Borrowed(
        "I\'m an reference link",
    ),
)
[src/documentation/markdown.rs:65] event = Text(
    Borrowed(
        "]",
    ),
)
[src/documentation/markdown.rs:65] event = Text(
    Borrowed(
        "[",
    ),
)
[src/documentation/markdown.rs:65] event = Text(
    Borrowed(
        "http://foo.bar/baz",
    ),
)
[src/documentation/markdown.rs:65] event = Text(
    Borrowed(
        "]",
    ),
)
[src/documentation/markdown.rs:65] event = End(
    Paragraph,
)
```

The expectation here would be that we see `Start` and `End` tags of type `Link` no matter what link type it is.

See unit tests `link_inline` and `link_reference` in https://github.com/drahnr/cargo-spellcheck/pull/105

Help would be much appreciated.

**Comment by marcusklaas** [comment]
The second does not contain a link, because the reference "http://foo.bar/baz" is not defined. If you want it to be a link, you'll either have to define the reference or use the broken link callback.

**Comment by drahnr** [comment]
Thanks for your fast response!

There are two issues that still persist:

For `[lnk][]` the parsing is still as shown in the previous post, just `Text` events, despite having registered a test handler as suggested using https://docs.rs/pulldown-cmark/0.7.2/src/pulldown_cmark/parse.rs.html#1955-1975:

```
    fn broken_link_handler(x: &str, y: &str) -> Option<(String, String)> {
        // do not copy this, it makes no sense, it's just a test helper
        Some((dbg!(x).to_owned(), dbg!(y).to_owned()))
    }
```

which should be ok and is covered by the spec as test case `548` in https://spec.commonmark.org/0.29/spec.json .

For all other variants, the handler fixes the initial issues with `Text` only events :)

The above handler seems to have a bit of a limitation though - in the case of `cargo-spellcheck` really all we care about is being able to extract the title and have appropriate link tags in the first step, only as a deferred (yet to be impl'd) stage we care about the link and reference correctness, but the registered handler does not gain access to the `title` that is covered - is there a way around this?

**Comment by marcusklaas** [comment]
That's weird. This snippet seems to work as expected on master:
```rust
extern crate pulldown_cmark;

use pulldown_cmark::{html, Options, Parser};

fn main() {
    let input: &str = "Hello world, check out [my website][].";
    println!("Parsing the following markdown string:\n{}", input);

    // Setup callback that sets the URL and title when it encounters
    // a reference to our home page.
    let callback = |x: &str, y: &str| -> Option<(String, String)> {
        Some((x.to_owned(), y.to_owned()))
    };

    // Create a parser with our callback function for broken links.
    let parser = Parser::new_with_broken_link_callback(input, Options::empty(), Some(&callback));

    // Write to String buffer.
    let mut html_output: String = String::with_capacity(input.len() * 3 / 2);
    html::push_html(&mut html_output, parser);

    // Check that the output is what we expected.
    let expected_html: &str =
        "<p>Hello world, check out <a href=\"my%20website\" title=\"my website\">my website</a>.</p>\n";
    assert_eq!(expected_html, &html_output);

    // Write result to stdout.
    println!("\nHTML output:\n{}", &html_output);
}
```
Note that in testcase 548, the reference does exist and the callback will never be called.

I'm not sure I understand what you mean by the title extraction for broken link callbacks. When a reference is not defined, there is no title to be retrieved.

**Comment by drahnr** [comment]
`cargo update` yielded a change:

```diff
-version = "0.7.1"
+version = "0.7.2"
```

for `cmark_pulldown` and that resolves the collapsed version :+1:

**Comment by marcusklaas** [comment]
Glad to hear it!

**Comment by drahnr** [comment]
Thanks a lot for your help and pointers!
