### ISSUE TITLE
README is outdated re unsafe blocks

### ISSUE THREAD

**Issue by camelid** [raphlinus/pulldown-cmark#480]
I don't think this line in the README is true anymore (emphasis mine):

> It is designed to be:
>
> - [...]
> - **Safe; written in pure Rust with no unsafe blocks**

There is unsafe code in the [`pulldown_cmark::escape` module](https://github.com/raphlinus/pulldown-cmark/blob/4f19f87385d63a16b6e03ba27e0d6975aa62dcf0/src/escape.rs) for SIMD stuff. There seem to be abut 3 instances of unsafe code outside of tests.

**Comment by raphlinus** [comment]
This can be worded better, but I think is still basically true. The SIMD stuff is an optional performance optimization, and it is off by default. Thus, unless the user explicitly opts into it (and presumably has some understanding of the tradeoffs), in normal use it is 100% safe Rust.

We would gladly accept a PR to word this more clearly.
