### ISSUE TITLE
Include span for Events, not just BrokenLinks

### ISSUE THREAD

**Issue by jyn514** [raphlinus/pulldown-cmark#486]
Rustdoc currently has code that looks like this (yes, it's awful): https://github.com/rust-lang/rust/blob/6f2e1c65933702186cc681a3772862afa77dd632/src/librustdoc/html/markdown.rs#L1076-L1088

Originally I was hoping I could get rid of it now that BrokenLinks have spans. But the spans are _only_ for the broken links, and rustdoc doesn't get them for `[parenthesized](links)`. Is it possible to add that info to `Event`? I think that would allow removing it from BrokenLink too, but I'm not 100% sure about that.

As a side note, it looks like pulldown includes the `[]` in the span - is that intentional? Rustdoc only wants the URL itself, which isn't currently possible: consider `[inline][link]`. The `-` in the diff is rustdoc's hacky generated span, the `+` is pulldown's span.

```
 LL | /// docs [label][with#anchor#error]
-   |                  ^^^^^^^^^^^^^^^^^ contains invalid anchor
+   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^ contains invalid anchor
```

**Comment by ehuss** [comment]
I believe [`into_offset_iter`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/struct.Parser.html#method.into_offset_iter) gives the Range for each Event. Rustdoc uses that in a few places already.

**Comment by jyn514** [comment]
Oh look at that! Thanks, I just didn't read the docs carefully enough :)
