### ISSUE TITLE
bug: \t-\tp broken

### ISSUE THREAD

**Issue by generateui** [raphlinus/pulldown-cmark#487]
Hi! I came across this bug on BabelMark, as I'm writing a markdown CST for C#. 

this lib writes an `<ul>` when having the input text `\t-\tp` (`\t` being a tab and `p` being paragraph content.

Version: 0.8

**Comment by generateui** [comment]
https://babelmark.github.io/?text=%09-%09It+offers

**Comment by marcusklaas** [comment]
Yup, that looks like a bug. Thanks for reporting it!
