### ISSUE TITLE
Bug: Lazy quoteline after empty quoteline

### ISSUE THREAD

**Issue by generateui** [raphlinus/pulldown-cmark#491]
See https://github.com/lunet-io/markdig/issues/480.

**Comment by raphlinus** [comment]
The behavior of pulldown-cmark matches the dingus. I believe you should take this up as a spec clarification; I'm not really seeing a motivation to change our code at this time.

**Comment by generateui** [comment]
As concluded similarly by the maintainer of Markdig. See https://talk.commonmark.org/t/unclear-paragraph-after-empty-quoteline-in-quote-block/3652 for the spec discussion.

**Comment by raphlinus** [comment]
Looking at the babelmark results, all *commonmark* implementations seem to agree, it's just the non-cm markdowns that have different behavior.

**Comment by generateui** [comment]
As per the spec discussion I'd suggest to close this. Direct link to spec example: https://spec.commonmark.org/0.29/#example-219
