### ISSUE TITLE
Nested brackets cause reference links to be dropped

### ISSUE THREAD

**Issue by jyn514** [raphlinus/pulldown-cmark#496]
Noticed this in https://github.com/rust-lang/rust/pull/77971. Is this intentional? I'm not super familiar with the markdown spec.

Input:
```markdown
Link to first [NonNull[u8]][NonNull]

[NonNull]: http://example.com


Link to second [NonNull[u8]]

[NonNull[u8]]: http://example.com
```

Output:
```html
<p>Link to first <a href="http://example.com">NonNull[u8]</a></p>
<p>Link to second [NonNull[u8]]</p>
<p>[NonNull[u8]]: http://example.com</p>
```
I'd at least expect the first and second to behave consistently; preferably both would link to example.com.

**Comment by jyn514** [comment]
and as a follow up - if this is too hard to support, would it be easier to make this work only when delimited by code blocks?
```md
Link to second [`NonNull[u8]`]

[`NonNull[u8]`]: http://example.com
```

**Comment by marcusklaas** [comment]
Reference links may not contain square brackets [per the spec](https://spec.commonmark.org/0.29/#reference-link).

**Comment by jyn514** [comment]
That's unfortunate ... I assume the link parsing is complicated enough it's not possible to tell the user this was skipped because it had a nested bracket?

**Comment by marcusklaas** [comment]
There currently isn't a way to signal this. I don't think we should either, mostly because it would open a can of similar issues where something sorta looks like something, but doesn't end up being that thing in the end. Should we signal we found an 'almost, but not quite' table, for example?

**Comment by jyn514** [comment]
From a purely selfish perspective, I'd like the criteria for warning to be 'looks like an intra-doc link', which includes brackets ... but I understand you have users other than rustdoc. I think the best way to address this is with something like https://github.com/deadlinks/cargo-deadlinks/, which can look for exactly this without having to affect other pulldown users.
