### ISSUE TITLE
Export the `BrokenLinkCallback` type

### ISSUE THREAD

**Issue by ClementNerma** [raphlinus/pulldown-cmark#498]
Hi,

This is just a little issue to ask if you could export the `BrokenLinkCallback` type, as it's currently public in the `parse` module, which is not public itself. This would be simplier to pre-declare broken link callbacks in code that uses this crate.

Thanks in advance and thanks for this amazing library :) !

**Comment by marcusklaas** [comment]
Good idea, we should probably do this. Thank you for the kind words!

**Comment by ClementNerma** [comment]
In fact I just realized fixing this was just a one-line change, so I opened a PR for it ^^ 

You can view it at https://github.com/raphlinus/pulldown-cmark/pull/499
