### ISSUE TITLE
question: Are `Start` and `End` tags guarunteed to be ordered correctly?

### ISSUE THREAD

**Issue by kneasle** [raphlinus/pulldown-cmark#500]
I'm building a Markdown formatter using pullmark, and for the correctness of the reformatting I need to know whether or not the output of `pullmark` will always produce a correctly ordered tree of `Start`s and `End`s - i.e. we never see a situation like this:
```
Start(x)
Start(y)
End(x)
End(y)
```

From the way commonmark is defined and from my observations of `pullmark` it seems like this is the case - but if there are any edge cases I'd like to know about them before getting too deep on the project...

Also, great library - it's saving me **a lot** of time and effort having to implement an efficient parser myself.  Thanks so much :1st_place_medal:!

**Comment by raphlinus** [comment]
Yes, it is a tree. It's remotely possible there is a bug because this is only enforced by convention, but internally the parse state is represented with stacks so each push should have a corresponding pop.

Thanks for the kind words, hope this helps.

**Comment by kneasle** [comment]
Awesome! Thank you `:)`.
