### ISSUE TITLE
Allow generating Gemini

### ISSUE THREAD

**Issue by ibotty** [raphlinus/pulldown-cmark#504]
I'd like to generate Gemini (markup) from markdown files, ideally with the same library software I use already uses to generate HTML.  Would you potentially accept a patch adding support (without additional dependencies of course)?

Of course it's a complicated by the fact that there not being a spec on how to translate various markdown constructs to gemini.

https://gemini.circumlunar.space/docs/specification.html section 5: *The text/gemini media type*

**Comment by marcusklaas** [comment]
This is certainly something that pulldown can be used for, but I believe it's not something that needs to be in the pulldown crate itself. Something similar was done in the [pulldown-cmark-to-cmark](https://crates.io/crates/pulldown-cmark-to-cmark) crate, which uses pulldown to re-emit markdown, possibly after doing some transformations.
