### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by ovidiu-ionescu** [raphlinus/pulldown-cmark#524]
I could not find a way to add ```target="_blank"``` to the html generated so that links open in a new tab.
Also, I could not find on the web, a consistent way to specify this behavior in markdown.

OTOH, it is quite easy to add rendering options to html in a similar way to the existing extension options of the parser.
I have already written the code, change is [here](https://github.com/raphlinus/pulldown-cmark/compare/master...ovidiu-ionescu:master).

Is this something interesting to the project?

**Comment by Martin1887** [comment]
Sorry, but this is out of the scope of this project. It could be an option of an external HTML renderer.
