### ISSUE TITLE
Consider breaking html escaping into subcrate?

### ISSUE THREAD

**Issue by alexwennerberg** [raphlinus/pulldown-cmark#526]
I really like the html escaping code for this library:

https://github.com/raphlinus/pulldown-cmark/blob/master/src/escape.rs

I've used it before by copy/pasting the relevant bits, but I was wondering if you'd consider putting it into a sub-crate so that it can be reused by other libraries that need to do html escaping?

**Comment by Keats** [comment]
It seems that every template engine/HTML renderer has their own method, is there an up to date benchmark for them?

**Comment by alexwennerberg** [comment]
Probably this one is fastest just by reading the code, plus the SIMD optimizations. I could put together some benchmarks

**Comment by Keats** [comment]
I was thinking of https://github.com/Kogia-sima/sailfish/tree/master/sailfish/src/runtime/escape that also does fancy things. It would be great to have benchmarks though.
