### ISSUE TITLE
Request for abbreviations/acronyms

### ISSUE THREAD

**Issue by heitorPB** [raphlinus/pulldown-cmark#527]
I'like to request support for abbreviations.

Abbreviations and/or acronyms (in HTML with the `<abbr>` tag) are not part of CommonMark neither GFM, but they are very useful.

Kramdown docs have a [nice example about it](https://kramdown.gettalong.org/quickref.html#abbreviations).

**Comment by marcusklaas** [comment]
This is a duplicate of https://github.com/raphlinus/pulldown-cmark/issues/5, so I will close this and respond there instead.
