### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by vedantroy** [raphlinus/pulldown-cmark#528]
I've been browsing the code to get an understanding of it & I have a few questions if you wouldn't mind answering!

- Why is `TreeIndex` a wrapper for `NonZeroUsize` instead of a wrapper for `usize`? (I saw https://github.com/raphlinus/pulldown-cmark/pull/184 but didn't really understand it).
- In `scan_containers` we `clone` `line_start` before calling `scan_blockquote_marker`, but `scan_blockquote_marker` seems to save/restore internally, so why do we do it twice?

**Comment by marcusklaas** [comment]
Hi Vedant, I'm happy to answer such questions!

> Why is `TreeIndex` a wrapper for `NonZeroUsize` instead of a wrapper for `usize`? (I saw #184 but didn't really understand it).

It is to allow for an optimization by the rust compiler. It understands that `NonZeroUsize` is never represented by the null word (all zeroes). So when it is wrapped in an `Option`, it can use that value to represent the `None` value. This is why `Option<TreeIndex>`, which is used a lot in pulldown's datastructures, is only one word long. Translated to machine code this should be exactly the same as using `usize` and remembering that `0` is never used, but this enforces things through the type system.

> In `scan_containers` we `clone` `line_start` before calling `scan_blockquote_marker`, but `scan_blockquote_marker` seems to save/restore internally, so why do we do it twice?

And that is because I wasn't being as sharp as you when I wrote that bit - excellent catch! Indeed we need not clone `line_start` there. Pull requests are welcomed! ;-)

**Comment by vedantroy** [comment]
Thanks for the response! I'm curious about what is going on here: https://github.com/raphlinus/pulldown-cmark/blob/8db4423ce78a1dad8a8377e0f25ebd48e0e534fc/src/firstpass.rs#L133.

Specifically, do we do nothing if there's a `BlockQuote`, but otherwise call `pop`?

**Comment by marcusklaas** [comment]
Yeah, that bit is somewhat tricky. All containers that are not blockquotes are ended by blank lines, or two in the case of list items. Blockquotes can have an arbitrary number of blank lines *within* them. Note that at the point in the code that you linked to, all the containers that are open have been scanned.

This is actually what `scan_containers` does: at the start of the line, it checks how many of them are still open and consumes the bytes that signal these continuations. This could be (nested) list items, blockquotes or indented code blocks. So my answer to [your question here](https://github.com/raphlinus/pulldown-cmark/pull/529#issuecomment-845311923) was actually incorrect! The function that does that is called `scan_block`.

**Comment by marcusklaas** [comment]
Oh my bad, I meant the [`parse_block`](https://github.com/raphlinus/pulldown-cmark/blob/8db4423ce78a1dad8a8377e0f25ebd48e0e534fc/src/firstpass.rs#L63) method!

**Comment by vedantroy** [comment]
Another question! Why do we peek the grandparent (instead of the parent) if the last line is blank?

https://github.com/raphlinus/pulldown-cmark/blob/8db4423ce78a1dad8a8377e0f25ebd48e0e534fc/src/firstpass.rs#L941

**Comment by marcusklaas** [comment]
Ah, that one's easy! List items (think of the like bullet points) are the direct parent there, and we want to change a property of the list itself, the list item's parent.

**Comment by marcusklaas** [comment]
Woops -- I see I missed your final question. Sorry about that.

In any case this may not be the ideal forum for discussing the code other than issues. I suggest such questions are taken to the #pulldown-cmark stream on the [xi zulipchat](https://xi.zulipchat.com/).
