### ISSUE TITLE
Document footnote syntax

### ISSUE THREAD

**Issue by ISSOtm** [raphlinus/pulldown-cmark#530]
It's not in the CommonMark spec, and unlike the GitHub syntax extensions, the README does *not* link to anything. I've only figured out the syntax by finding an example; where can the README point to?

**Comment by ehuss** [comment]
I don't think there are any specs to point to.  I believe this is inherited from [hoedown](https://github.com/hoedown/hoedown), which I think maybe was using the syntax from [php-markdown](https://michelf.ca/projects/php-markdown/extra/#footnotes).  Footnotes have become common across many markdown parsers, including GitHub's own [cmark fork](https://github.com/github/cmark-gfm) which confusingly GitHub does not enable their own footnote extension, but GitLab, which uses the same library, does enable it ([tests here](https://github.com/github/cmark-gfm/blob/85d895289c5ab67f988ca659493a64abb5fec7b4/test/extensions.txt#L645)). It is also mentioned in the [commonmark extensions](https://github.com/commonmark/commonmark-spec/wiki/Deployed-Extensions#note).  It is also documented in many places like [the Markdown Guide](https://www.markdownguide.org/extended-syntax/#footnotes).

Better documentation would be great, but in this instance there isn't anything concrete to point to. I think this project is free to grab the documentation I wrote [here](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html#footnotes) if it wants to use something more vague. Writing a spec would be valuable, but is somewhat tedious. I'm not aware of any project that has done that to the extent GFM did.

**Comment by chriskrycho** [comment]
It's also worth note that this implementation diverges substantially from most others in how it handles footnotes by default (#20, #142, etc.). In terms of an intuitive description of the behavior, footnotes should behave basically the same way that list items or blockquotes do: the presence of `[^<definition name>]: ` starts a new block-level item, and everything within it follows block-level item rules identically to those other block-level elements. (The same would go for definition lists and a number of other extensions if this library were to support those.)

Related to the question of *documenting* the footnote syntax (and its current divergence from other implementations) is the question of whether pulldown-cmark should standardize on the rules used in other implementations, which would require a breaking change *or* maintaining both options in perpetuity. There’s quite a lot of code out there which relies on the existing implementation—basically every user of Zola, for example—which makes a breaking change not especially appealing; but maintaining separate parse-and-render paths is *also* pretty unappealing.
