### ISSUE TITLE
Multiline HTML in a table breaks in an amusing way

### ISSUE THREAD

**Issue by kknives** [raphlinus/pulldown-cmark#536]
This seems like an edge case to me, but, when using a HTML tag inside a table, any newlines inside the tag attributes (or body) will cause the HTML to be escaped and the newlines are interpreted as new rows.

Most HTML tags are not used in this way, but the `<svg>` tag used for rendering math by Katex falls prey to this unfortunate edge case, as we encountered in lzanini/mdbook-katex#3

What was supposed to be:
![image](https://user-images.githubusercontent.com/57328978/121504687-d3ab6280-c9ff-11eb-9687-8a4228ca1936.png)
became:
![image](https://user-images.githubusercontent.com/57328978/121365767-9048e980-c956-11eb-8cda-c3a9490aa5a7.png)
---
I took a brief look at the code and my guess is that, when `TableParseMode::Active` is set, newlines are interpreted as new rows:
https://github.com/raphlinus/pulldown-cmark/blob/4d5094be11ec524e30acededc8ea097ad95267e8/src/firstpass.rs#L416-L420

Do correct me if my guess is wrong and we can work on this together :+1:

**Comment by Martin1887** [comment]
I fear that this is the correct GFM specification, it allows rows with fewer cells (fill missing with empty cells) or more cells (ignoring the excess): https://github.github.com/gfm/#example-204. I have tried this rule inside a HTML block and the same happens, so pulldown-cmark is following the GFM specification and this is not a bug but a feature :laughing: (weird GFM behaviour).

This behaviour is shown below.

The Markdown text

```
| abc | def |
| --- | --- |
| <span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.714em;vertical-align:0em;"></span><span class="mord accent"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.714em;"><span style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord mathnormal">a</span></span><span style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="accent-body" style="left:-0.2355em;"><span class="overlay" style="height:0.714em;width:0.471em;"><svg width='0.471em' height='0.714em' style='width:0.471em' viewBox='0 0 471 714' preserveAspectRatio='xMinYMin'><path d='M377 20c0-5.333 1.833-10 5.5-14S391 0 397 0c4.667 0 8.667 1.667 12 5
3.333 2.667 6.667 9 10 19 6.667 24.667 20.333 43.667 41 57 7.333 4.667 11
10.667 11 18 0 6-1 10-3 12s-6.667 5-14 9c-28.667 14.667-53.667 35.667-75 63
-1.333 1.333-3.167 3.5-5.5 6.5s-4 4.833-5 5.5c-1 .667-2.5 1.333-4.5 2s-4.333 1
-7 1c-4.667 0-9.167-1.833-13.5-5.5S337 184 337 178c0-12.667 15.667-32.333 47-59
H213l-171-1c-8.667-6-13-12.333-13-19 0-4.667 4.333-11.333 13-20h359
c-16-25.333-24-45-24-59z'/></svg></span></span></span></span></span></span></span></span></span></span> |
| bar | baz | boo |
```

is rendered by GitHub as:

| abc | def |
| --- | --- |
| <span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.714em;vertical-align:0em;"></span><span class="mord accent"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.714em;"><span style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord mathnormal">a</span></span><span style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="accent-body" style="left:-0.2355em;"><span class="overlay" style="height:0.714em;width:0.471em;"><svg width='0.471em' height='0.714em' style='width:0.471em' viewBox='0 0 471 714' preserveAspectRatio='xMinYMin'><path d='M377 20c0-5.333 1.833-10 5.5-14S391 0 397 0c4.667 0 8.667 1.667 12 5
3.333 2.667 6.667 9 10 19 6.667 24.667 20.333 43.667 41 57 7.333 4.667 11
10.667 11 18 0 6-1 10-3 12s-6.667 5-14 9c-28.667 14.667-53.667 35.667-75 63
-1.333 1.333-3.167 3.5-5.5 6.5s-4 4.833-5 5.5c-1 .667-2.5 1.333-4.5 2s-4.333 1
-7 1c-4.667 0-9.167-1.833-13.5-5.5S337 184 337 178c0-12.667 15.667-32.333 47-59
H213l-171-1c-8.667-6-13-12.333-13-19 0-4.667 4.333-11.333 13-20h359
c-16-25.333-24-45-24-59z'/></svg></span></span></span></span></span></span></span></span></span></span> |
| bar | baz | boo |

I'm glad at least you have fixed it removing the line breaks.
