### ISSUE TITLE
Capability to extract metadata into a struct

### ISSUE THREAD

**Issue by EstebanBorai** [raphlinus/pulldown-cmark#539]
Markdown metadata is usually written as:

```
---
title: How to cook pancakes
author: A Good Chef
keywords: breakfast, pancakes, cook, chef
---
```

On the top of the file, it would be great to be able to gather this into a user defined `struct` such as:

```
struct Metadata {
    title: String,
    author: String,
    keywords: Vec<String>,
}
```

**Comment by marcusklaas** [comment]
I completely understand the need for this functionality, as it is commonly used in many markdown files, but I do believe that parsing these metadata blocks are not in the scope of this project as they are not markdown themselves.

It shouldn't be hard to write a complete file parser by having some other small piece of code parse the metadata block, and then calling into pulldown to handle the actual markdown that follows.

Sorry to disappoint, but I hope that this at least makes sense :-)

**Comment by EstebanBorai** [comment]
Thanks for the quick response @marcusklaas!
