### ISSUE TITLE
Tasklists break when loose

### ISSUE THREAD

**Issue by not-my-profile** [raphlinus/pulldown-cmark#557]
For tight lists the output is as expected:

```html
$ printf '* [ ] bar\n* [ ] foo' | cargo run -- --enable-tasklists
<ul>
<li><input disabled="" type="checkbox"/>
bar</li>
<li><input disabled="" type="checkbox"/>
foo</li>
</ul>
```

For loose lists the checkboxes are however outside of the paragraph tags:
```html
printf '* [ ] bar\n\n* [ ] foo' | cargo run -- --enable-tasklists
<ul>
<li><input disabled="" type="checkbox"/>
<p>bar</p>
</li>
<li><input disabled="" type="checkbox"/>
<p>foo</p>
</li>
</ul>
```

While the [GFM spec unfortunately again lacks a respective test case](https://github.github.com/gfm/#task-list-items-extension-), I'd argue that it's quite obviously incorrect because the HTML ends up getting rendered as:

![image](https://user-images.githubusercontent.com/73739153/148178153-c3d7fb2b-c8ad-47db-b0a8-c203955efb6a.png)

As opposed to what GitHub is doing:

* [ ] bar

* [ ] foo

**Comment by marcusklaas** [comment]
You are right, that does look a little funky in pulldown.. I will investigate. Thanks for reporting this!

**Comment by marcusklaas** [comment]
* [ ] foo

* [ ] bar

**Comment by marcusklaas** [comment]
Aah, I think I see what may be going on. It looks like we add the checkbox to the list item directly, and not to the paragraph within the list item?

**Comment by not-my-profile** [comment]
Yes exactly.
