### ISSUE TITLE
Mixed nested unordered list types no longer work

### ISSUE THREAD

**Issue by ehuss** [raphlinus/pulldown-cmark#567]
The following list type no longer seems to render correctly:

```md
* foo
    + bar
    + baz
```

In 0.9.0 renders as:

```
<ul>
<li>foo
+ bar
+ baz</li>
</ul>
```

In 0.8.0 it was:

```
<ul>
<li>foo
<ul>
<li>bar</li>
<li>baz</li>
</ul>
</li>
</ul>
```

This seems to be caused by #554.

**Comment by marcusklaas** [comment]
Oof, this is not good. I will look into this shortly.

**Comment by marcusklaas** [comment]
Okay, found the problem. The PR you linked uncovered this bug, but didn't cause it. We checked for unordered list by inspecting the list marker. We compared it co `*` and `-`, but forgot about `+` lists! So luckily this had an easy fix :-)
