### ISSUE TITLE
is it possible to add a tag variant which renders to `div` element with custom classes?

### ISSUE THREAD

**Issue by Turmiht** [raphlinus/pulldown-cmark#568]
I'm not sure whether there's already a way to create an `div` in rendered html. In case it does not exist, I expect a tag variant like `Tag::Div(CowStr<'a>)` which will be created not by parser but only manually by caller code. I need it when trying to scan headers and generate table of content. I think `div` the best container for generated nested list of link in this case. I'm happy to implement it if possible.

**Comment by marcusklaas** [comment]
There's not a `Div` tag yet, but there's something more general: an HTML tag! In this you could pop any HTML tag, including `div`s :-)

Let me know if this works for you!

**Comment by Turmiht** [comment]
Wow, I'll just try it. thx! 😆

**Comment by marcusklaas** [comment]
Perfect! 👍🏽 

I'll close your issue then. Let us know if you run anything else :-)
