### ISSUE TITLE
Option::unwrap panic in parser when `ENABLE_HEADING_ATTRIBUTES` is set

### ISSUE THREAD

**Issue by 5225225** [raphlinus/pulldown-cmark#571]
I have come bearing gifts. (When looking up the spelling of that, I just learned the phrase was about the trojan horse. Neat.)

But inside of the horse is a fuzzer panic.

```rust
#[test]
fn test_bad_heading_attribute() {
    let mut opts = pulldown_cmark::Options::empty();

    opts.insert(Options::ENABLE_HEADING_ATTRIBUTES);

    let data = "[[][({][}\n-";

    for _ in pulldown_cmark::Parser::new_ext(data, opts) {};
}
```

This took a whole 10k seconds of CPU time, or 2 hours of wall clock time to find. So we are definitely making progress!

**Comment by 5225225** [comment]
(This was fuzzed directly against the #564 PR, commit 209b248)

**Comment by marcusklaas** [comment]
This should be fixed by that PR now as well. I have since fuzzed myself for a few hours, and found nothing!

**Comment by 5225225** [comment]
Cool! Probably best to get that PR in sooner than later, there may be more bugs, but long running PRs are no fun, personally.

Your call, but I tend to avoid em.

**Comment by marcusklaas** [comment]
I am in agreement with you. I will ask Raph Levien if he has time to review when he has time.

**Comment by marcusklaas** [comment]
Merged! Thanks again for helping us get started with fuzzing :)

If you find any more, please do send em to us!
