### ISSUE TITLE
Backslash escaped characters do not include the backslash in the range

### ISSUE THREAD

**Issue by dsherret** [raphlinus/pulldown-cmark#572]
For example, for the following text:

```
\\\\\\* asdasd
\ttesting

\\\\\\* asdasd
```

**Expected**

```
Some((Start(Paragraph), 0..25))
Some((Text(Borrowed("\\")), 0..2)) // note
Some((Text(Borrowed("\\")), 2..4)) // note
Some((Text(Borrowed("\\")), 4..6)) // note
Some((Text(Borrowed("*")), 6..7))
Some((Text(Borrowed(" asdasd")), 7..14))
Some((SoftBreak, 14..15))
Some((Text(Borrowed("\\ttesting")), 15..24))
Some((End(Paragraph), 0..25))
Some((Start(Paragraph), 26..41))
Some((Text(Borrowed("\\")), 27..28)) // note
Some((Text(Borrowed("\\")), 28..30)) // note
Some((Text(Borrowed("\\")), 30..32)) // note
Some((Text(Borrowed("*")), 32..33))
Some((Text(Borrowed(" asdasd")), 33..40))
Some((End(Paragraph), 26..41))
None
```

**Actual**

```
Some((Start(Paragraph), 0..25))
Some((Text(Borrowed("\\")), 1..2)) // note
Some((Text(Borrowed("\\")), 3..4)) // note
Some((Text(Borrowed("\\")), 5..6)) // note
Some((Text(Borrowed("*")), 6..7))
Some((Text(Borrowed(" asdasd")), 7..14))
Some((SoftBreak, 14..15))
Some((Text(Borrowed("\\ttesting")), 15..24))
Some((End(Paragraph), 0..25))
Some((Start(Paragraph), 26..41))
Some((Text(Borrowed("\\")), 27..28)) // note
Some((Text(Borrowed("\\")), 29..30)) // note
Some((Text(Borrowed("\\")), 31..32)) // note
Some((Text(Borrowed("*")), 32..33))
Some((Text(Borrowed(" asdasd")), 33..40))
Some((End(Paragraph), 26..41))
None
```

**Comment by raphlinus** [comment]
I'm not sure this is wrong? The range covers the actual text in the source file. The backslash is a control character, and we don't make any guarantee that's covered in the range (though it will be covered in the element that encloses it). Obviously we're not working from a spec here which dictates the correct behavior, but I think a case can be made that the current state is reasonable.

**Comment by dsherret** [comment]
@raphlinus it includes it for `\t` but not `\\`, so I think it should at least be made consistent? I think it would make sense for the range of the first backslash character to be from byte position `0..2` and not halfway in the character from byte position `1..2`

**Comment by raphlinus** [comment]
This still seems consistent to me. In the case of `\ttesting` the backslash is part of the text, so it makes sense for the range to include it.

**Comment by dsherret** [comment]
If I take this range of `1..2` and evaluate it against the raw text, it won't give me the text that was used to produce that event. For other events I can reference back the original text to know, but not with this text event since it occurs in the middle of the range that produced it. The `0..2` range is more correct IMO, but anyway, this is not a big deal for me because I have adjusted my code to handle it.

**Comment by dsherret** [comment]
Ah, I just took at the commonmark spec and see that `\\` is similar to `\*` or `\#` and see that the ranges for `\*` do not include the leading `\`. So yes, that's consistent. https://spec.commonmark.org/0.30/#backslash-escapes

That said, I still think the proper range would include the backslash because that's the range of the text that produces that event. But again, feel free to close.

**Comment by raphlinus** [comment]
I think I'll close this, but it's something we could reconsider, if there is a consensus that the range should be interpreted as "these are the source characters that were responsible for producing the element," a reasonable interpretation. For the most part (entities are the only exception), text elements map to actual characters in the source, and that's what we've chosen to expose. If we change it, we're at risk of breaking clients.

In any case, thanks for bringing it up!

**Comment by marcusklaas** [comment]
Apart from the issue of interpretation, it would currently not be feasible to implement this currently. For text elements we don't make a distinction between "what the text is" and "where the text came from". It is literally just a slice into the original string.
