### ISSUE TITLE
Tasklist item is treated as broken link

### ISSUE THREAD

**Issue by frondeus** [raphlinus/pulldown-cmark#575]
I was debugging https://github.com/Michael-F-Bryan/mdbook-linkcheck/issues/45, and I noticed that even with `Options::ENABLE_TASKLISTS`, the `pulldown-cmark::Parser` still calls `broken_link_callback` on every tasklist item.

For example:
```markdown
- [X] This is tasklist
```

The callback would be called for broken link `X` with link type `Shortcut`.

Minimal (not) working example:
https://github.com/frondeus/linkcheck/blob/frondeus/tasklists/src/scanners/markdown.rs#L54-L94

The panic is raised:
```
---- scanners::markdown::tests::detect_common_links_in_markdown stdout ----
thread 'scanners::markdown::tests::detect_common_links_in_markdown' panicked at 'Found broken link: 132..135, Shortcut, "X"', src/scanners/markdown.rs:85:17
```

**Comment by marcusklaas** [comment]
Uh-oh, that doesn't sound right. I will investigate this one.

**Comment by marcusklaas** [comment]
I'm having some trouble reproducing this. Reduced the test case to the following, which seems to pass:
```rust
    #[test]
    fn broken_link_on_tasklists() {
        let src = r#"
# Some Heading

[this](https://example.com) is a link [to nowhere][nowhere]. But
[this](../README.md) points somewhere on disk.

- [X] Tasklist

![Look, an image!](https://imgur.com/gallery/f28OkrB)

[nowhere]: https://dev.null/
        "#;

        let _ = Parser::new_with_broken_link_callback(
            src,
            Options::ENABLE_TASKLISTS,
            Some(&mut |BrokenLink {
                           span,
                           link_type,
                           reference,
                       }| {
                panic!(
                    "Found broken link: {:?}, {:?}, {:?}",
                    span, link_type, reference
                )
            }),
        )
        .count();
    }
```
But maybe I made a mistake extracting it?

**Comment by marcusklaas** [comment]
Ooh, I think I see what was going on. In the example you linked, the options passed were `Options::ENABLE_FOOTNOTES & Options::ENABLE_TASKLISTS`. I think that doesn't do what you may expect it to. To enable both of them, you'd have to "OR" the options together like this: `Options::ENABLE_FOOTNOTES | Options::ENABLE_TASKLISTS`
