### ISSUE TITLE
Getting link title

### ISSUE THREAD

**Issue by maxwell8888** [raphlinus/pulldown-cmark#576]
I was expecting a link of the form `[Link Title](linkurl.com)` to return the string `"Link Title"` from the `title` field of `pulldown_cmark::Tag::Link`. However, instead only the `destination` field is populated, and `title` is empty, and the title actually needs to be retrieved from a `Text` event, as demonstrated below. Is this the intended behaviour? If so, in what circumstances will the `title` field be populated? I can't find any mention of this in the docs.
```rust
use pulldown_cmark::{html, Options, Parser};

pub fn main() {
    let markdown_input = "[Link Title](linkurl.com)";
    let mut options = Options::empty();
    let parser = Parser::new_ext(markdown_input, options);

    for event in parser {
        match event {
            pulldown_cmark::Event::Start(tag) => match tag {
                pulldown_cmark::Tag::Link(link_type, destination, title) => {
                    println!("start. title: {}, destination: {}, link_type: {:?}", title, destination, link_type);
                }

                _ => (),
            },
            pulldown_cmark::Event::End(tag) => match tag {
                pulldown_cmark::Tag::Link(link_type, destination, title) => {
                    println!(
                        "end. title: {}, destination: {}, link_type: {:?}",
                        title, destination, link_type
                    );
                }
                _ => (),
            },
            pulldown_cmark::Event::Text(text) => {
                println!("text: {}", text);
            }

            _ => (),
        };
    }
}
```
produces:
```bash
start. title: , destination: linkurl.com, link_type: Inline
text: Link Title
end. title: , destination: linkurl.com, link_type: Inline
```

**Comment by ehuss** [comment]
[Link titles](https://spec.commonmark.org/0.30/#link-title) are the things in quotes, like `[link](/uri "title")`.  The text between the brackets can't be returned as a bare string because they may include arbitrary inline elements.

**Comment by maxwell8888** [comment]
Ah ok, sorry I should have checked the markdown lingo. Thanks for your response.
