### ISSUE TITLE
Question on extending markdown syntax

### ISSUE THREAD

**Issue by ToferC** [raphlinus/pulldown-cmark#578]
First - thank you for the amazing work.

I'm working on an app to natively host organizational documents as data which would be rendered through markdown. One of the elements needed is the ability to redact text for privacy or security reasons.

This would effectively be an alternative version of strikethrough that fully blacks-out the text with a reference to the rationale for redaction. E.g.:

`The following text is ~~redacted~~[13.1]`

Which would render as:

`The following text is ■■■■■■■■[link to legislation]`

I'm already using pulldown-cmark for rendering and I understand how I could fork the repo to add this fuctionality.

I was wondering about the best way to *extend* the crate's functionality and whether this was something you'd previously considered.

Thanks in advance and keep up the great work!

**Comment by marcusklaas** [comment]
I don't think you'd have to extend or fork pulldown to do this. Instead, you could enable the strikethrough option, and then catch those events and do your magic on them (doing a little parsing to get the link reference).

You could also accomplish this by forking pulldown and doing the parsing in-library of course, to make the event stream a bit cleaner, but I think this would be significantly more difficult as you'd have to familiarize yourself with some of the project internals. For your purpose I wouldn't recommend this.

It does sound like a rather specific application and syntax, so I don't think it makes sense to include it as part of the library for now.

Hope this helps!

**Comment by ToferC** [comment]
Thanks so much. I couldn't figure out how to catch the events and transform the markdown, so I ended up building a regex replace function that grabs the text before it goes to markdown. Is there an example of how to do this I could check out? Thank you!
