### ISSUE TITLE
InlineStr stores length inside string buffer

### ISSUE THREAD

**Issue by Shadlock0133** [raphlinus/pulldown-cmark#581]
While not really a problem, it's weird to me to store length of a string inside the string buffer itself, especially without any comments about it in the code.

It shouldn't break anything to make it a separate field in struct (and decrease `MAX_INLINE_STR_LEN` by one), and it would make it more readable/obvious what it is doing.

```rust
const MAX_INLINE_STR_LEN: usize = 3 * std::mem::size_of::<isize>() - 2;

pub struct InlineStr {
    inner: [u8; MAX_INLINE_STR_LEN],
    len: u8,
}
```

If, for some reason, it's not possible, I suggest at least putting a comment explaining the behaviour and reasoning.

Code change would be what's in playground here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=267627926e4a7d246e4b4e3ecb10483d and changing https://github.com/raphlinus/pulldown-cmark/blob/ea1b4cd4dbcf912129f14dd81ad4809f0d5d1999/src/strings.rs#L278-L280 to

```rust
// we need 4 bytes to store a char
assert!(MAX_INLINE_STR_LEN >= 4);
```

**Comment by marcusklaas** [comment]
Totally agreed that this is a wart, and your solution looks much better.

I would be most happy to merge any pull request implementing your suggested changes!
