### ISSUE TITLE
Support for audio and video media types

### ISSUE THREAD

**Issue by JShorthouse** [raphlinus/pulldown-cmark#584]
It would be nice if this library had an option to enable html embedding of audio and video.

As an example, pandoc already supports this using the image embed syntax.

Example file:

```markdown
![](image.png)

![](video.mp4)

![](audio.wav)
```
Pandoc:

```html
$ pandoc test.md --to html5
<p><img src="image.png" /></p>
<p><video src="video.mp4" controls=""><a
href="video.mp4">Video</a></video></p>
<p><audio src="audio.wav" controls=""><a
href="audio.wav">Audio</a></audio></p>
```

Currently, for the same input, pulldown-cmark outputs:

```html
<p><img src="image.png" alt="" /></p>
<p><img src="video.mp4" alt="" /></p>
<p><img src="audio.wav" alt="" /></p>
```

---

For anyone else with this issue: as workaround for now, you can just put `<video>` tags directly in the markdown, and pulldown-cmark will leave them there in the generated html.

**Comment by ultrasaurus** [comment]
I have a similar use case, but the workaround doesn't work for me.  I'm working on a static site generator and want the user to be able to write pure markdown, but then generate a/v players in the HTML when there are a/v links -- where linking to a file vs. inline playback could be disambiguated with the text of the link (or lack thereof, like pandoc).

I would like a way to override the writing of specific tags, maybe extending `HtmlWriter` in some way.  This could allow people to address issues like https://github.com/raphlinus/pulldown-cmark/issues/524, https://github.com/raphlinus/pulldown-cmark/pull/628, and maybe implement some CommonMark extensions (that are consistent with standard CommonMark syntax) without changes to the core code.

**Comment by ppearson** [comment]
JFYI: I've hacked around this use-case by manually filtering the events after parsing, and replacing Event::Start(Tag::Image)  with raw html depending on the filename of the image URL with a Event::Html (and dropping the corresponding Event::End as well), .

It's slightly annoying and hacky, but works for my purposes.

**Comment by ultrasaurus** [comment]
Now there are two PRs with two different approaches to addressing issue.  Interested in what people think!

**Comment by Martin1887** [comment]
Pull requests will be reviewed soon, but this is probably out of scope of this project and should be implemented in another crate.

**Comment by bobhy** [comment]
test task list
+ [ ] ddd
+ [x] ooo
