### ISSUE TITLE
Support for a C API?

### ISSUE THREAD

**Issue by gjtorikian** [raphlinus/pulldown-cmark#585]
Hi! I maintain Commonmarker, the Ruby bindings to the Commonmark C lib. For [a few years now](https://github.com/gjtorikian/commonmarker/issues/107 ) I’ve wanted to move off of the C lib and onto a Rust-generated dylib. 

Would you support a PR that exposed a C entry point (eg. `crate-type = ["staticlib", "cdylib", "rlib"]`) and a header, so that other FFIs can bind to this library?

**Comment by marcusklaas** [comment]
That seems like a great idea to me!
