### ISSUE TITLE
didn't match spec 0.30

### ISSUE THREAD

**Issue by CliffHan** [raphlinus/pulldown-cmark#600]
refer to this https://spec.commonmark.org/0.30/#example-152

In this example, first line is unclosed, and output should be the same.
But when I used pulldown-cmark via zola, looks like it output with html tags closed.

**Comment by CliffHan** [comment]
my original text looks like this:

```
<p class="text-center"><small>

[link](http://some_link)

</small></p>
```

and it outputs:

```
<p class="text-center"><small></small></p>
<p><small><a href="http://some_link">link</a></small></p>
<small></small>
<p><small></small></p>
<p></p>
```

Maybe my understanding is wrong? Not very sure about this.

**Comment by CliffHan** [comment]
looks like only one unclosed tag works good:

```
<div align="center">

![](some_image)

</div>
```

outputs

```
<div align="center">
<p><img src="some_image" alt=""></p>
</div>
```

**Comment by raphlinus** [comment]
This is a messy case. With this input on the commandline:

```markdown
<p class="text-center"><small>

[link](http://some_link)

</small></p>
```

I get:

```html
<p class="text-center"><small>
<p><a href="http://some_link">link</a></p>
<p></small></p></p>
```

This is not valid HTML, as there is a nesting error. However, it is the same result as the [commonmark demo](https://spec.commonmark.org/dingus/).

When the input doesn't have extra blank lines the result is more reasonable. I haven't read the spec carefully to analyze exactly where the fault lies, but it looks like it's not our implementation.

**Comment by wooorm** [comment]
it's according to spec. Not an issue with pulldown

**Comment by CliffHan** [comment]
thanks for your explanation
