### ISSUE TITLE
How to get the original line number?

### ISSUE THREAD

**Issue by boan-anbo** [raphlinus/pulldown-cmark#605]
Hi there, I am using cmark to convert Markdown to another structured format, but I need the original line number of a tag. For example
```
""
"# Heading "
""
"- Bullet point"
```
Suppose the first line is 0. I need the information of line `1` for tag Heading. And line `3` for the bullet point.

It seems empty line does not emit any event, the first event will be the start tag of the heading. 

Perhaps I missed something, and thanks in advance!

**Comment by marcusklaas** [comment]
If I understand correctly, you could try the following:
1. build an ordered list of line start positions in the markdown document
2. take the range of a tag event, and look up the opening position of that range in the list from point 1 using binary search
3. the index of the greatest line start that is lesser than your tag opening position will be your line number

**Comment by boan-anbo** [comment]
Thanks so much @marcusklaas !

For those who didn't see it on the documentation, use `into_offset_iter()` to get both `Event` and `Range`
