### ISSUE TITLE
[Feature Request] Allow custom HTML attributes to be inserted from within markdown content

### ISSUE THREAD

**Issue by Animeshz** [raphlinus/pulldown-cmark#606]
Jekyll's markdown engine supports [this kind of syntax](https://digitaldrummerj.me/styling-jekyll-markdown/) to cope up for inline styling of the text and other stuffs at the end of the html export.

It'd be a lot easier to make content in markdown while formatting them for example to be quote / tip, while still being readable (no html).

**Comment by Martin1887** [comment]
Sorry but this kind of extensions are out of the scope of this project. In the long term, it would be great to have a plugin system to be able to add these types of rules in other crates.
