### ISSUE TITLE
help with repo

### ISSUE THREAD

**Issue by yankeeinlondon** [raphlinus/pulldown-cmark#612]
@marcusklaas dropped you an email but if you'd like someone to help process through some of the PR's and issues I'd be willing to do that. I'd really want your help in review to start as my Rust skills are still developing. 

Also, if others are willing to join a small group to help maybe you could express your interest here? 

I think this repo is a fantastic contribution to open source and i'd love to see people attempts to contribute via PRs especially be brought into the fold and keep this repo smelling of roses. :)

**Comment by raphlinus** [comment]
I'm definitely in favor of someone with time and motivation helping out, and it's a great way to grow those skills. Maybe a brief video chat to go over expectations, then we can make give you permissions. If Marcus is available, we can both participate.

A few overall words about the direction of the repo. We get a pretty steady stream of issues and PRs that in one way or another expand the scope. Very often nonstandard extensions (which I'm resistant to as a matter of principle, as I feel the Markdown world is fragmented enough), but also more types of processing and rendering for a particular application. Personally, I *like* the idea that the scope of this crate is limited. We definitely prioritize the use in rustdoc, and they're a good downstream - surfacing actual bugs and improvements.

Other things, like documentation improvements, are much more fine, and there it's mostly having bandwidth to review, etc.

That said, we could probably be better about communicating, as letting a PR sit unanswered is not a great experience. Having someone to do first line of review, and escalate things that might require more thought, would be great, and it sounds to me like you're signing up for that.

**Comment by yankeeinlondon** [comment]
Sounds great. I'm currently spending most of my time in Los Angeles so GMT-7 but I have a flexible schedule. Happy to setup a zoom/video call to discuss. My email is ken@ken.net if you want to send a meeting request.

**Comment by alerque** [comment]
I for one appreciate the limited scope and maintainers keeping this tool from growing into a monster. Possibly surfacing enough API that other projects could extend it with custom parsing could be considered, but I don't really want to see this library grow too complex. I only reach for it when I know I'm dealing with strict common mark. I have plenty of other Markdown content too, but I tend to think expanding the scope of this project ta handle a million extensions like, say, Pandoc does would just bring more bugs and difficulty and degrade the overall usefulness this provides in speed and correctness.

**Comment by yankeeinlondon** [comment]
@alerque just to be clear ... I agree too ... focus is important. What I think is helpful fits into the following categories:

1. any and all **documentation** or **example** based PR's should receive quick review and acceptance if they meet quality standards
2. any **additional tests** that are added as a PR which help to explain functionality or extend confidence in **test coverage** should also receive expidited accepance as they only help to promote a shared and testable understanding of functionality for core.
3. fixes like the "checklist" bug that was reported, a PR created to fix it which initially passed all test but then aged without merging should be avoided ... this feels like an indicator of "busy people" not closing out a closable process or possibly a belief that the current tests aren't enough to simply merge a PR like this.
4. any feature requests that might extend scope should be immediately **tagged** as a `feature-request` to provide a visible distinguishing characteristic from an "issue" (which it is not). Then in a non-urgent manner these feature requests should be considered with an eye to rejecting more than accepting them ... also "acceptance" should be given mainly _only if_ the author of the suggested feature is willing to author the PR (with the goal of avoiding "nice ideas with no resource attached" rarely reach the finish line)

In general my goal is to just to add some additional bandwith to the team if that's helpful and I'm not pre-supposing that this comes at no cost in adding someone new which is why as a first step I think a Zoom call probably does serve as a good first step. 

> Note: beyond my genuine desire just to help I would love to have other's greater Rust skills (as well as knowledge of pulldown parsers) rub off on me as I am learning daily but don't consider myself an expert in this. I mention this just to be as much of an open book on my interests as I can be

**Comment by Martin1887** [comment]
I have just joined as a maintainer and any help would of course be appreciated.

If any of you also want to be a maintainer, you should talk to @raphlinus. Otherwise, pull requests and issues will be carefully reviewed (but that could take some time).

Thanks.
