### ISSUE TITLE
Parsing `FootnoteDefinition` is broken when definitions are not separated by a blank line

### ISSUE THREAD

**Issue by rhysd** [raphlinus/pulldown-cmark#618]
## Repro

Convert the following Markdown input to HTML with `--enable-footnotes` option.

```markdown
Here is a simple footnote[^1].

A footnote can also have footnote[^2].

[^1]: My reference 1.
[^2]: My reference 2.
```

## Expected behavior

```html
<p>Here is a simple footnote<sup class="footnote-reference"><a href="#1">1</a></sup>.</p>
<p>A footnote can also have footnote<sup class="footnote-reference"><a href="#2">2</a></sup>.</p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>My reference 1.</p>
</div>
<div class="footnote-definition" id="2"><sup class="footnote-definition-label">2</sup>
<p>My reference 2.</p>
</div>
```

## Actual behavior

```html
<p>Here is a simple footnote<sup class="footnote-reference"><a href="#1">1</a></sup>.</p>
<p>A footnote can also have footnote<sup class="footnote-reference"><a href="#2">2</a></sup>.</p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>My reference 1.
<sup class="footnote-reference"><a href="#2">2</a></sup>: My reference 2.</p>
</div>
```

Only 1 `FootnoteDefinition` event happened and `FootnoteReference` event incorrectly happened while parsing the footnote definition.

Events while parsing the above input are as follows:

```
0..31: Start(Paragraph)
0..25: Text(Borrowed("Here is a simple footnote"))
25..29: FootnoteReference(Borrowed("1"))
29..30: Text(Borrowed("."))
0..31: End(Paragraph)
32..71: Start(Paragraph)
32..65: Text(Borrowed("A footnote can also have footnote"))
65..69: FootnoteReference(Borrowed("2"))
69..70: Text(Borrowed("."))
32..71: End(Paragraph)
72..116: Start(FootnoteDefinition(Borrowed("1")))
78..116: Start(Paragraph)
78..93: Text(Borrowed("My reference 1."))
93..94: SoftBreak
94..98: FootnoteReference(Borrowed("2"))
98..115: Text(Borrowed(": My reference 2."))
78..116: End(Paragraph)
72..116: End(FootnoteDefinition(Borrowed("1")))
EOF
```

## Note

It seems that a parser assumes blank line to separate footnote definitions. When I added a blank line between `[^1]` and `[^2]`, two footnote definitions were correctly parsed.

```markdown
Here is a simple footnote[^1].

A footnote can also have footnote[^2].

[^1]: My reference 1.

[^2]: My reference 2.
```

---

I confirmed the input is rendered correctly on GitHub as follows:

Here is a simple footnote[^1].

It can also have another footnote[^2].

[^1]: My reference 1.
[^2]: My reference 2.

**Comment by rhysd** [comment]
I also noticed that parsing footnotes no longer works when non-blank line is before footnote definitions.

```markdown
Here is a simple footnote[^1].

A footnote can also have footnote[^2].

This line prevents parse parsing out footnote definitions
[^1]: My reference 1.
[^2]: My reference 2.
```

Events while parsing the above text are:

```
0..31: Start(Paragraph)
0..25: Text(Borrowed("Here is a simple footnote"))
25..29: FootnoteReference(Borrowed("1"))
29..30: Text(Borrowed("."))
0..31: End(Paragraph)
32..71: Start(Paragraph)
32..65: Text(Borrowed("A footnote can also have footnote"))
65..69: FootnoteReference(Borrowed("2"))
69..70: Text(Borrowed("."))
32..71: End(Paragraph)
72..174: Start(Paragraph)
72..129: Text(Borrowed("This line prevents parse parsing out footnote definitions"))
129..130: SoftBreak
130..134: FootnoteReference(Borrowed("1"))
134..151: Text(Borrowed(": My reference 1."))
151..152: SoftBreak
152..156: FootnoteReference(Borrowed("2"))
156..173: Text(Borrowed(": My reference 2."))
72..174: End(Paragraph)
EOF
```

**Comment by marcusklaas** [comment]
Thanks for your investigations here. I also saw your pull request. I think your approach is sound, but I am a bit hesitant to change the behaviour of pulldown here for two reasons:
1. this would be a fairly impactful breaking change; and
2. there (still) is no spec that we can actually follow.

Especially the latter concern I consider a blocker. Indeed, GitHub seems to [support footnotes] as of September 2021, but they have not added them to the [GFM spec]. While I agree that our current footnotes implementations is due for an overhaul, simply trying to replicate GitHub's parser without spec is not a great place to be in.

Note that there already a number of issues open for footnotes:
- https://github.com/raphlinus/pulldown-cmark/issues/20
- https://github.com/raphlinus/pulldown-cmark/issues/530
- https://github.com/raphlinus/pulldown-cmark/issues/464

There's even a WIP [pull request](https://github.com/raphlinus/pulldown-cmark/pull/544) that is making many of the requested changes. But again, without a spec to follow, it's not exactly clear which semantics should actually be implemented..

[support footnotes]: https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/
[GFM spec]: https://github.github.com/gfm/
