### ISSUE TITLE
Latex formulas parsing error

### ISSUE THREAD

**Issue by Jonas1312** [raphlinus/pulldown-cmark#630]
Hi,

Related issue for a software using pulldown-cmark: https://github.com/lycheeverse/lychee/issues/941

Seems like pulldown-cmark interprets the `(n)` inside  `$$[f * g](n)$$` as a relative path.

Thanks

**Comment by lebensterben** [comment]
I just tested it with [tree-sitter parser for markdown](https://github.com/ikatyang/tree-sitter-markdown) and it also interpret `$$[f * g](n)$$` as a link. 

You can try it here: https://ikatyang.github.io/tree-sitter-markdown/

---

BTW, even though GitHub supports inline math equation, `$$[f*g](n)$$` would look like

$$[f*g](n)$$

and what you want to achieve should be `$$[f*g]\(n\)$$`

$$[f*g]\(n\)$$

---

To be rendered correctly as LaTeX math equation, and meanwhile parsed correctly as Markdown, you need `$$\[f*g\]\(n\)$$`

$$\[f*g\]\(n\)$$

**Comment by Jonas1312** [comment]
Thanks for your comment @lebensterben ! I escaped the [] and (), and it works

I see some PR in this repository already for support of maths/latex equations, so I'll close this issue
