### ISSUE TITLE
FS link with space(s) in file-name fails to parse

### ISSUE THREAD

**Issue by hoijui** [raphlinus/pulldown-cmark#633]
While this successfully parses as a link:

```markdown
[link](doc/unspaced_name.md)
```

this does not:

```markdown
[link](doc/spaced name.md)
```

One can argue that all links should be URL encoded, even local file-system ones,
but given that Markdown is meant to be super easy to use for the average person,
that makes little sense to me.
I can also not remember having see this behavior in other parsers.

**Comment by wooorm** [comment]
That’s per the spec. Every CommonMark-compliant parser works that way. It’s the same here:

```markdown
[link](doc/spaced name.md)
```

[link](doc/spaced name.md)


Use an enclosed url if you want to allow more characters:

```
[link](<doc/spaced name.md>)
```

[link](<doc/spaced name.md>)

Or encode spaces (character references, or percent encoding)
