### ISSUE TITLE
Why are internal tabs converted to spaces in Code blocks?

### ISSUE THREAD

**Issue by critiqjo** [raphlinus/pulldown-cmark#64]
More specifically, why was [this match arm][code-tab] added? Removing that arm does not result in any additional spec test breakage, but it does make the [test 1](http://spec.commonmark.org/0.27/#example-1) fail with a better match with the expected output:

```
---input---
→foo→baz→→bim

---wanted---
<pre><code>foo→baz→→bim
</code></pre>


---got---
<pre><code>foo→baz→→bim</code></pre>

```

Compared to the original:

```
---input---
→foo→baz→→bim

---wanted---
<pre><code>foo→baz→→bim
</code></pre>


---got---
<pre><code>foo baz     bim</code></pre>

```

I found [the commit] which added this arm, but did not find any explanation why it was added.

[code-tab]: https://github.com/google/pulldown-cmark/blob/6641571/src/parse.rs#L703-L706
[the commit]: https://github.com/google/pulldown-cmark/commit/7e12774808f42a95f49f2dc2066dc31ca83828bd#diff-258c0555e6f9c4bc4fba3a551d81638aR512

**Comment by raphlinus** [comment]
Very simply because that was the spec at the time. Since then, they've changed the spec so that tabs are preserved, and the code hasn't been updated to follow.

**Comment by critiqjo** [comment]
After #63 was merged, removing that `match` arm improves the number of test cases passed from 562 to 565 (for v0.27). Shall I issue a PR?

**Comment by marcusklaas** [comment]
This has been fixed!
