### ISSUE TITLE
`"__!_!__"` parsed as strong

### ISSUE THREAD

**Issue by mgeisler** [raphlinus/pulldown-cmark#660]
Events from pulldown-cmark:

```rust
"__!_!__" -> [
  Start(Paragraph)
    Start(Strong)
      Text(Boxed("!_!"))
    End(Strong)
  End(Paragraph)
]
```

Events from commonmark.js:

```rust
"__!_!__" -> [
  Start(Paragraph)
    Text(Boxed("__!_!__"))
  End(Paragraph)
]
```

XML from [commonmark.js](https://spec.commonmark.org/dingus/?text=__%21_%21__):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <text>__</text>
    <text>!</text>
    <text>_</text>
    <text>!</text>
    <text>__</text>
  </paragraph>
</document>
```

I think the problem here is that `__` in `"__!` does not count as a [left-flanking delimiter-run](https://spec.commonmark.org/0.30/#left-flanking-delimiter-run) because neither 2a nor 2b are fulfilled:

- (2a) not followed by a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character), or 
- (2b) followed by a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character) and preceded by [Unicode whitespace](https://spec.commonmark.org/0.30/#unicode-whitespace) or a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character). For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.

Because `__` is not a left-flanking delimiter-run, it should not be parsed as strong emphasis.

**Comment by Martin1887** [comment]
Yes, it seems a commonmark.js bug and it has been confirmed by the Pandoc author, so this can be closed because the actual bug is open in commonmark.js.

Thanks!

**Comment by mgeisler** [comment]
> It is followed by a unicode punctuation character (`!`), and it is preceded by the beginning of the line (which is treated as whitespace).

Yeah, now that I read it again, I'm not sure why I said that (2b) doesn't apply. Thanks for filing the issue in commonmark.
