### ISSUE TITLE
HTML block loses initial indentation

### ISSUE THREAD

**Issue by mgeisler** [raphlinus/pulldown-cmark#662]
Events from pulldown-cmark:

```rust
"\n <foo>" -> [
  Html(Boxed("<foo>"))
]
```

Events from commonmark.js:

```rust
"\n <foo>" -> [
  Html(Boxed(" <foo>"))
]
```

XML from [commonmark.js](https://spec.commonmark.org/dingus/?text=%0A%20%3Cfoo%3E):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <html_block> &lt;foo&gt;</html_block>
</document>
```

The says that a [first line of a HTML block can start after three optional spaces](https://spec.commonmark.org/0.30/#html-blocks). I guess they're trimmed in pulldown-cmark?

**Comment by Martin1887** [comment]
This bug keeps happening after merging #704.
