### ISSUE TITLE
HTML has higher priority than block quotes

### ISSUE THREAD

**Issue by notriddle** [raphlinus/pulldown-cmark#674]
Found with modified differential fuzzer (please mark as a fuzzing output): https://github.com/raphlinus/pulldown-cmark/pull/673

Events from pulldown-cmark:

```rust
"<G\n>\n" -> [
  Start(Paragraph)
    Html(Boxed("<G\n>"))
  End(Paragraph)
]
```

Events from pandoc:

```rust
"<G\n>\n" -> [
  Start(Paragraph)
    Text(Boxed("<G"))
  End(Paragraph)
  Start(BlockQuote)
  End(BlockQuote)
]
```

Events from commonmark.js:

```rust
"<G\n>\n" -> [
  Start(Paragraph)
    Text(Boxed("<G"))
  End(Paragraph)
  Start(BlockQuote)
  End(BlockQuote)
]
```

AST from [pandoc](https://pandoc.org/try/?params=%7B%22text%22%3A%22%3CG%5Cn%3E%5Cn%22%2C%22to%22%3A%22json%22%2C%22from%22%3A%22commonmark%22%7D):

```text
Pandoc {
    meta: {},
    blocks: [
        Para(
            [
                Str(
                    "<G",
                ),
            ],
        ),
        BlockQuote(
            [],
        ),
    ],
}
```

**Comment by Martin1887** [comment]
I understand the issue here is that only HTML blocks should have higher priority than block quotes meanwhile inline HTML should have less priority, right?
