### ISSUE TITLE
Metadata extraction fails on 4-space-or-more indented content

### ISSUE THREAD

**Issue by chriskrycho** [raphlinus/pulldown-cmark#689]
I'm working with the latest version on `master`, and found that you can blow up the first pass parse time (to a degree where I haven't seen it stop!) with any content indented by four spaces or more:

```markdown
---
anything:
    indented4Spaces: true
---
```

Configuration:

```rust
let mut options = Options::all();
```

(I imagine this is possible to trigger by *just* enabling the `ENABLE_YAML_STYLE_METADATA_BLOCKS` option, but haven't checked yet.)

This goes for *any* time something is indented that far in the metadata block, including nested keys like this:

```markdown
---
something:
  nested:
    twice: true
---
```

Or lists:

```markdown
---
lists:
    - indented 4 spaces
---
```

**Comment by Martin1887** [comment]
Thanks, it was an important bug. It has been fixed in #690.
