### ISSUE TITLE
Convert from `Tag` to `TagEnd`

### ISSUE THREAD

**Issue by rambip** [raphlinus/pulldown-cmark#696]
I use a fork following the unreleased version of the main branch (https://github.com/rhysd/pulldown-cmark/tree/math)

In my project, I'm creating my own rendering pipeline from the events `Parse` created.
To get the children attributes when I match an opening tag, I would like to do something like this:

```rust
fn render_tag<'a>(context: &RenderContext, stream: &mut EventStream<'a>, tag: Tag<'a>) -> Result<Html, HtmlError> {
    let children = 
        stream
        .take_while(|(event, range)| event != Event::Start(corresponding_closing_tag(tag))
        .collect();

    match tag {
        Tag::Paragraph => todo!(),
        Tag::Heading(_, _, _) => todo!(),
        Tag::BlockQuote => todo!(),
        Tag::CodeBlock(_) => todo!(),
        Tag::List(_) => todo!(),
        Tag::Item => todo!(),
        Tag::FootnoteDefinition(_) => todo!(),
        Tag::Table(_) => todo!(),
        Tag::TableHead => todo!(),
        Tag::TableRow => todo!(),
        Tag::TableCell => todo!(),
        Tag::Emphasis => todo!(),
        Tag::Strong => todo!(),
        Tag::Strikethrough => todo!(),
        Tag::Link(_, _, _) => todo!(),
        Tag::Image(_, _, _) => todo!(),
    }
}
```

But it seems there is no way to turn an opening tag into a closing tag, or at leat test if a `Tag` and a `TagEnd` match.
Am I missing something ?

**Comment by Martin1887** [comment]
Hello.

Pulldown-cmark is a pull parser, so future tags are not known until they are parsed. If I have understood it correctly, to achieve something like you want I think you would have to use a recursive function each time you read an open tag, with the corresponding closing tag as as the base case.

Note that a recursive function is needed because other open-close tags of the same type could be inside the first one.

To get the corresponding end tag, you could create a simple function with a `match` expression.

Regards.

**Comment by rambip** [comment]
I think I was not really clear in my original post.
I just wanted to say that testing if an `Event` is the corresponding closing tag of a `Event::Start(tag)` is probably something a lot of the users of the library will want to do.
In addition, pattern matching has a cost, while if the discriminants of `Tag` and `TagEnd` events matched, you could just compare them to check if it is the corresponding closing tag.

**Comment by rambip** [comment]
If you make sure the variants are defined in the same order, you could check for the correspondance with `start_tag as u32 == end_tag as u32 `.
This would be an efficient way to test if a closing tag corresponds to an opening tag, but it should be documented
If there were a small sentance in the  docs of `TagEnd` that said "you can check if an opening tag matches a closing tag with `start_tag as u32 == end_tag as u32`", I would be happy
Hope it is more clear now.

**Comment by Martin1887** [comment]
OK, I thought you talked about the whole process because a `match` expression seems an easy solution, but I had not taken into account the performance cost.

They were already in the same order, but #698 have added a doc comment in both enums.

Thanks!

**Comment by rambip** [comment]
Hum, turns out I was wrong !

You can cast an enum variant only if it has no fields, see [here](https://doc.rust-lang.org/reference/items/enumerations.html#casting)

So the documentation I asked you to add is wrong, sorry

**Comment by rambip** [comment]
For reference, see [discriminant](https://doc.rust-lang.org/std/mem/fn.discriminant.html) and the [rust reference](https://doc.rust-lang.org/reference/type-layout.html#primitive-representations)

**Comment by Martin1887** [comment]
OK, now I read it I have recalled reading it in the Rust book.

#707 removes the wrong comments.

**Comment by vidhanio** [comment]
> OK, now I read it I have recalled reading it in the Rust book.
> 
> #707 removes the wrong comments.

have you considered adding a third type, something like `TagKind`? then both `Tag` and `TagEnd` could have a `.kind()` method and those could be compared.

**Comment by rambip** [comment]
> > OK, now I read it I have recalled reading it in the Rust book.
> > #707 removes the wrong comments.
> 
> have you considered adding a third type, something like `TagKind`? then both `Tag` and `TagEnd` could have a `.kind()` method and those could be compared.

It really seems like an elegant solution, but I feel like `TagKind` is just `TagEnd` (the enum variant + the minimum information required, like the level of heading)
So converting from `Tag` to `TagKind` ... is just converting from `Tag` to `TagEnd` !
But I agree that `TagEnd` should be named `TagKind`

**Comment by vidhanio** [comment]
> > > OK, now I read it I have recalled reading it in the Rust book.
> 
> > > #707 removes the wrong comments.
> 
> > 
> 
> > have you considered adding a third type, something like `TagKind`? then both `Tag` and `TagEnd` could have a `.kind()` method and those could be compared.
> 
> 
> 
> It really seems like an elegant solution, but I feel like `TagKind` is just `TagEnd` (the enum variant + the minimum information required, like the level of heading)
> 
> So converting from `Tag` to `TagKind` ... is just converting from `Tag` to `TagEnd` !
> 
> But I agree that `TagEnd` should be named `TagKind`

maybe the best solution would be to add a `.end_kind()` method to Tag that just returns the corresponding end tag?

**Comment by rambip** [comment]
Maybe the best place to continue is #706 then
