### ISSUE TITLE
Automatically add id to headings

### ISSUE THREAD

**Issue by FedericoPonzi** [raphlinus/pulldown-cmark#700]
I know there is `options.insert(Options::ENABLE_HEADING_ATTRIBUTES);` but this would require to manually enter the ids. I would like generate a ToC and link the heading's ids. It would be nice to automatically add the heading's name as an id:

    ### Demo

would result in

    <h3 id="demo">Demo</h3>

**Comment by Martin1887** [comment]
Sorry, but this feature is out of the scope of this project. The renderer is a very basic feature to complement the parser.

This sort of things should be done in external crates that import pulldown-cmark. The creation of a renderer crate will be welcome.

Thanks.

**Comment by FedericoPonzi** [comment]
Thanks for the quick answer!
