### ISSUE TITLE
implementing PartialEq for `Tag` and `TagEnd`

### ISSUE THREAD

**Issue by rambip** [raphlinus/pulldown-cmark#706]
As I said in #696, the PR in #698 is wrong (and it's my fault)

You can't cast an enum as an `u32` if some of the variants have fields.
Doing that would require to know the memory layout, which is feasible (see https://doc.rust-lang.org/reference/type-layout.html#primitive-representations) but cumbersome and require unsafe.

That said, I still think the user should be able to compare a `Tag` and a `TagEnd` for a variety of reasons, like if it wants to get all the children events of a tag.

I think the following code will be written at least twice by the users of this crate:
```rust
pub fn as_closing_tag(t: &Tag) -> TagEnd {
    match t {
        Tag::Paragraph => TagEnd::Paragraph,
        Tag::Heading{level, ..} => TagEnd::Heading(*level),
        Tag::BlockQuote => TagEnd::BlockQuote,
        Tag::CodeBlock(_) => TagEnd::CodeBlock,
        Tag::List(b) => TagEnd::List(b.is_some()),
        Tag::Item => TagEnd::Item ,
        Tag::FootnoteDefinition(_) => TagEnd::FootnoteDefinition,
        Tag::Table(_) => TagEnd::Table,
        Tag::TableHead => TagEnd::TableHead ,
        Tag::TableRow => TagEnd::TableRow ,
        Tag::TableCell => TagEnd::TableCell ,
        Tag::Emphasis => TagEnd::Emphasis ,
        Tag::Strong => TagEnd::Strong ,
        Tag::Strikethrough => TagEnd::Strikethrough ,
        Tag::Link(_, _, _) => TagEnd::Link,
        Tag::Image(_, _, _) => TagEnd::Image,
        Tag::MetadataBlock(k) => TagEnd::MetadataBlock(*k),
    }
}
```

So I still think implementing `PartialEq<Tag> for TagEnd` and `PartialEq<TagEnd> for Tag` is a requirement.
```rust
impl PartialEq<TagEnd> for Tag {
    fn eq(&self, other: &TagEnd){
        other == &as_closing_tag(self)
    }
}
```

**Comment by Martin1887** [comment]
Renaming `TagEnd` into `TagKind` seems a good move because the end semantics are included in the event (`Event::End`).

However, the problem about converting `Tag` into `TagKind` keeps existing. Both, implementing `PartialEq` and adding a `.kind()` method are possible, but they would have to be implemented using a `match`.

**Comment by Martin1887** [comment]
The other option would be using `TagKind` in both events and adding a second parameter `TagData` to the `Event::Start` variant.

The problem of this approach is `TagData` would be basically the current `Tag` enum because data depends on the tag variant.

**Comment by rambip** [comment]
I think a match is fine
A benchmark could be interesting, though, but I think the compiler is smart enough to convert with few instructions

**Comment by raphlinus** [comment]
Implementing `PartialEq` between `Tag` and `TagEnd` doesn't feel right, as I think it breaks the transitive rule. As an example, two lists might not be equal, but both tags would be equal to the corresponding `TagEnd`.

I think it's worth fixing the problem, but I don't think `PartialEq` is the right way to do it. Having a `match` method that does the same but just has its own name seems fine, as does the conversion proposed in #696.

**Comment by rambip** [comment]
I agree
Feel free to close this issue and reopen the older one
