### ISSUE TITLE
Multi-line link not recognised in full, drops part on second line

### ISSUE THREAD

**Issue by keunes** [raphlinus/pulldown-cmark#709]
Hello,

For [AntennaPod](https://github.com/AntennaPod/AntennaPod) we're using the Lychee GitHub action to check for broken links on our website. We noticed that multiline links aren't processed correctly.

For example:
```text
[Google Play](https://play.google.com/store/apps/details?
id=de.danoeh.antennapod)
```
is recognised as https://play.google.com/store/apps/details. Because this URL as such is not valid, Lychee throws an error. I created the issue https://github.com/lycheeverse/lychee/issues/1245, where @mre pointed us here.

Copying their test results:

**Input**
```text
works: [](https://example.com)
broken: [](https://example.com?
id=foo)
```

**Output**
```text
"works: [](https://example.com)\nbroken: [](https://example.com?\nid=foo)\n" -> [
  Start(Paragraph)
    Text(Borrowed("works: "))
    Start(Link(Inline, Borrowed("https://example.com"), Borrowed("")))
    End(Link(Inline, Borrowed("https://example.com"), Borrowed("")))
    SoftBreak
    Text(Borrowed("broken: "))
    Text(Borrowed("["))
    Text(Borrowed("]"))
    Text(Borrowed("(https://example.com?"))
    SoftBreak
    Text(Borrowed("id=foo)"))
  End(Paragraph)
]
```

It would be great if this could be addressed in pulldown-cmark :)

**Comment by keunes** [comment]
Hi, thanks for getting back on this. That would be a bummer. @mre any thoughts/comments?

**Comment by mre** [comment]
@keunes, if it's not part of the spec, we might be out of luck here. Is there a way to change the links in your document, such that there is no line break? That would probably be the easiest solution.

**Comment by keunes** [comment]
I read up on the specs and see where it's coming from (though I do wonder why the spec is like this, probably to avoid some technical issues?).

Our files are generated by another tool (mdpo) and it seems possible to not have a fixed line cut-off width. So I think I'll have to wipe all files and rebuild them without the cut-off.

Thanks both!
