### ISSUE TITLE
Inline HTML event is oddly glued to text up to end of line

### ISSUE THREAD

**Issue by dyoo** [raphlinus/pulldown-cmark#712]
In this example test, I was expecting to see two events:

```
fn main() {
    let parser = pulldown_cmark::Parser::new("<!-- this is a test --> Hello, world!");
    for event in parser {
        println!("{:?}", event);
    }
}
```

I was expecting to see:

```
Html("<!-- this is a test -->")     // modulo the borrow structure
Text(" Hello, world");
```

Instead, I see just one:

```
Html(Borrowed("<!-- this is a test --> Hello, world!"))
```

This is really odd because it depends on context: if the inline html is in the middle of more text, as in:

```
fn main() {
    let parser = pulldown_cmark::Parser::new("starting: <!-- this is a test --> Hello, world!");
    for event in parser {
        println!("{:?}", event);
    }
}
```

then this *does* have the behavior I was expecting to see in separating the comment from the rest of the content:

```
Start(Paragraph)
Text(Borrowed("starting: "))
Html(Borrowed("<!-- this is a test -->"))
Text(Borrowed(" Hello, world!"))
End(Paragraph)
```

so I suspect that this is a bug.

**Comment by Martin1887** [comment]
Right, this seems a bug. Thanks for reporting!

**Comment by dyoo** [comment]
A troubling issue, though, is that this appears to be defined behavior in the spec, in one of its test cases:  https://spec.commonmark.org/0.30/spec.json

https://spec.commonmark.org/0.30/#example-177

```
  {
    "markdown": "<!-- foo -->*bar*\n*baz*\n",
    "html": "<!-- foo -->*bar*\n<p><em>baz</em></p>\n",
    "example": 177,
    "start_line": 2869,
    "end_line": 2875,
    "section": "HTML blocks"
  },
```

and the spec does appear to say that this is expected, as what is happening is an HTML block, matching the second of the start/end condition cases.

https://spec.commonmark.org/0.30/#html-block

> If the first line meets both the [start condition](https://spec.commonmark.org/0.30/#start-condition) and the [end condition](https://spec.commonmark.org/0.30/#end-condition), the block will contain just that line.

and unfortunately, this means that my bug report is erroneous: the parser is doing exactly what the spec is saying should happen.  :(

Sorry for the noise.  I'll have to let @mgeisler know that this particular desired feature won't quite work the way we expected.
