### ISSUE TITLE
inconsistent behaviour of parsing &nbsp;

### ISSUE THREAD

**Issue by chungwong** [raphlinus/pulldown-cmark#713]
When `&nbsp;` is inside `<p>` it is unchanged but when it is inside a `<span>` it will get parsed to `\u{a0}`
I believe this applies to all block elements.
```rs
use pulldown_cmark::{Options, Parser};

fn main() {
    let opts = Options::empty();

    let mut s = String::new();
    let html = "<span>&nbsp;</span>";
    let p = Parser::new_ext(html, opts);
    pulldown_cmark::html::push_html(&mut s, p);
    dbg!(s);

    let mut s = String::new();
    let html = "<p>&nbsp;</p>";
    let p = Parser::new_ext(html, opts);
    pulldown_cmark::html::push_html(&mut s, p);
    dbg!(s);

    let mut s = String::new();
    let html = "<p><span>&nbsp;</span></p>";
    let p = Parser::new_ext(html, opts);
    pulldown_cmark::html::push_html(&mut s, p);
    dbg!(s);
}

// output
[src/main.rs:10] s = "<p><span>\u{a0}</span></p>\n"
[src/main.rs:16] s = "<p>&nbsp;</p>"
[src/main.rs:22] s = "<p><span>&nbsp;</span></p>"
```

There is an extra `\n` in the first case too.

**Comment by ehuss** [comment]
I believe this is working as expected. CommonMark treats `<p>` as an [HTML Block](https://spec.commonmark.org/0.30/#html-blocks) where all content inside the block is passed through without any parsing. `<span>` is not an HTML block, so content within a span gets translated like normal markdown.

**Comment by Martin1887** [comment]
Dingus (https://spec.commonmark.org/dingus/) does the same (except the final line break), so I think the issue can be closed:

![imagen](https://github.com/raphlinus/pulldown-cmark/assets/4211771/625076e8-8e0f-4e98-859c-6729b12b1c9a)
