### ISSUE TITLE
Output changed between 0.8.0 and 0.9.3

### ISSUE THREAD

**Issue by winks** [raphlinus/pulldown-cmark#714]
Hello there,
I just updated the crate from 0.8.0 to 0.9.3 and a diff showed me that e.g. this input:

```
Some [website](https://example.org/~foo/).
```

went from

```
Some <a href="https://example.org/%7Efoo/">website</a>.
```

to

```
Some <a href="https://example.org/~foo/">website</a>.
```

It doesn't really matter, the links still work, I'm just posting this because it was unexpected and I didn't see it mentioned in the release notes, but maybe it's related to the strike through change.

Thanks for making my life easier with this crate :)

**Comment by Martin1887** [comment]
Sorry for the delay in the response, this change was introduced in the following commit:

https://github.com/raphlinus/pulldown-cmark/commit/27f7cd588c6f6402c1cd50a000dd6f73452bd34e

Thanks!!
