### ISSUE TITLE
add "markdown"

### ISSUE THREAD

**Issue by 1268** [raphlinus/pulldown-cmark#717]
currently the repository description and topics are both empty for this repo. that means that if someone searches GitHub for:

~~~
markdown language:rust
~~~

they wont find this repo. further, even the entire area "above the fold" does not have the word "markdown":

https://github.com/raphlinus/pulldown-cmark/blob/dae2fcddbf95d66e6b42b77bcf330af553452fd0/README.md?plain=1#L1-L27

**Comment by raphlinus** [comment]
Thanks for the suggestion! I added a description and some topics. Does that address your concern?

**Comment by 1268** [comment]
thank you sir
