### ISSUE TITLE
Check for setext headers after parsing a paragraph

### ISSUE THREAD

**Issue by DemiMarie** [raphlinus/pulldown-cmark#75]
Setext headers can be multi-line, and should be checked for *after* a paragraph has been parsed, not before.

**Comment by marcusklaas** [comment]
We've recently landed a complete rewrite. Is this still an issue? If so, could you provide a short example?

**Comment by marcusklaas** [comment]
By looking at the code, we do in fact now check this after parsing paragraphs. Closing this until new information arises.
