### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by DerDrodt** [raphlinus/pulldown-cmark#757]
I just wanted to quickly ask if there is an ETA on a new version of pulldown-cmark.

Some dependents on this crate, like zola, would benefit from some new versions like the footnotes (see getzola/zola#1285).

**Comment by Martin1887** [comment]
There are two complex issues (#715 and #716) to be fixed before releasing it, but I hope it will be released in few days.

**Comment by DerDrodt** [comment]
Thanks for your quick response and the work on this project! I look forward to seeing what else is new.
