### ISSUE TITLE
Add an owned variant of Parser

### ISSUE THREAD

**Issue by LegNeato** [raphlinus/pulldown-cmark#778]
In my project I am hitting lifetime issues with the parser as it borrows the input string. While normally this is what I want to happen, sometimes it is easier to have the parser own the input string so I can pass them both around together without separate lifetime bookkeeping. My current project is full of iterators in iterators that create a parser and I have to do various collecting just to make the lifetimes work.

(I'm not great with lifetimes, please close if this does not make sense)

**Comment by Martin1887** [comment]
Without seeing the code it is difficult guessing, but just defining the strings before the outer loops would not work?

Also, hardcoded strings have `'static` lifetimes and the `lazy_static` crate allows to define compile-time things.

**Comment by LegNeato** [comment]
In my use-case it is extremely hard as I am layering iterators (acting as adaptors), so the lifetimes get super dicey quick. With my interior iterators `Parser` taking a reference is bubbling up through everything and preventing a specific `fold` due to lifetimes. I understand what is going on, and the problem is the lifetimes of the parser and source reference are disconnected, and (I assume) the `CowStr`s are causing issues with the events not lasting long enough.  I can't just clone the input as it is deep in an iterator and the locally cloned string does not live long enough. Collecting / allocating does not help, as I am collecting `Events` with `CowStr`s that still point to the string that doesn't live long enough.

**Comment by LegNeato** [comment]
Ok, it turns out I could do what I wanted by making everything borrowed rather than a mix of borrowed and owned. Closing as invalid.
