### ISSUE TITLE
It would be good to derive PartialEq on Event, Tag and Alignment

### ISSUE THREAD

**Issue by hhexo** [raphlinus/pulldown-cmark#80]
All underlying types of the Event, Tag and Alignment variants seem to implement PartialEq, so it would be nice to have PartialEq derived on the variants.

Suppose that I want to write a test for your "replace soft breaks with hard breaks" example. I want to test that other Events are unchanged, but I cannot easily compare them.

**Comment by raphlinus** [comment]
This was fixed by #118.
