### ISSUE TITLE
Foreign quotes support?

### ISSUE THREAD

**Issue by virtualritz** [raphlinus/pulldown-cmark#802]
It would be nice if [`Options::ENABLE_SMART_PUNCTUATION`](https://docs.rs/pulldown-cmark/0.9.3/pulldown_cmark/struct.Options.html#associatedconstant.ENABLE_SMART_PUNCTUATION): turned `'` and `"` into [localized quotes](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table).

An additional way to switch this on (`Options::ENABLE_LOCALISED_QUOTES`?) and select a supported language would be needed too, I guess.

No need to add detection of primary/secondary. The Markdown author itself should have control over this implcitly by using single/double quotes.

**Comment by Martin1887** [comment]
This is a relatively big feature, and I think it is out of the scope of the basic pulldown-cmark renderer.

Note the aim of this crate is basically parse Markdown, and the renderer is only a basic utility showing what can be do. An external renderer using pulldown-cmark is welcome, and this feature would be useful there, check #645.
