### ISSUE TITLE
Quadratic time consumption on pathological input

### ISSUE THREAD

**Issue by DemiMarie** [raphlinus/pulldown-cmark#82]
See commonmark/cmark#218.  Pulldown-cmark is also vulnerable:
```
$ python -c 'print("[a](<b"*50000)' | time pulldown-cmark >/dev/null
pulldown-cmark > /dev/null  9.80s user 0.00s system 99% cpu 9.831 total
```

**Comment by andersk** [comment]
Are you interested in further reports of this nature? The `new_algo` branch has a complexity regression compared to `master` where `"[](" * 50000` takes quadratic time instead of linear.

**Comment by raphlinus** [comment]
Yes, we will want to start addressing these. I think the new_algo branch is a good basis to start cleaning this up; some of these would be very hard to fix in master.
