### ISSUE TITLE
`cargo build` fails when `--locked` is passed for 0.9.4 and 0.9.5

### ISSUE THREAD

**Issue by CobaltCause** [raphlinus/pulldown-cmark#833]
I noticed that the most recent two releases (https://github.com/raphlinus/pulldown-cmark/commit/2332fa8ea2f04597052f972f7421ffaa402d22dd and https://github.com/raphlinus/pulldown-cmark/commit/377947d317607b958ca9406612ad90d3b16b30f3) both forgot to update `Cargo.lock` in addition to `Cargo.toml`. This discrepancy causes `cargo build --locked` to fail with an error like this:

```
error: the lock file /.../pulldown-cmark/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

Passing `--locked` is required for e.g. certain distro packaging methodologies. Also, it means that running `cargo build` without `--locked` will work but leave your git tree dirty, which is kinda weird.

Obviously this isn't really retroactively fixable, but hopefully this can be avoided in future releases.

**Comment by Martin1887** [comment]
Sorry, my fault. 0.9.6 has just been released and 0.9.5 yanked. Thanks for reporting.
